### ISSUE TITLE
Game does not open with Radial Mount Menu installed

### ISSUE THREAD

**Issue by Herouw** [Friendly0Fire/GW2Radial#101]
**Describe the bug**
When I perform the installation procedures, the game is not loaded. Login screen does not open.
Then "A serious error occurred ..."

**To Reproduce**
1. I put d3d9.dllem in my bin64 directory
1. I click to start game
2. Then do '...'
3. It does not load, and "A serious error has occurred"

**Expected behavior**
Login screen loads. I enter the game, and I can use the mod.

**Screenshots**

![Radial Error](https://user-images.githubusercontent.com/49153092/55325691-25d5be00-545c-11e9-834e-7817b1e56cfb.png)
![Radial Error2](https://user-images.githubusercontent.com/49153092/55325695-28381800-545c-11e9-97a7-1f54a6775718.png)

**System configuration (please fill in):**
 - Windows 10
 - GPU GTX1060ti
 - Ryze 5 2400G

**Additional context**
 When I change the name of "d3d9.dll" the game opens. But the mod does not work.
 I would love to use your mod. It just seems incredible.
 Sorry for any typing errors. I'm from Brazil, and I do not speak English. So I'm using Google Translate hahaha

Thanks <3

**Comment by Friendly0Fire** [comment]
I'm afraid the only troubleshooting I can give is to follow [these](http://gw2bgdm.blogspot.com/p/faq.html#2.5) instructions as outlined in the readme. If you've done that already, I don't have any other suggestion right now. We've never discovered what the source of this particular problem is.

**Comment by Myster-Marz** [comment]
I was having a somewhat similar issue, except I didn't get an error message, GW2 just wouldn't start after hitting play (after logging in). 
What ended up working for me was adding the Gw2-64.exe (and the CoherentUI_Host.exe, not sure if it matters) to the Windows 10 Ransomware Protection exception list.

You can follow the instructions here:
https://www.windowscentral.com/how-allow-blocked-apps-ransomware-protection-windows-10-october-2018-update

Hope this helps!

**Comment by Friendly0Fire** [comment]
That is a very interesting finding, thank you!

**Comment by Herouw** [comment]
Thank you >Myster-Marz for the help, but unfortunately it did not work yet
My Windows 10 Ransomware was not even active :(
Thank you >Friendly0Fire, but I tried [these](http://gw2bgdm.blogspot.com/p/faq.html#2.5) instructions and they also did not work :(

**Comment by Myster-Marz** [comment]
Herouw - Sorry to hear that it didn't work.. I'll keep an eye out for any possible solutions.

Friendly0Frire - No problem! I ran into this issue before when trying to use script extenders for Skyrim and Fallout 4.

**Comment by Necrodude** [comment]
Same issue. None of the recommendations worked.

**Comment by DeWinterish** [comment]
I used to have an intel cpu and i swapped to a ryzen 5 2600.
On intel it worked fine no issues .
On Amd it gives white screen of doom and no error ,just never loads.
Swap back to intel and its fine .
