### ISSUE TITLE
The shortcut:alt+shift+M can not open the main menu 

### ISSUE THREAD

**Issue by shuang0922** [Friendly0Fire/GW2Radial#103]
The shortcut:alt+shift+M can not open the main menu after i played the game a moment.
When i enter GW2 it is useful，but after a moment,nearly 10min,i could not use shorcut to open the main menu.

**Comment by Friendly0Fire** [comment]
You'll need to check for a rogue application on your machine. There is nothing in the addon that would make the shortcut stop working after a while.

**Comment by geoff-harper** [comment]
@Friendly0Fire what options are there for troubleshooting other than throwing darts at my task manager? I got the first time user window but default keybind does nothing

**Comment by Friendly0Fire** [comment]
I wish I could help you, but I don't even know what could somehow break the input management without also outright breaking the entire addon (since you saw the welcome window, it's obviously running).
