### ISSUE TITLE
Game Crash. exception: c0000005

### ISSUE THREAD

**Issue by BreakingForce** [Friendly0Fire/GW2Radial#109]
**Describe the bug**
when i have gw2radial installed, my gw2 crashes before loading the character screen.  it worked just fine until 4/28.  i have no clue what changed.  gw2radial is the only non-standard thing i run with gw2 (no arcdps or gw2taco or anything similar).  i remove the radial and i load just fine without crashing.  reinstall radial, crash. i tried repairing and then uninstalling and reinstalling gw2.  the only thing that seems to solve it is removing gw2radial. 
**To Reproduce**
1. install gw2radial
2. launch gw2
3. Bad stuff happens

**Expected behavior**
i expected gw2radial to work as intended

**Screenshots**

**System configuration (please fill in):**
 - OS: Win 10 Pro 64 bit
 - GPU:  GTX970
 - Chainloading, if any [e.g. arcdps -> GW2Radial -> GW2Hook]
none
**Additional context**

**Comment by BreakingForce** [comment]
makes me sad, because i like gw2radial :X

**Comment by willgk** [comment]
Would be nice to see a comment on this as I am having it as well, only using this addon.
