### ISSUE TITLE
Skyscale

### ISSUE THREAD

**Issue by andrei9669** [Friendly0Fire/GW2Radial#110]
update radial mount menu to include scyscale

**Comment by Kidel** [comment]
Seconding this, but I'll add a "please" :)

**Comment by praetoras** [comment]
I will third this! I would really like the Skyscale and other mounts to be added!

**Comment by Kidel** [comment]
Found this fork: https://github.com/dameischta/GW2Radial
The art is a bit different, but it works fine.

**Comment by dameischta** [comment]
> Found this fork: https://github.com/dameischta/GW2Radial
> The art is a bit different, but it works fine.

I know...the icon of Skyscyale looks terrible....i'm not an artist :-)

**Comment by Kidel** [comment]
Never said it was worse. Just different.
