### ISSUE TITLE
Radial breaks the whole GW2 installation for running arcdps

### ISSUE THREAD

**Issue by Emerald-12** [Friendly0Fire/GW2Radial#112]
**Describe the bug**
At any point after Radial is introduced to my game the game will not function if arcdps is installed, this includes after having uninstalled radial or both and the reinstalled arc. The game has to be reinstalled to be able to run arc-

**To Reproduce**
1. Install Arcdps
2. Test that the game works
3. Install Radial
4. Game does not work, so remove Radial
5. Game still doesn't work, so remove Arc
6. Game now works, so install a fresh arc download
7. Still doesn't work

**Expected behavior**
I either expect Radial to work with arc, or at least not work but also not ruin the game installation.

**System configuration:**
 - OS: Windows 10
 - GPU: Radeon RX480
 - Chainloading. arcdps -> GW2Radial

This occured to me after the 14th of May patch with arc, but I have friends who do not have the same problem

**Comment by Friendly0Fire** [comment]
If by "remove Radial" you're deleting the DLL or renaming it, then the problem you're seeing is not due to this addon. It's impossible for any addon to cause a problem when it's no longer being run.

**Comment by Emerald-12** [comment]
I have a hard time seeing how it could work myself, but at any point after introducing Radial to my game, no matter what i do afterwards the game will not launch with arcdps installed, even if it is the only addon installed.

**Comment by Friendly0Fire** [comment]
- Are you 100% certain your arcdps version is up to date? Not reusing an old download by mistake or something?
- What exactly happens when the game is broken?
- How do you "uninstall" the addons exactly?
- Do you have *anything* else running on your machine that could cause conflicts? Stuff like Afterburner or any other overlay (e.g. Steam) could do it.

**Comment by Emerald-12** [comment]
Arcdps version is up to date, i have even tried to use arcdps files my friends have given me.
The game will never go past it's launcher state, launching the game results in nothing but the process shutting down without an error message.
I uninstall it my removing the .dll files from the bin folder, not sure there is anything else to do since it is basically a "reverse install".
I don't blieve i have any overlays running.

**Comment by Friendly0Fire** [comment]
Well let's at least try to eliminate one potential source. Next to the `bin` folder, there should be an `addons` folder. Try deleting the `gw2radial` first with the addon uninstalled and see if it works. If not, keep arc installed but delete its config folder.

Deleting those should be functionally identical as uninstalling and reinstalling the game, so we can check where things break.

**Comment by Emerald-12** [comment]
I honestly don't know anymore. Before i posted the issue here i tested for almost an hour and it was always related to installing Radial, now it just happens with arc alone.

**Comment by Friendly0Fire** [comment]
Does GW2Radial alone work then?

**Comment by Emerald-12** [comment]
Yes it does, it now seems to be a problem between arcdps and my computer somehow

**Comment by Friendly0Fire** [comment]
Very odd. I wish you luck though!

I'll close this, feel free to reopen if it turns out GW2Radial is partly responsible after all.
