### ISSUE TITLE
System error : d3dx9_43.dll

### ISSUE THREAD

**Issue by DoNotBlameItOnMe** [Friendly0Fire/GW2Radial#117]
Have a system error when i launch the client.
![Sans titre](https://user-images.githubusercontent.com/51187337/58610465-d3721b80-82ab-11e9-940d-81744baf0771.jpg)

**Comment by Friendly0Fire** [comment]
You're somehow missing the latest version of DirectX 9. Download it here: https://www.microsoft.com/en-us/download/details.aspx?id=35

**Comment by DoNotBlameItOnMe** [comment]
Thank you woked now
