### ISSUE TITLE
Graphical Bug with Griffon and Roller Beetle.

### ISSUE THREAD

**Issue by GriffithLG** [Friendly0Fire/GW2Radial#119]
**Describe the bug**
The graphic for the Roller Beetle mounts the Griffon and vice versa. 

**Screenshots**
[https://gyazo.com/dedac9866e935f1744fc0b50afe63036](url)
[https://gyazo.com/06755cd5934e4ab6e3057efa55fb1f6b](url)

**System configuration (please fill in):**
 - OS: [Windows 10]
 - CPU [Ryzen 1800x]
 - GPU: [GTX1070]
 - Chainloading [arcdps -> GW2Radial]

**Comment by Friendly0Fire** [comment]
Uh... Check your keybinds? This would've been reported ages ago if it were an actual bug.
