### ISSUE TITLE
Missing Overlay keybind issue

### ISSUE THREAD

**Issue by Avekube** [Friendly0Fire/GW2Radial#120]
The option to keybind the main radial overlay is missing.

**To Reproduce**
Install add on by following instructions on github.
Open GW2
Open the addon menu with alt-shift M
Go to the mounts section (other sections might be missing it too)

**Expected behavior**
Expecting a subsection of Mounts section to have a line to keybind the overlay based off screen shots found online and verifying with a guild mate who has also used the add on.

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: Geforce 1060
 - Currently not chain loading

**Additional context**
GW2 is not installed on C: Drive, but on a secondary drive instead. Tried rebooting GW2 multiple times. Also tried deleting the add on file from GW2 and re adding it from the original extracted folder.

**Comment by Friendly0Fire** [comment]
Sorry, but you're expected to actually fill in the report. I can't help you with no details.

**Comment by Avekube** [comment]
Sorry I don't know what happened, I had it all filled out before. Will edit it now.

**Comment by Friendly0Fire** [comment]
Ah! You're looking for the "Show on mouse" or "Show in center" keybinds. They were simply renamed.

**Comment by Avekube** [comment]
You're right, I tried that before I had the rest of the keybinds working, so I didn't think that was it. I should have tried that afterwards too. Thank you for your trouble/time.
