### ISSUE TITLE
The radial won't work

### ISSUE THREAD

**Issue by NeuerWind** [Friendly0Fire/GW2Radial#121]
Basically, the radial won't appear at all, and I can't pick any mounts, it's not that the images don't load, it's just that the interface won't load.

1. I configured the radial to appear with the letter B
2. When I put to lock on the center, the pointer will actually move to the center, but still nothing will appear

On a side note, the camera lock on will always lock the camera, not only when I press the key.

**System configuration (please fill in):**
 - OS: Windows 10 home
 - GPU: amd RX 580
 - CPU: amd Ryzen 5 1600
 - Chainloading: gw2radial => arcdps

**Additional context**
The interface for options works, but the wheel doesn't, I also tried doing hotkeys for the marker wheel, and it doesn't work either.

**Comment by Friendly0Fire** [comment]
Have you tried without arcdps? Also, while pressing down on your activation key, is there a little glow around your cursor?

**Comment by NeuerWind** [comment]
I tried it without arcdps, still nothing. also, there's no glow around my cursor. I first put an old version of the addon without knowing, but it didn't work, so I checked and found the newest version, maybe it has to do with option files from the old version interfering with the new one? I'll try that too

**Comment by NeuerWind** [comment]
welp, removing the option files didn't help either, it just erased the hotkey I had for the wheel, it still doesn't do anything sadly

**Comment by kevinhav** [comment]
Having the same issue, but not using any other addons at all
