### ISSUE TITLE
System error: couldnt find attach points 47 and 54

### ISSUE THREAD

**Issue by BearsMan** [Friendly0Fire/GW2Radial#123]
**Describe the bug**

**To Reproduce**
1. Do '...'
2. Then do '...'
3. Bad stuff happens

**Expected behavior**

**Screenshots**

**System configuration (please fill in):**
 - OS: [e.g. Windows 10]
 - GPU: [e.g. GTX1080]
 - Chainloading, if any [e.g. arcdps -> GW2Radial -> GW2Hook]

**Additional context**

System error: couldn't find attach points 47 and 54

OS = Windows 10 Home
GPU = NVIDIA GeForce 940M
Chainloading - Arcdps, GW2Radial, and GW2Hook is running

**Comment by Friendly0Fire** [comment]
Sorry for the belated answer (you probably fixed it by now), but those are arcdps errors so I can't really help.
