### ISSUE TITLE
Impossible to cancel the little welcome window when launching the game

### ISSUE THREAD

**Issue by DXWALK** [Friendly0Fire/GW2Radial#124]
The little window welcoming me using radial and using shift alt m to bind keys won't leave my screen. I can't even click ok.

Using Reshade and arcdps too, maybe that's an issue ?

Because of shift alt m not working, I'm stuck at the first version of the radial menu, only with the 5 first mounts :(

**Comment by Friendly0Fire** [comment]
If you think Reshade/arc are the issue, have you tried without them? Are you following the prescribed load order for them?

**Comment by DXWALK** [comment]
I tried, doesn't work, it cancels arcdps. I guess it's a deadend then :c

Le ven. 23 août 2019 à 18:38, FriendlyFire <notifications@github.com> a
écrit :
