### ISSUE TITLE
Old version still comes up

### ISSUE THREAD

**Issue by KrazyKubrow** [Friendly0Fire/GW2Radial#126]
Shift+alt+M brings up the old OLD version of the mod (I haven't updated in some time)

I've uninstalled everything I could and yet, when running the game without any d3d9.dll or otherwise (vanilla) I still get the old menu with my old keybind and the old Options window. NOTHING I'm doing is fixing this. what do I need to do???

**Comment by Friendly0Fire** [comment]
Look again for another old version of the addon. There's no other possible reason.

**Comment by KrazyKubrow** [comment]
there are no other files. legit the only other d3d9.dll is in my system32
file for windows. is it possible the mod is baked in??

**Comment by Friendly0Fire** [comment]
It is literally impossible for any addon to magically work without being there. You did not remove all of the files, there is no other option.

**Comment by KrazyKubrow** [comment]
please allow me to provide evidence that this is exactly what's happening.

Take note the times at the bottom right both in game (minimap) and not (excuse the lag in the gif. where wasn't any when I was captureing it.) to prove that the mod is uninstalled completely with no leftover files.
https://i.gyazo.com/39e5974d44471e2a018d93b0c22b9eb4.png
https://i.gyazo.com/addc7399088ac92ec76cb4721ddc5a57.png
https://i.gyazo.com/d3818c1f41477d03ba9fe766a3bf6c11.mp4

**Comment by ThermoMan** [comment]
Look in your C drive perhaps?  Have you rebooted your PC since you removed the files?  Otherwise it's magic.

**Comment by Friendly0Fire** [comment]
The only reasonable explanation I can think of is that you are not running the copy you're looking at. Make sure the executable for the game is indeed the one in that path, `D:\gw2\Guild Wars 2\`.

If this is not the case, then you'd have had to modify the OS in some fashion, which sounds unlikely. There is no possible way for the addon to magically insert itself into the game permanently.

**Comment by KrazyKubrow** [comment]
My install file is in my D drive and I have rebooted my PC. My shortcut opens to the path to my D drive. Both are the first things I've done.

I really don't want to have to reinstall because I just wanted to update my radial mod. 

Before you ask I did try to just put in the new version of it to try and override. It worked once perfectly, then when I came home from work it reverted back to the old mod when I logged back in. I've not been able to get another updated version to work again after that. not even from a fresh 30 second old file.

**Comment by KrazyKubrow** [comment]
Screw it. I'll just reinstall the game tonight. nothing seems to be fixing it at all. Probably a good Idea anyhow.

**Comment by Friendly0Fire** [comment]
Shortcuts have both a "Target" and a "Start in" folder. Is the "Start in" box either blank or pointing to the right folder? Have you tried starting the game directly from the folder by double-clicking `Gw2-64.exe`?

**Comment by KrazyKubrow** [comment]
yes and yes. as I've said before I've checked, rechecked and triple checked just to fix it. I'm reinstalling the game now so either way it'll be dealt with.
