### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by blagsneeky** [Friendly0Fire/GW2Radial#127]
**Describe the bug**
game crashes when interacting with the menu on verions after the novatal update crashes on start up with the latest skyscale radial update

**To Reproduce**
1. open game
2. click on the shift+alt +m menu
3. Bad stuff happens

**Expected behavior**
expected it to run and me being able to interact with the menu

**Screenshots**

**System configuration (please fill in):**
 - Windows 10
 - GTX1080 x2
 

**Additional context**
completly crashes out for the skyscale the only version i can use is the novalty update

**Comment by Friendly0Fire** [comment]
Usual steps: disable any other addon you might use, make sure your drivers are up to date, disable SLI.

**Comment by blagsneeky** [comment]
sorted it, turned off sli launched it and played with the menu then turned sli back on and relauched it and it works love this wheel!
