### ISSUE TITLE
Radial Menu for Build Template Selection

### ISSUE THREAD

**Issue by dewabuanam** [Friendly0Fire/GW2Radial#128]
Radial Menu for Build Template Selection.
Menu for equipment template selection.
Menu for build template selection
Menu for custom combination build and equipment template selection.

**Comment by Sylarheart** [comment]
I was going to ask this aswell. This would save us so many keypressing.

**Comment by MidoriKami** [comment]
And ideally the ability to have one button to switch BOTH Equipment AND Skills. The fact that Arenanet doesn't allow you to bind those to the same key is astonishing to me.

**Comment by Sylarheart** [comment]
> And ideally the ability to have one button to switch BOTH Equipment AND Skills. The fact that Arenanet doesn't allow you to bind those to the same key is astonishing to me.

Indeed.

**Comment by Si13n7** [comment]
@Friendly0Fire seems a bit inactive at the moment. :sweat_smile:

Therefore, I extended **GW2Radial** for me and added menus for armor and build templates. You will find it [here](https://github.com/Si13n7/GW2Radial/releases/latest) if you don't want to wait for an official solution. :wink:

_But please note that I have **not** added the ability to switch both with a single button. At first, I had plans to add that too. However, I discovered during testing that I don't need it myself. So please don't ask, I'm just sharing something that I did exclusively for myself._ :stuck_out_tongue:

**Comment by Sylarheart** [comment]
> @Friendly0Fire seems a bit inactive at the moment. 😅
> 
> Therefore, I extended **GW2Radial** for me and added menus for armor and build templates. You will find it [here](https://github.com/Si13n7/GW2Radial/releases/latest) if you don't want to wait for an official solution. 😉
> 
> _But please note that I have **not** added the ability to switch both with a single button. At first, I had plans to add that too. However, I discovered during testing that I don't need it myself. So please don't ask, I'm just sharing something that I did exclusively for myself._ 😛

Thank you Sir. That's amazing!

**Comment by tkrause** [comment]
Has this been merged into this project? I'm not seeing it in the latest version only the fork.

**Comment by Si13n7** [comment]
@tkrause you need [GW2Radial 2.0](https://github.com/Friendly0Fire/GW2Radial/releases/tag/v2.0.0-alpha). It's still alpha for some reason, but it works pretty well. @Friendly0Fire didn't add any new menus, but instead added new features that allows you to create custom menus for all of your needs. So I'm not going to update the code of my fork anymore, instead I added a [new release](https://github.com/Si13n7/GW2Radial/releases/tag/v2.0.0) with only custom menus for armor and build templates for 2.0. Feel free to use, duplicate and modify. I don't care.

The customization is very easy to use. You can even easily duplicate my custom menus. All you have to do is open the zip file that you copied and change the `nickname` and `display_name` values. This way you could, for example, create different build template menus for different characters. This is very useful as armor and build templates are soulbound and your characters may not have all of them unlocked equally.
