### ISSUE TITLE
[Bug] Not working with the latests update

### ISSUE THREAD

**Issue by Arturoe1** [Friendly0Fire/GW2Radial#130]
**Describe the bug**
A fresh install of the pluging in a the latests update does not show the welcome window either open the menu with Shift+Alt+M. The addon folder is created thou with an empty config file. 

**To Reproduce**
1. copied the dll file toD:\Guild Wars 2\bin64\ folder. no result.
2. copied the dll file to D:\Guild Wars 2\. no result.
3. Bad stuff happens

**Expected behavior**
does not show any menu or welcome window. 

**Screenshots**

**System configuration (please fill in):**
 - OS: [e.g. Windows 10] Windows 10 latest update. 
 - GPU: [e.g. GTX1080] RTX 2070 
 - Chainloading, if any [e.g. arcdps -> GW2Radial -> GW2Hook] Just Gw2 radial 

**Additional context**
The Gw2 directory is in the custom in the secondary harddrive. D:\Guild Wars 2.

An example of the config file would be a good as i could try if it's just a graphical glitch or the addon is not enabled testing an already setup config.

**Comment by SecurityStatement** [comment]
Yep, I am now having the same problem. Updated in the last couple of days, and now I no longer get the greeting and opening the menu does not work. This was just working right before the latest update.

**Comment by f3ck4r** [comment]
Same problem ¬¬

**Comment by adrianpavone** [comment]
Attempting to use this plugin for the first time.

I *did* get the welcome window (which wasn't dismissable, I had to change the config to get it to stop showing, but that's a different issue), but am getting no response to Alt-Shift-M. Without this, I cannot set keys for the radial menu or even bring it up (as no options exist in the config files for this), making the addon unusable in its current state.
