### ISSUE TITLE
Non official Game Bug

### ISSUE THREAD

**Issue by NoahBodee** [Friendly0Fire/GW2Radial#131]
I can't seem to get GW2Radial to work with the multi game launcher Gw2Launcher found at https://github.com/Healix/Gw2Launcher

It worked the first few times I had it installed but suddenly it won't work at all and will not pop up the radial on both instances of Guild Wars, only on the first instance launched. I've not done anything different and have no idea if a recent game update may have changed something.

The hotkey to launch GW2Radial doesn't work now in the second account (which it used to), nor does the mount hotkey, which is the same as the primary account. The pet hotkeys are also the same in both accounts.

I do hope you can get this working with Gw2Launcher as it's a great way to deal with multiple accounts on only 1 computer.

Thank You

**Comment by SecurityStatement** [comment]
This may be an update issue. There is another thread that was opened, that I also commented in, about this same issue. Tried to redownload this and it is still not working for me currently.

**Comment by NoahBodee** [comment]
Glad it's not just me. Hopefully it can be figured out and fixed.

 
 

Sent: Friday, November 29, 2019 at 4:11 AM

**Comment by unrelentingsarcasm** [comment]
I'm having a similar issue with GW2 LaunchBuddy.  I use it to run multiple accounts and for the software injection feature for ArcDps, d912pxy (this is absolutely necessary to keep me from having a black screen error), ReShade (really GW2Hook), and TacO.  But there's no way for me to get GW2Radial to work with it.

**Comment by Friendly0Fire** [comment]
This will be resolved in the next release provided you also use GW2Launcher's MumbleLink rename feature:
![image](https://user-images.githubusercontent.com/3399000/132998160-9e959b8c-4aa9-4f87-92cc-7b242bc7dc04.png)
