### ISSUE TITLE
Cannot type in the Input Boxes of the Options Menu to Assign Keybinds

### ISSUE THREAD

**Issue by Levinus14** [Friendly0Fire/GW2Radial#132]
I just really can't type into it...

I downloaded the mod and followed your instructions after the installation, 
opened gw2 and, with it of course, 
also opened the options menu's "greetings" or whatever window almost immediately afterwards the gw2's program start-up,
pressed shift+alt+M, which opened up the Options Menu,
and followed your instructions about the assignment of keybinds that you have shown in the read.md images in your github... 
after that, i just cant type in the keys
Like, my the keys on my keyboard just wont put in letters and numbers in it; i dont know, its just does not show that i am typing in the input boxes of the Options Menu.

Everything else in my laptop seems to work fine though, I think... (I did not play the game immediately after the installation, by play I mean did not log in with my character and then play within the servers) I immediately go here to report lol, just found this occurrence annoying.
 
Expected it to run smoothly and fine... just can't type into it :<

Well, all in all, everything is fine, except for the fact that me, trying to type in keys into it just cant spawn the letters and numbers within the input boxes; only blank spaces and a cursor (insertion point) blinking and out.
 
**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: Intel(R) UHD Graphics 605
 - No chainloading, your add-on is the first mod that I have tried in not only gw2, but any games in general within my whole life :D

Everything that I found important was already said; no further context are needed.

**Comment by Friendly0Fire** [comment]
You're correctly pressing the Set button before trying to enter your keybind, right?

**Comment by Levinus14** [comment]
Yes... Thought my keyboard is the problem, but it works as fine as any
normal keyboard out there.
