### ISSUE TITLE
Discord Overlay Incompatible - Please revisit

### ISSUE THREAD

**Issue by WareWolf-PDX** [Friendly0Fire/GW2Radial#137]
Hello,

I know this was opened and closed a couple of years ago, but I'd like to see if anything new has come available to possible resolve this issue. Many of us use Discord for voice comms or guild chatter between folks both in and out of the game, and having these two together is unfortunately a bad combination. 

From what I've experienced, they argue with each other for control, where sometimes I have the mount radial and sometimes I have the overlay for Discord. Often, attempting to use both will within minutes result in a GW2 client crash.

**Comment by Friendly0Fire** [comment]
Discord's overlay is not open source, so I have no way of knowing what they're doing that might clash. Unfortunately, I don't have any way to diagnose or fix.
