### ISSUE TITLE
New MumbleLink features!

### ISSUE THREAD

**Issue by Friendly0Fire** [Friendly0Fire/GW2Radial#140]
* [x] Make use of mount data to determine if mounted and on which
    * Can show a "Dismount" option replacing the currently mounted mount (with the option of moving that to the first slot on the wheel or the center)
    * Can finally auto switch to another mount by first dismounting, waiting for the state to change to dismounted, then mounting (should be an option as well)
* [x] Make use of in combat flag
    * Can "save" mount up action until out of combat and immediately mount then
    * Can hide the mount wheel while in combat
    * [x] Need to show some kind of spinner/countdown around the cursor if an input is queued
* [x] Make use of game focus/input focus/map state
    * [x] Disable sending input until game has focus and input doesn't have focus and map is not fullscreen
    * [x] ~~Add option to drop chat focus (Esc key?), do action, then give chat focus again?~~

**Comment by ThermoMan** [comment]
I believe that the Auto change mount function would require two keystrokes sent to the game and that would violate TOS.  One click = one key.

**Comment by dameischta** [comment]
please tell me you're working on this :)
