### ISSUE TITLE
Freeze at character select

### ISSUE THREAD

**Issue by dk728** [Friendly0Fire/GW2Radial#141]
**Describe the bug**
So I've been using the first milestone version for a while now, and recently got back to the game and saw that there was an update to the ad on, thought of installing it but i tried every version and the only one that was able to work without my game freezing at character select, would be the first milestone version.

Additionally as im a returning player, ive only unlocked the roller beetle and yet to unlock skyscale and warclaw, is that the issue?

**To Reproduce**
1. Do 'moved the dll file to the bin folder'
2. Then do 'proceed to start up'
3. Bad stuff happens

**Expected behavior**
Use the new updated interface

**Screenshots**
just a blank screen

**System configuration (please fill in):**
 - OS: [e.g. Windows 10]
 - GPU: [e.g. GTX1050ti]

**Additional context**
Unlocked roller beetle but not warclaw and skyscale, game ran well with 5 mounts on radial, unable to use new dll files

**Comment by Friendly0Fire** [comment]
Do you have other addons? Have you tried erasing the config INI in the game's folder?

**Comment by dk728** [comment]
> Do you have other addons? Have you tried erasing the config INI in the game's folder?

Nope i only use radial, and i shall try that :) thanks much, if there are any other inquiries i'll post here ^^

**Comment by dk728** [comment]
There are two files inside, the config file and imgui_config, which do i remove?

**Comment by Friendly0Fire** [comment]
Both.

**Comment by dk728** [comment]
I just tried removing both files but it still freeze then crashes at the character select

**Comment by Friendly0Fire** [comment]
Try installing the latest Visual C++ redist: https://aka.ms/vs/16/release/VC_redist.x64.exe

**Comment by dk728** [comment]
Hi i installed the latest Visual C++ But it still crashes :(

**Comment by Friendly0Fire** [comment]
Do you have anything running in the background like MSI Afterburner, RTSS, etc.? These are known to interfere.

**Comment by jiangyi0923** [comment]
Do you have any razer equipment? He will install a software, which will interfere with the operation of the plug-in. I don't know its English name, but there is a screenshot in Chinese. If there is this software, please stop using it or uninstall it
![2002222000](https://user-images.githubusercontent.com/40364405/84023226-4a132000-a9ba-11ea-8789-9b9158e5c058.png)

**Comment by dk728** [comment]
@Friendly0Fire Nope none of those
@jiangyi0923 Yes i do have it and okay i shall try it
