### ISSUE TITLE
Selecting Griffon open the Roller Beetle and vice versa

### ISSUE THREAD

**Issue by Swystix** [Friendly0Fire/GW2Radial#142]
The Griffon option opens Roller Beetle and Beetle opens the Griffon. 
Looking through the menu I can't see why it is doing this, is there something simple that I am not seeing?

Thanks

**Comment by Friendly0Fire** [comment]
Sounds like you've got your keybinds switched around. Check the game options *and* the addon's settings and make sure the keys match.
