### ISSUE TITLE
GW2 Radial not working for me.

### ISSUE THREAD

**Issue by kraychanjh** [Friendly0Fire/GW2Radial#143]
**Describe the bug**
I have Arcdps installed and working. I want to add Gw2Radial so I proceeded to download and put into Gw2 bin folder with the necessary rename/changes for the .dll files. Proceed to load Gw2 up, I got the pop up and the menu. The keybind for show in center was binded, I click the keybind but it only centralize my mouse cursor with no glow effect. No mount pop-up and nothing happens.
Arcdps is still working fine if that's relevant.

**To Reproduce**
Had ArcDps installed and was working fine.
Proceed to install Gw2Redial with the necessary changes to the rename of .dll files according to guide provided.

**Expected behavior**
Gw2 Radial mount menu to glow up/appear.

**Screenshots**

**System configuration (please fill in):**
 - OS: Windows 10 
 - GPU: Nvidia 940MX
 - Chainloading, [arcdps -> GW2Radial]

**Additional context**
I do not have all the mounts yet if that is relevant, only Jackal and Bunny!

Thank you for your time!

**Comment by Friendly0Fire** [comment]
Did you setup your mount keybinds in the addon properly? If none are bound, the wheel will be empty.

**Comment by kraychanjh** [comment]
Hi, 

I just did and it's working well now!

Thank you for the trouble in responding.
