### ISSUE TITLE
[BUG]Cant open options menu

### ISSUE THREAD

**Issue by pips-queek** [Friendly0Fire/GW2Radial#144]
**Describe the bug**
Cant open the options menu to configure the overlay 

**Workaround Attempts**
1. Un/Reinstalled
2. Unbound Map 'M'
3. Removed Microsoft keyboards to see if their hotkey was interfering (shift+alt)
4. Changed fulscreen->windowed FS -> windowed
5. Tried dropping entire folder in bin
6. Relogging

**Expected behavior**
pressed ctrl+shift+m to open options. nothing opens

**System configuration (please fill in):**
 - OS: WIN10
 - GPU:GTX1650

**Comment by Friendly0Fire** [comment]
The keybind is Alt+Shift+M, not Ctrl+Shift+M.

**Comment by aragog53** [comment]
Hi! I was able to reproduce this, I'm pretty sure it's related to "Complete rewrite of keyboard input handling."

Explanations: My keyboard setup is fr-azerty, I can't either open settings menu anymore on 2.0 with Alt+Shift+M

BUT using Alt+Shift+,  "," being where Qwerty M should be works. I did not have to change Windows keyboard input setting btw.

**Comment by minecrawler** [comment]
Cannot open the menu when chainloading the ArcDPS-Chainloader + ReShade. I'm using a QWERTY international layout keyboard!

**Comment by Friendly0Fire** [comment]
This should be fixed with the next release.
