### ISSUE TITLE
Once radial menu activated, cursor will not move

### ISSUE THREAD

**Issue by raffenit** [Friendly0Fire/GW2Radial#145]
Hi there, I've used this software on my main PC for months and it's worked perfectly fine. I recently tried installing on a secondary pc (a laptop), and for some reason I cant seem to move my cursor while the mount menu is displayed. If I move my cursor to a position on the wheel before activating, then activate the wheel, it selects the mount properly. I just can't move the mouse while it's visible. Any ideas? Is this maybe a setting somewhere?

EDIT: This only occurs when using the track pad, a USB mouse works fine

**Comment by Friendly0Fire** [comment]
I cannot replicate this as of now, so if this comes up in the upcoming release, please reopen.
