### ISSUE TITLE
Problem while installing via addon manager

### ISSUE THREAD

**Issue by Shikaa** [Friendly0Fire/GW2Radial#147]
Hi,

When i try to install GW2Radial via addon manager, it told me it work but it didn't. 

Since the last GW2 version on 07/07/2020, the version of d3d9.dll download by addon manager make my game crash immediatly. (i try to download addon manager the 08/07/2020 but it didn't change anything)
So i uninstall my addons and download manually d3d9.dll on the arcdps website to make arcdps and GW2 work again. (and it work now)
Then i used addon manager to install GW2Radial but it's not working in game.

Im playing on W10.

Am i doing it wrong or the last version broke the system? Is there any method to install gw2radial whithout addon manager?

thanks

**Comment by Friendly0Fire** [comment]
You cannot use the addon manager to install GW2Radial (or any other addon) if you overwrote `d3d9.dll`.

Follow the instructions in the [readme](https://github.com/Friendly0Fire/GW2Radial#installation).

**Comment by Shikaa** [comment]
thanks, it works! 
I don't know why but when i look the part "how to install" on readme it only says "via addon manager" and i wasn't able to found the .zip and the d3d9.dll you just gave me.

I rename it d3d9_chainload.dll as you mention it and all work perfectly even with arcdps :)
