### ISSUE TITLE
d3d9.dll only works from game directory

### ISSUE THREAD

**Issue by Valera512** [Friendly0Fire/GW2Radial#149]
**Describe the bug**
Since 2-3 months my radial d3d9.dll only works from the game directory - not from bin64. However, that way I can't use ARCDPS in combination with gw2radial anymore.

I tried different combinations:
- **Both** (arcdps as d3d9.dll, gw2radial as d3d9_chainload.dll) **in bin64** -> only arcdps works
(deleting the addon-file beforehand creates only a new arcdps-file)
- Only **gw2radial as d3d9.dll in bin64** -> nothing
- **Both in game directory** -> only gw2radial works
- **arcdps as d3d9.dll in bin64, gw2radial as d3d9_chainload.dll in game directory** -> only arcdps works
- **arcdps as d3d9.dll in bin64, gw2radial as d3d9.dll in game directory** -> only gw2radial works

I can't think of anything resolving that problem, but maybe you have an idea.

Thanks

**System configuration:**
 - OS: [Windows 10]
 - GPU: [GTX1060]
 - Chainloading, arcdps -> GW2Radial

**Additional Info**
- I use the newest version of ARCDPS and gw2radial
- I don't use any shortcut to skip the login prompt

**Comment by Friendly0Fire** [comment]
How are you launching the game? If using a shortcut or something, have you tried launching by directly clicking the EXE?

**Comment by Valera512** [comment]
I normally use a shortcut, but for the above results, I also tried clicking the GW2-64.exe directly.
The strange thing is that if i delete the addon folders and try launching the game with only gw2radial as d3d9.dll, the folder is only recreated if i put it directly in C:\Program Files\Guild Wars 2.

**Comment by Valera512** [comment]
I just discovered your new 2.0 alpha release. As recommended there, using GW2-Addon Manager fixed it for me, as that tool seems to integrate all addons into one d3d9.dll.
So unless some people stumble upon this problem again, while wanting to use v2.0 as a standalone, I think you can close that Issue.

**Comment by Friendly0Fire** [comment]
I'm really glad it's working!
