### ISSUE TITLE
Question: Chat window input

### ISSUE THREAD

**Issue by Myster-Marz** [Friendly0Fire/GW2Radial#150]
"Radial menus will not send keybinds to text boxes such as the chat box. This will effectively cancel the action however."

Would it be possible to have this as a feature that we could turn on and off per custom menu?

P.S. Loving the update so far! Thanks for putting in the hard work to make this possible and for making the controls in this game more manageable for a controller user like myself!!!

**Comment by Friendly0Fire** [comment]
Unfortunately, chat box interactions are a Pandora's box that will most likely result in breaking the 1:1 interaction restriction ANet has put in place. I'd rather avoid giving people the ability to potentially break the rules and get banned, even if the chances are astronomically low.

You can of course fork this repo and change the [one line](https://github.com/Friendly0Fire/GW2Radial/blob/5d871a8000af18f2d4a6a41250aeaf737010b95e/GW2Radial/src/Input.cpp#L442) that controls this, but that's as much as I can give you, sadly.

**Comment by Myster-Marz** [comment]
I completely understand. I was going to try and make a emote radial menu, but its probably not worth the risk. Thanks for the hint about the code. I'm gonna try and see if I can get the okay for this from someone at Anet before making any changes. Thanks!
