### ISSUE TITLE
Alpha - reset queue & change mount via "1 click"

### ISSUE THREAD

**Issue by dameischta** [Friendly0Fire/GW2Radial#152]
- when a mount is in queue (because in combat), use middle section / inner circle of wheel to disable queue
- when on mount, then "1 click" to change to another mount (might interfere with arenanets "one click, one action" policy for macros)

**Comment by Friendly0Fire** [comment]
First suggestion is possible, probably will be an option. Second suggestion is definitely out of bounds unfortunately.
