### ISSUE TITLE
Armor & Skill Template Swapping Suggestion

### ISSUE THREAD

**Issue by leosaurd** [Friendly0Fire/GW2Radial#153]
1. Allow for Armor/Skill template swapping as an additional menu, as they have hotkeys in the game to quickswap. As the hotkeys are allowed, I think it should align with one button, one action.

**Comment by Friendly0Fire** [comment]
Requests for new radial menus without special behaviors are now redirected to the [custom wheels](https://github.com/Friendly0Fire/GW2Radial/tree/master/custom_examples) section. Feel free to make your own and distribute it!

I'm also considering making a repository for commonly used ones.
