### ISSUE TITLE
Radial Menu Doesn't Work With Arrow Keys...

### ISSUE THREAD

**Issue by AmeliaLotus** [Friendly0Fire/GW2Radial#155]
When I set keybinds to arrow keys, it resets to "Num 2, Num 4, Num 6, Num 8" instead of arrow keys. The keybinds don't actually work, whether it's arrow keybound, or numpad keybound.

**Comment by AmeliaLotus** [comment]
Sorry, BIG ONE 2.0.0 ALPHA build

**Comment by Friendly0Fire** [comment]
As of the current alpha, this bug appears fully resolved.
