### ISSUE TITLE
Radial Menu not working after using discord overlay

### ISSUE THREAD

**Issue by SharpAxe27430** [Friendly0Fire/GW2Radial#156]
Radial Menu does not work after using discord overlay. Whenever I access my discord overlay with the hotkey "Shift - ` " and return back to my game, I can no longer use my designated hotkey "x" to bring up the radial menu. I can only solve this problem by completely exiting and reentering the game.

**To Reproduce**
1. Run game with gw2radial installed and functioning
2. Then use the discord overlay by using the default hotkey "Shift - ` "
3. Return to game and try to use gw2Radial again

**Expected behavior**

**Screenshots**

**System configuration (please fill in):**
 - OS: [e.g. Windows 10]
 - GPU: [e.g. GTX1080]
 - Chainloading, if any [e.g. arcdps -> GW2Radial -> GW2Hook]

**Additional context**

**Comment by Friendly0Fire** [comment]
Unfortunately since Discord's overlay is not open source, I cannot fix issues related to it.
