### ISSUE TITLE
Alpha - Custom Radial Crash

### ISSUE THREAD

**Issue by TanukiSoup** [Friendly0Fire/GW2Radial#157]
**Describe the bug**
Game crashes on startup when you try to load icons with custom a radial. Tested with the provided Attunements2 template. Everything was directly copied. The icon-less Attunements template worked perfectly fine.

**To Reproduce**
-create folder named custom in gw2radial
-create folder named General inside folder named custom
-copy config.ini from example and place in folder named General
-download each attunement png and place next to config.ini in General folder
-launch game, should crash

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: RX580
 - Not Chainloading

**Additional context**
I did notice the downloaded PNGs were blocked on my initial testing. Some sort of prompt from them originating from another PC or something like that. I unblocked them and tested again to no avail. I also tried changing all attunement images to JPG format and changing the config.ini to reflect this, and still crashed.

**Comment by Friendly0Fire** [comment]
The files should be in a *subfolder* within `custom`, e.g. the `Attunements2` example should be in `custom/Attunements2`. The folder name doesn't actually matter, as long as each radial menu is in its own folder within `custom`.

**Comment by TanukiSoup** [comment]
Sorry, they were in a subfolder named General. I just missed that when writing all that out.
