### ISSUE TITLE
Alpha - In-game UI Crash

### ISSUE THREAD

**Issue by TanukiSoup** [Friendly0Fire/GW2Radial#158]
**Describe the bug**
Click on the numerical value for the in combat expiration time and it crashes the game.

**To Reproduce**
-shift+alt+m to open in-game menu
-go to mounts tab
-find option for expiration time
-click the number (not the +/-)

**Expected behavior**
Expected to be able to edit the numerical value by typing the desired number.

**Screenshots**
attached

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: RX580
 - Not Chainloading
![bug screenshot](https://user-images.githubusercontent.com/64162736/89158289-7d45db80-d533-11ea-9822-fa286dfe20da.png)

**Comment by Friendly0Fire** [comment]
Can you send me your configuration settings? Should be in `Guild Wars 2\addons\gw2radial\config.ini`, wherever you installed the game.

**Comment by TanukiSoup** [comment]
I actually reset my config to test this and forgot to include that information. I originally found it with my default settings, but then deleted both ini files and was able to reproduce. Just to be sure though, they're attached below. (image format, sorry)
![Annotation 2020-08-03 131427](https://user-images.githubusercontent.com/64162736/89213861-60d58d80-d58b-11ea-9a76-8876c2b00f89.png)
![Annotation2 2020-08-03 131427](https://user-images.githubusercontent.com/64162736/89213868-6337e780-d58b-11ea-99aa-4fd0f3cd4221.png)

**Comment by Friendly0Fire** [comment]
Since I can't reproduce on my current dev build, mind testing if this works? 
[GW2Radial-v2.0.0-alpha-DEBUG.zip](https://github.com/Friendly0Fire/GW2Radial/files/5017718/GW2Radial-v2.0.0-alpha-DEBUG.zip)

**Comment by TanukiSoup** [comment]
Sure thing. Tried using that build and cant get the menu to even open.

**Comment by TanukiSoup** [comment]
I should also add that if I don't interact with the game while frozen gw2radial seems to infinitely create some sort of .dmp file till I close the game. 

(Also I don't mean to be bothersome. If you have dedicated testers for your alpha build I can leave it be, it's not hindering me at all. I was just testing new features and trying to break shit)

**Comment by Friendly0Fire** [comment]
Can you upload some of those .dmp files? They zip up pretty well, so you can send the first 10 or so that it generates.

And I'm glad you're reporting bugs, there's a reason why it's still an alpha build! Keep 'em coming.

**Comment by TanukiSoup** [comment]
Yeah, I'll give that a go. Let me know if you need anything else. I'm not code savvy, but more than willing to dig through files and get you anything that could help.

[idkwhatimdoing.zip](https://github.com/Friendly0Fire/GW2Radial/files/5020258/idkwhatimdoing.zip)

**Comment by Friendly0Fire** [comment]
You'll also have to attach `gw2radial.log`, it should be in the same directory as `Gw2-64.exe`.

**Comment by TanukiSoup** [comment]
Oh okay, that's what that error was a couple comments up. I'll just re-send both from a new crash though. Just to be clear this freeze is from the one you sent me to test.
[dmpstuff.zip](https://github.com/Friendly0Fire/GW2Radial/files/5023873/dmpstuff.zip)

**Comment by Friendly0Fire** [comment]
I haven't forgotten you, just been a bit busy.

I'm honestly pretty baffled by this. It'd probably be easier to track down the issue if you joined the [GW2 Development Community Discord server](https://discord.gg/XzR5eq), if that's at all possible.

In the meantime, I'm trying to setup a secondary PC to use for testing to see if I can replicate your issues. Could you provide your exact Windows 10 version? If you type "version" in the Start menu search, it should bring up System Information, the version number is the second item from the top. Also make sure your GPU drivers are up to date.

**Comment by TanukiSoup** [comment]
Version	10.0.18362 Build 18362

I have a second PC I will run the same tests on tonight with some different specs. GPU drivers are current as well.

**Comment by TanukiSoup** [comment]
> 
> 
> Version 10.0.18362 Build 18362
> 
> I have a second PC I will run the same tests on tonight with some different specs. GPU drivers are current as well.

**Comment by TanukiSoup** [comment]
I was able to recreate both issues on the other PC with completely different specs. I did not test the image loading from the other ticket on that PC, but can do so tomorrow.
