### ISSUE TITLE
Unable to install the 2.0 version with addon manager

### ISSUE THREAD

**Issue by soniquete0** [Friendly0Fire/GW2Radial#160]
The addon manager points to this repo forked by megai2 https://github.com/gw2-addon-loader/GW2Radial with the last version being 1.2.4al

What is the method to install the new 2.0 together with d912pxy?

**Comment by Friendly0Fire** [comment]
Version 2.0 is still alpha, hence you need to install it manually by replacing the DLLs yourself. Check the addon loader's documentation and the pre-release download.

**Comment by soniquete0** [comment]
That did not help me at all.
None of the documentations was foolproof enough for me to figure out how to make it work.

What helped however was this https://github.com/megai2/d912pxy/wiki/Using-with-other-addons-and-overlays

**Comment by Friendly0Fire** [comment]
The alpha is intentionally not "foolproof" because I don't want a bunch of people installing it and being incapable of submitting bug reports afterwards. You might prefer waiting for the final release.

**Comment by soniquete0** [comment]
Unwillingness to spend a bunch of time by digging through insufficient docs scattered across a number of repos doesn't equal incapability to submit a bug report.

If I find something, I'll let you know.
