### ISSUE TITLE
Menu doesnt work after alt tabbing

### ISSUE THREAD

**Issue by Fluxyy** [Friendly0Fire/GW2Radial#162]
The menu doesn't work anymore after I alt tab out of the game. I have to remap it to make it work again. I play full screen 1920x1080 and use the center version of the menu. I have it binded to X

I am chainloading, arcdps -> gw2radial

System configuration:
 - OS: Windows 10
 - GPU: Rtx 2070

**Comment by sicu** [comment]
Alt + Enter and then Alt + Enter again works for me when this happens
