### ISSUE TITLE
Crash on selecting 'character name' in the Conditions menu

### ISSUE THREAD

**Issue by QuitarHero** [Friendly0Fire/GW2Radial#165]
**Describe the bug**
When you press the "Character Name" box, the game crashes.

**To Reproduce**
1. Open the menu.
2. Go to any radial.
3. Check box to open the conditional menu subcategories.
4. Click "Character Name".
5. Crash.

**Expected behavior**
For it to not crash and show a list of character names that I can pick from.

**Dump & Log Files:**
[select character condition crash dmp.zip](https://github.com/Friendly0Fire/GW2Radial/files/5184053/select.character.condition.crash.dmp.zip)
[arcdps_lastcrash - select char condition crash.log](https://github.com/Friendly0Fire/GW2Radial/files/5184055/arcdps_lastcrash.-.select.char.condition.crash.log)

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: GTX 970
 - Using addon loader; my addons are ArcDPS, SCT, Boon Table, Mechanics Addon, bHud integration, Build Pad.

**Additional context**
None.

**Comment by Friendly0Fire** [comment]
Does the latest version still exhibit a similar issue?
