### ISSUE TITLE
Show in Center with multi key stroke does not work

### ISSUE THREAD

**Issue by Hirukaru** [Friendly0Fire/GW2Radial#173]
**Describe the bug**
When going in GW2Radial options menu to mounts, changing the show in centre to CTL + ALT + NUM 0 (or even CTL + NUM 0) the overlay shows up, but when then hovering over a mount it wont mount up. changing it to just NUM 0 (the show on center) the mounting does happen. 

**To Reproduce**
1. Do change the show in center to CTL + NUM0 or longer string
2. TThen try to use that combination to mount up 
3. No mounting will happen

**Expected behavior**
That the radial system would be able to handle longer strings and thus I would be able to moun tup

**Screenshots**
No screenshot at this time, can be provided.

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: 970M
 - Chainloading, Arcdps -> GW2Radial -

**Additional context**
Nothing to be found here

**Comment by Friendly0Fire** [comment]
Alpha or mainline release?

**Comment by Hirukaru** [comment]
Mainline

**Comment by Friendly0Fire** [comment]
I cannot replicate this as of now, so if this comes up in the upcoming release, please reopen.
