### ISSUE TITLE
Darker the game color

### ISSUE THREAD

**Issue by Snaccs** [Friendly0Fire/GW2Radial#174]
When ever i press X (radial menu button) it turns the game dark and when used it returns to normal, it almost seems like it comes with the addon but it doesnt and some times it flicker makes me nauseous 

Bugged

![image](https://user-images.githubusercontent.com/71942317/94347496-0f022e80-0035-11eb-8322-7ae29a34fdf8.png)

No bugged 
![image](https://user-images.githubusercontent.com/71942317/94347521-3953ec00-0035-11eb-96f6-1dbeac386880.png)

**Comment by Friendly0Fire** [comment]
* OS?
* GPU?
* Other addons?
* How are you loading it?
* Tried the alpha version?
* How often/consistent is it?

**Comment by Snaccs** [comment]
Windows 10
EVGA Geforce 1070
Dx912pxy
installed it through gw2 addon manager 
i havent try the alpha version since i got it with manager but i had it b4 addon manager it worked fine and even when i first installed it on addon manager it works wonders but after few weeks it starts to do that, some times it happens alot some times doesnt.

**Comment by Friendly0Fire** [comment]
Try without d912pxy, this is likely a conflict with it.

**Comment by Friendly0Fire** [comment]
Will be closing this in favor of #191. Please track the issue there.
