### ISSUE TITLE
Does Radial affect other keybinds?

### ISSUE THREAD

**Issue by YarrikV** [Friendly0Fire/GW2Radial#175]
This is more of a question than a bug report.

So, yesterday, I installed Gw2 add-on manager, and with that, radial. To be exact, I installed radial, arcdps(+boon table & buildpad) and dx9 to 12 thingy. Since then, I have noticed a bug (not necessarily caused by radial).

My problem:
Only in-game, the button M2 (mouse right click) is registered as M3 (middle mouse button). When i try to bind my right click to sth, it registers as M3. 

My question:
Could this be caused by Radial? I haven't had the time to uninstall radial properly and see if the problem is gone.

**Comment by Friendly0Fire** [comment]
Sorry for replying so late, but GW2Radial only affects whatever you assign to it, it doesn't otherwise intercept keybinds. You'd have to have set a menu on M2 with M3 as the action, or at least that's the only plausible scenario I can think of.

**Comment by YarrikV** [comment]
Ok this can be closed. Still don't know the cause, but it wasn't Radial. Thanks you.

**Comment by Friendly0Fire** [comment]
Good luck figuring it out!
