### ISSUE TITLE
WvW Mode

### ISSUE THREAD

**Issue by Durzan666** [Friendly0Fire/GW2Radial#180]
**Is your feature request related to a problem? Please describe.**
I binded the Radial menu to the key C. That works pretty fine in PvE but in WvW there is no menu. So I have to re-bind every time in WvW the hotkey for the Warclaw to C so I don't have to learn new keybindings. When I leave the WvW I have to remove the key binding.

**Describe the solution you'd like**
There seems to be a detection if the player is in WvW. So it would be great if the Warclaw is called by the addon instead of doing nothing (current behaviour).

**Comment by Friendly0Fire** [comment]
The upcoming 2.0 build will do just that.
