### ISSUE TITLE
With linux you cannot use NUM keys ¬¬

### ISSUE THREAD

**Issue by hk3wx** [Friendly0Fire/GW2Radial#181]
**Describe the bug**
If the NUM keys is used, it gives [error]
Num keys doesn't seem to be working with linux

**Expected behavior**
Since it's working with the game itself 
wonder why it doesn't work with gw2radial ;(

**System configuration** 
 - OS: [ ArchLinux ]
 - Chainloading, arcdps -> GW2Radial -> BoonTable

**Comment by Friendly0Fire** [comment]
Sorry, this addon does not officially support Linux. You're welcome to fork it and try to fix the issue, I'd accept merge requests for it.

**Comment by Friendly0Fire** [comment]
If someone can verify whether this is working now, I'd be appreciative.
