### ISSUE TITLE
Not working on drives that aren't C drive?

### ISSUE THREAD

**Issue by Cobacomey** [Friendly0Fire/GW2Radial#184]
I am on a Windows 10 pc, GW2 is installed on my D: drive.
I fallowed the steps and nothing happens when I press the Alt + Shift + M
I have deleted, reinstalled and restarted my pc. This was an issue before the latest update which happened today Nov17th 2020.

Please help, I really like the idea of the radial mount setup, 100x better then the garbage right click swap mounts...

Thank you
Cob,

**Comment by Friendly0Fire** [comment]
You'll need to detail the steps you followed in more details, because the addon works fine on other drives. What exactly made you suspect that as a cause specifically? Which version are you using? There was no update today...

**Comment by Cobacomey** [comment]
Sorry GW2 had an update today.
Well in the instructions it doesn't say anything about other drives so I thought maybe it didn't support it since it's not working, silly assumption maybe.

I also had a second 64bin, I placed it in both, then deleted one and that also didn't seem to do anything.

1. I downloaded the addon, the SkyScale one from chrome
2. started GW2, pressed the short cut 
3. nothing happened
4. deleted and tried it again, still nothing

**Comment by Friendly0Fire** [comment]
What file exactly did you place in bin64? What name was it in the zip file and what did you name it to in bin64? Do you have any other addon?

**Comment by Cobacomey** [comment]
This is the file path D:\Games\Guild Wars 2\bin64
I placed the d3d9.dll into the bin64, I have no other addons so I don't need to rename it.
I did have a map guide addon for my other pc for map completion but I don't think it was made by you guys and shouldn't effect this pc anyways.

**Comment by Cobacomey** [comment]
![image](https://user-images.githubusercontent.com/74627931/99459907-db3cda00-28fc-11eb-9f95-c80840dad49b.png)
