### ISSUE TITLE
Jackal/Rollerbeetle mix up/doesn't work

### ISSUE THREAD

**Issue by Kimmia** [Friendly0Fire/GW2Radial#185]
Hi,

I installed the radial mount choice and I do love it except I can't choose the jackal mount at all, I installed it as directed and did not mess with the order of the mounts but when I choose the Jackal option it mounts me on my Rollerbeetle and when I choose the Rollerbeetle (originally thinking they had been swapped) it instead does a weapon swap.

I only have this addon installed and I am currently working around this issue but I would like to see it fixed if possible.

Thanks!

**Comment by Friendly0Fire** [comment]
Redo your keybinds as per [here](https://github.com/Friendly0Fire/GW2Radial#usage).

**Comment by Kimmia** [comment]
Do I have to use those exact keybinds? For the novelties too?

**Comment by Friendly0Fire** [comment]
You have to have them match. Doesn't matter what they are as long as they match between the addon's settings and the game's.

**Comment by Kimmia** [comment]
I've just double checked and they match, all of my novelties are unbound on
both and my weapon weap is on the tilde
[image: image.png]

**Comment by Friendly0Fire** [comment]
You'll have to reply in Github, attachments don't work.

**Comment by Kimmia** [comment]
Sorry, image below

![image](https://user-images.githubusercontent.com/75013651/100448203-da006f80-30a9-11eb-9343-d8c31495fe89.png)

**Comment by Friendly0Fire** [comment]
Try the alpha version.
