### ISSUE TITLE
Discord Overlay

### ISSUE THREAD

**Issue by EmilianT** [Friendly0Fire/GW2Radial#186]
When trying to use discord overlay while in game after installing the mount addon, the game just crashes. Can that somehow get fixed? I've been using to use Discord Overlay while playing games a lot so that means that every half an hour or something the game crashes. Thanks for the addon and keep up the good work!

**Comment by Zaidya** [comment]
Just wanted to report this one, too. I can open the Discord Overlay, but if I then use it, the Game crashes. If I just take a look into the overlay and close it again, the Game doesn't crash but the gw2 radial overlay isn't working anymore.

**Comment by Friendly0Fire** [comment]
Discord overlay now appears to work fine with the Addon Loader, which is the preferred way to load GW2Radial now. You can set it up using the [Addon Manager](https://github.com/gw2-addon-loader/GW2-Addon-Manager), though you'll need to manually insert the new version while it's still in alpha.
