### ISSUE TITLE
Game can't run when Razer Cortex is running.

### ISSUE THREAD

**Issue by FallRegalia** [Friendly0Fire/GW2Radial#187]
Probably just be me being a dumb, idk.

When I launch the game with Cortex running and d3d9.dll in bin64, I get an error message and a crash. Remove the d3d9.dll, gw2 runs normally.
When I exit Cortex, the game works fine with d3d9.dll in the folder.

I have gone through and made sure Cortex wasn't optimizing anything and the game still has has the error and the crash. So I guess its something to do with the base Cortex program.

https://user-images.githubusercontent.com/63219843/102679049-936ad600-417a-11eb-8e1c-b5d99ddddb44.mp4

**Comment by KB0A** [comment]
This issue seems came back after a while.
Any solution?

**Comment by knoxfighter** [comment]
Uninstall Razer cortex, it does weird things with all programs named `d3d9.dll`, so this will always happen.

**Comment by Friendly0Fire** [comment]
This may work with the Addon Loader, which is the preferred way to load GW2Radial now. You can set it up using the [Addon Manager](https://github.com/gw2-addon-loader/GW2-Addon-Manager), though you'll need to manually insert the new version while it's still in alpha.

If it doesn't work with that either, I'm afraid there's nothing I can do.
