### ISSUE TITLE
Custom wheel doesn't show up in the options

### ISSUE THREAD

**Issue by kazerniel** [Friendly0Fire/GW2Radial#188]
**Describe the bug**
I followed [these instructions](https://github.com/Friendly0Fire/GW2Radial/tree/master/custom_examples):

> Everything happens in the addons/gw2radial/custom folder of your Guild Wars 2 installation directory.
> To create a new menu, first make a new folder. Its name does not matter. Inside, create a file named config.ini which must at minimum contain the following

But the custom wheel doesn't show up in the options menu.

Neither do the "Reload custom wheels on focus" and "Reload custom wheels" options show up in the Misc tab.

**System configuration (please fill in):**
 - OS: Win10
 - GPU: AMD Radeon RX 570
 - Chainloading with GW2 Addon Manager: d912pxy and Radial

**Additional context**
This is the content of my config.ini (basically I just want to change the icons) :
```
[General]
nickname = MountsCustom
display_name = Mounts
only_out_of_combat = true
only_above_water = true

[Raptor]
color = 
icon = Raptor_(overhead_icon).png

[Springer]
color = 
icon = Springer_(overhead_icon).png

[Skimmer]
color = 
icon = Skimmer_(overhead_icon).png

[Jackal]
color = 
icon = Jackal_(overhead_icon).png

[Griffon]
color = 
icon = Griffon_(overhead_icon).png

[Beetle]
color = 
icon = Roller_Beetle_(overhead_icon).png
```

**Comment by Friendly0Fire** [comment]
Three things:
* Display name will clash with existing mounts menu.
* Parentheses in icons might cause issues.
* Color shouldn't be there if it's going to be empty.

I don't know if any of these is the reason for it not working, but I'd start there. Also, try to import one of the demo radial menus to see if those work.

**Comment by kazerniel** [comment]
Fixed those three bullet points, but none of them made the custom wheel show up. I also downloaded the two sample packs but those don't show up either.

The "Reload custom wheels on focus" and "Reload custom wheels" options are also still missing.

**Comment by Friendly0Fire** [comment]
... Are you using the 2.0 alpha? Because those are 2.0 alpha features.

**Comment by kazerniel** [comment]
According to GW2 Add-on Manager I have v1.2.4al. I saw mentions that such functions exist on this page, so I thought it was a bug that they were missing:

https://github.com/Friendly0Fire/GW2Radial/tree/master/custom_examples

**Comment by Friendly0Fire** [comment]
The manager doesn't yet have the 2.0 build as I'm trying to solve a few issues before release.
