### ISSUE TITLE
Causes GW2 to crash upon second startup and menu is unreadable during the first

### ISSUE THREAD

**Issue by VaileCearo** [Friendly0Fire/GW2Radial#189]
**Description of issue**
After a clean install of the addon using the addon manager the addon works but has visual bugs such as all the text in the menus being represented only by boxes and squares instead of any actual letters. After closing the game and reopening it however the addon will cause GW2 to crash right as the character select screen loads and will continue to do so fo every startup of the game after until or unless the d3d9.dll file is deleted or the addon is completely uninstalled then reinstalled at which point the issue will persist again as soon as the game is closed out for the first time.

**To Reproduce**
1. Install the addon through the addon manager app.
2. Launch the game and open addon menu, there will be no text only different sized boxes where the text is supposed to be.
3. Close the GW2 client completely.
4. Open the GW2 client again and sign in, game will immediately crash upon loading the character select screen.

**Expected behavior**
To be able to read the addons menus and not have it crash the game client when logging back in.

**Screenshots**
![Gw2-64 2020-12-28 20-35-51](https://user-images.githubusercontent.com/35614805/103255272-4b07a100-494e-11eb-8055-b5c3df409a31.png)

**System configuration**
 - OS: Windows 10
 - GPU: GTX 970
 - Chainloading: None however addon was installed using the universal addon manager for GW2 and was also installed alongside d912pxy via the same manager.

**Additional context**
It appears the the issue with the addon's menu text showing only as shapes and squares is able to resolve itself after about 30 minutes of being in game however the crashes still seem to happen if I close the game and try to reopen it no matter how long I wait. To get by I'm currently uninstalling and reinstalling the addon before every startup of the game client in order to avoid the crash but it's super tedious and I end up needing to rebuild my radial mount settings every time I want to play.

**Comment by Friendly0Fire** [comment]
Please head on over to the [2.1.0 pre1](https://github.com/Friendly0Fire/GW2Radial/releases/tag/v2.1.0-pre1) release and let me know if the problem persists.

**Comment by Friendly0Fire** [comment]
Closing due to no reply.
