### ISSUE TITLE
AutoMount not working

### ISSUE THREAD

**Issue by KritusMennes** [Friendly0Fire/GW2Radial#190]
**Describe the bug**
Pressing the mount key while underwater does not automatically mount the skimmer (unless the skimmer is set as the default)

**To Reproduce**
1. Go underwater.
2. Ensure default mount is raptor.
3. Push mount key.
4. Keep swimming because skimmer didn't mount up.

**Expected behavior**
I expected to mount up on the skimmer while underwater (or Warclaw in WvW, which I haven't tested as I don't do much of that).

**Screenshots**
![image](https://user-images.githubusercontent.com/76783681/103363452-1cdaac00-4a89-11eb-96e9-9322c05b9fa6.png)

**System configuration (please fill in):**
Windows 10-64 bit
Loaded mod using GW2-UOAM, along with ArcDPS and the d912pxy addons.

**Additional context**
The skimmer mounts up underwater fine if I navigate the radial menu to the skimmer option, it's only the automount option that doesn't work. It's entirely possible I've got something configured wrong. Thanks for looking into it!

**Comment by Friendly0Fire** [comment]
You're not using the alpha. This is an alpha 2.0 feature. You'll have to manually install it for now, I can only push final releases into the addon loader.

**Comment by KritusMennes** [comment]
Brilliant, yes, it works flawlessly with the Alpha. Thank you.
