### ISSUE TITLE
when I select a mount the screen goes dark and changes color

### ISSUE THREAD

**Issue by ihavenodamage** [Friendly0Fire/GW2Radial#191]
https://youtu.be/b_NcG4SBHNc

I'm using a version v1.2.4 Skyscale Update and d912pxy support

And i use other addons too  , arc dps / d912pyx

Setup 
i7 8700k
1070 ti
16GB RAM

**Comment by Friendly0Fire** [comment]
Use the alpha, it has additional compatibility fixes with d912pxy.

**Comment by ihavenodamage** [comment]
and, i started using alpha version but it doesn't work for me in wvw and i can't use mount in water, fellsbad

**Comment by Friendly0Fire** [comment]
Only the Warclaw is available in WvW so it doesn't show the wheel, just immediately activates the Warclaw. Check your keybinds.

The same goes underwater but with the Skimmer. You can change an option in the settings if you don't have the underwater mastery.

**Comment by ihavenodamage** [comment]
Skimmer it works now, thank you so much
Buutt
I'm pressing the CTRL, which would be the my hotkey that will open the radial, however the warclaw does not want to open in wvw
pve it works, but not on wvw https://youtu.be/kluhqgoiFS0

**Comment by Friendly0Fire** [comment]
Can you try with a key that's not a modifier? Ctrl/Shift/Alt have a lot of special handling because they're combined with other keys.

**Comment by ihavenodamage** [comment]
it worked hahaha, sorry for the inconvenience

**Comment by Friendly0Fire** [comment]
No, thank you! This is definitely a bug to fix.

**Comment by Matsyir** [comment]
Hi, I'm also getting this issue - also while using d912pxy & arcdps. How can I use the most recent alpha update with GW2-UOAOM (addon manager)? I don't really see any way to select a version besides the global "update" button, which leaves it at v1.2.4al, while there seems to be more recent releases available on the repo.

For me this started happening when I turned my "Shaders" setting from high to low. In some areas, I can even get the world to consistently keep a whole tint of color after using the radial selection (like, everything looks blue, or red, or green). I can confirm that putting my shaders back to high fixes it, but I still run low shaders for fps.

Also, I imagine this is related, while I was on the medium "Shadows" setting it sometimes caused the shadows to flash in and out very quickly, rather than tinting everything (like, extreme seizure-warning-level flashing). This doesn't happen after switching to Low shadows. Note that this is **shadows** and above was **shaders**. Can also confirm that it continues doing it if I switch back to medium.

![image](https://user-images.githubusercontent.com/28902643/125323010-56c81d00-e30c-11eb-85d8-23334d776ad7.png)

Great addon btw. So much that I'm willing to deal with these tints to use it, lol. I understand that this is likely an interaction with d912pxy so probably a pain to fix.

i5 8400
1060 3gb
16gb ram

**Comment by sicu** [comment]
> Hi, I'm also getting this issue - also while using d912pxy & arcdps. How can I use the most recent alpha update with GW2-UOAOM (addon manager)? I don't really see any way to select a version besides the global "update" button, which leaves it at v1.2.4al, while there seems to be more recent releases available on the repo.
> 
>(...)

Addon Manager won't update to the latest one you see here on github as it is tagged as pre-release. If you want it before it's officially released just download the zip file and extract 'gw2addon_gw2radial.dll' into ...\Guild Wars 2\addons\gw2radial

**Comment by Matsyir** [comment]
> AddonManager won't update to the latest one you see here on github as it is tagged as pre-release. If you want it before it's officially released just download the zip file and extract 'gw2addon_gw2radial.dll' into ...\Guild Wars 2\addons\gw2radial

I appreciate the quick reply, but unfortunately I'm still getting both issues with 2.0.0-alpha. I replaced the file like you said (while GW2 was closed), then tried it, still had the issue, so I ran "update" on AddonManager and tried again, was still broken. I can't really see a way to confirm that I'm on 2.0, but the new .dll hasn't been replaced and the wheel does look a tiny bit different.

**Comment by sicu** [comment]
You're on the latest if you have "Custom Wheel Tools" available at the bottom of the Misc tab in the addon's menu [Shift+Alt+M]

As for your other issues, you'll have to wait for someone else to chime in as I'm just a regular end-user like yourself.

**Comment by Demeth** [comment]
I have the same issue :( Latest version as well, when i chose a favorite mount, screen goes dark

**Comment by Friendly0Fire** [comment]
To all having an issue, please head on over to the [2.1.0 pre1](https://github.com/Friendly0Fire/GW2Radial/releases/tag/v2.1.0-pre1) release and let me know if the problem persists.

**Comment by Matsyir** [comment]
Unfortunately, I still have the issue when using the 2.1.0 pre1 .dll you linked. The issue does seem to get resolved quicker/more consistently though, but maybe that's just a bit of "luck" in the time I tested it. Want me to test without d912pxy?

**Comment by Friendly0Fire** [comment]
Please do! I suspect it's a problem with d912pxy but I'd like to be certain.

**Comment by Matsyir** [comment]
I was having issues directly uninstalling/disabling addons with GW2UOAOM, so I ended up doing a "reset to clean install" which removes all addons, figured I may as well test more versions & addon combinations at that point:

- 1.2.4al by itself(no other addons) does not have the issue (this is the latest release on GW2UOAOM)
- 1.2.4al + d912pxy **does** have the issue
- 2.1.0pre1 by itself does not have the issue
- 2.1.0pre1 + d912pxy **does** have the issue

So it's basically as we would have expected. Fwiw I've never come across this visual bug until I got gw2radial, was playing with only d912pxy/arcdps for a while before I learned about it. So it's obviously related to d912pxy, but I'm not sure if it's directly a bug they introduced. Or maybe it is but surrounding certain rendering functions they don't actually use themselves. (I don't really know just speculating).

Also I am on Windows 10.

**Comment by Friendly0Fire** [comment]
Looping in @megai2 in case he's got any ideas. We looked into it in the past, but I unfortunately don't run into it so it's really hard to fix.

**Comment by Matsyir** [comment]
Feel free to let me know if you ever want to arrange some kind of screen-share or if you want logs or anything like that to help test/debug. I totally understand this is a weird interaction between the two mods so I can't blame you at all for not fixing this / not finding the cause sooner.

**Comment by Friendly0Fire** [comment]
I've made the decision that, between D3D9 and d912pxy both getting phased out soon, I will not be investing more time into this issue. As soon as the D3D11 version of Radial comes out, I strongly encourage everyone having this issue to migrate to D3D11!
