### ISSUE TITLE
When will GW2Radial be out of Alpha?

### ISSUE THREAD

**Issue by seanbarr1988** [Friendly0Fire/GW2Radial#192]
Hi, just wondering if GW2Radial is close to being released from alpha as the addon manage is still using the older version and won't update until gw2radial is marked as the latest release.

**Comment by Jayshua83** [comment]
I was hoping to find this out as well.

Did @Friendly0Fire go missing? Is this addon still in active development or is there a fork somewhere that is the updated one?

**Comment by BrentMifsud** [comment]
i just noticed that there was a commit by @Friendly0Fire a few days ago. Looks like its still being developed.

Would definitely like an update on this though. Especially with end of dragons coming very soon.

**Comment by Friendly0Fire** [comment]
Soon™.
