### ISSUE TITLE
Multiple Overlapping Radials

### ISSUE THREAD

**Issue by DarthMaul22** [Friendly0Fire/GW2Radial#193]
**Describe the bug**
Multiple radial menus are opened while using modifier keys. I have the default four menus bound to M3 with different combinations of the Shift and Alt keys. Holding Shift+Alt+M3 brings up all four menus at once, and GW2Radial will attempt to activate all menus on release. In version 1.2.4al, the previous menu would close and be replaced by the new menu as modifiers are pressed/released.

**To Reproduce**
1. Bind Mount radial to M3
2. Bind Novelties menu to Shift+M3
3. Press and hold Shift+M3
4. Both the Mounts and Novelties menus appear at once

**Expected behavior**
Mount menu should go away after pressing Shift.

**Screenshots**

Video showing menus while cycling through M3, Shift+M3, Shift+Alt+M3, Alt+M3, and back to M3.
https://youtu.be/ZvgvS8NoKGg

The same rotation in 1.2.4al showing expected behavior.
https://youtu.be/0P8i4lZ2EBs

**System configuration (please fill in):**
 - OS: Windows 10 x64
 - GPU: GTX 1070
 - Chainloading: ArcDPS, d912pxy (through GW2 Addon Manager - GW2Radial updated in-place manually)

**Additional context**
I tried searching for an option or setting in GW2Radial's menu regarding this, but found none. Conditional activation is disabled for all menus. I did have to re-bind the menus after upgrading, but swapping to 1.2.4 and back did not result in me having to re-bind again.

**Comment by ThermoMan** [comment]
I can get double rings in another way.  I'm on the beta version.
Same key bindings.

Run GW2 full screen.
Use /wiki to look something up (for GW into background and other window on top)
Alt+tab back to GW. 

Press M3.  Presto, two windows.

Pressing Alt by itself seems to clear it up???!?!!?

**Comment by Friendly0Fire** [comment]
The next release (an alpha for which should be up Soon™) has massively changed input handling in part to address this issue, so the new behavior should be much closer to the old one (new input will override old inputs, causing the previous menu to close and the new one to pop up).

I'll close this for now, feel free to reopen when the alpha is available if this is still a problem.
