### ISSUE TITLE
intercepted unhandled exception

### ISSUE THREAD

**Issue by albertmueladote** [Friendly0Fire/GW2Radial#195]
**Describe the bug**
When i start the game with addon, crash and show error (check image)
I called d3d9_chainload.dll

**To Reproduce**
Donwoload last release from plugin
Put d3d9_chainload.dll in bin64
Start the game.

**Expected behavior**
It should works.

**Screenshots**
![image](https://user-images.githubusercontent.com/22682314/115093265-0bbf8900-9f1a-11eb-8aec-2a466ff7db5e.png)

**System configuration (please fill in):**
 - OS: Windows10
 - GPU: GTX 1080 TI
 - arcdps > gw2radialmount

**Additional context**

**Comment by Friendly0Fire** [comment]
Not enough details to be actionable, and the code has changed a lot since then. When the next alpha releases, please try again.
