### ISSUE TITLE
Modifier keybind keypresses fall through to game input

### ISSUE THREAD

**Issue by Ririshi** [Friendly0Fire/GW2Radial#199]
**Describe the bug**
Modifier keybind keypresses "fall through" to the game. For example, I use G for interact, and shift + G to open the novelty radial. For example, pressing shift + G while at a vendor, will also open the vendor window.

**To Reproduce**
1. Bind interaction key to any letter
2. Bind opening a radial to the same letter with a modifier
3. Use the radial keybind while next to an interactable object or NPC.

**Expected behavior**
I expect to only be opening the radial menu, rather than also activating my interaction keybind.

**Screenshots**
Here's the video of the bug in action.
![video of bug](https://i.imgur.com/D3jhshl.gif)

And a screenshot of my keybinds.
![image](https://user-images.githubusercontent.com/8461226/121730198-a5a54b80-caef-11eb-94a4-66dcf9177084.png)

**System configuration:**
 - OS: Windows 10
 - GPU: RTX 2070 Super
 - Chainloading: Literally everything in the GW2AddonManager. Also using BlishHUD and TacO.
 - GW2Radial version: 2.0.0 alpha

**Comment by trowieuk** [comment]
That's an ArenaNet issue, you'll need to choose different binds.

**Comment by Ririshi** [comment]
I brought it up on Discord and friendly fire himself said I should make an issue for it. If there's nothing to be done about it, I guess he wouldn't have asked me to do so.

**Comment by Friendly0Fire** [comment]
Indeed, I'm pretty sure I can improve this behavior at least to a certain extent.

**Comment by glassbloom** [comment]
Same problem here. I use numpad for my mounts, and alt-numpad for squad markers. If I try to place a squad marker through radial, though, I just hop on my mount instead.

**Comment by Jademalo** [comment]
Similar problem here, have my mounts bound to Ctrl+Shift+F1 etc, and while I'm able to use that keybind with my keyboard, using the radial menu instead just does my pet's F1 attack.

**Comment by Friendly0Fire** [comment]
I will leave this issue open to track problems with modifiers, but the behavior of the upcoming version should be substantially better. I'm hoping to have an alpha for this out soon.

**Comment by Friendly0Fire** [comment]
To all having an issue, please head on over to the [2.1.0 pre1](https://github.com/Friendly0Fire/GW2Radial/releases/tag/v2.1.0-pre1) release and let me know if the problem persists.
