### ISSUE TITLE
Raptor and Beetle Mount

### ISSUE THREAD

**Issue by Jarr0ws** [Friendly0Fire/GW2Radial#201]
Hey There,
i whatched a mukluk video and rly love this Addon. I edited my key bindings and controlled it a lot times. ( addon and options get same bindings )
If i wanne use Raptor or Beetle, allways the friend menu opens ! only on this two mounts.

I also use the Addon Manager and Arc DPS ( there i use the update button )

would be nice if you can help me

greeting from germany

**Comment by Friendly0Fire** [comment]
This is likely a problem with modifier keys or incorrect bindings. The new version which should release soon overhauls this, so I will close this for now but feel free to report back if the issue persists with the new update.
