### ISSUE TITLE
Apologies - More of a Question

### ISSUE THREAD

**Issue by praetoras** [Friendly0Fire/GW2Radial#202]
**First-Off, allow me to apologize. I wasn't sure how else to reach someone directly with experience in coding Gw2 Addons. Reddit felt like a little too much of a random chance of actually getting someone.**

I'm actually considering attempting an addon myself, but I'm not sure how feasible it is. I was considering studying this addon, but I'm relatively new to C++ without much experience.

Essentially, the addon would do a very simple, non-combat thing: It would store dye sets for Outfits, Gliders, and Mounts, so if you change to a specific outfit, glider, or mount, it would automatically load the dyes you'd last used with that item.

Is this something that would be possible in the game, or would it be a fool's errand to attempt?

**Comment by Friendly0Fire** [comment]
That's well outside the bounds of this addon or what you can do with simple addons. You'd have to get into reverse engineering, which is a pretty complex topic.

You should ask this kind of thing on the [GW2 Addon Devs Discord server](https://discord.gg/zqeHCEg).
