### ISSUE TITLE
Radial + DXVK win10

### ISSUE THREAD

**Issue by narf203** [Friendly0Fire/GW2Radial#203]
**Describe the bug**
I can't get Radial to work with dxvk on windows 10.
What I do to make it work is giving me a error when I close the game.

**To Reproduce**
1) d3d9.dll 			        -Radial dll
2) d912pxy.dll 		        	-DXVK dll   
(This is the only way I found to get Radial to work with dxvk on my system)
3) ingame no problems and smooth (after cash is created)
4) on exit it gives me a error (probably because i renamed the dxvk dll to d912pxy.dll)

**Expected behavior**
Is there something I'm missing to get Radial working with dxvk?

**Screenshots**

**System configuration (please fill in):**
 - OS:  Windows 10
 - GPU: RTX 2070
 - Chainloading, if any  GW2Radial -> dxvk (d912pxy.dll ) -> Reshade vulkan

**Comment by Friendly0Fire** [comment]
Sorry, I won't be supporting DXVK, it'd be too much work to test all possible variations and workarounds for all proxy DLLs.

**Comment by megai2** [comment]
you can use https://github.com/megai2/SelectRenderer to use DXVK, that can be installed with gw2radial via https://github.com/Draeggiar/GW2-Addon-Manager

**Comment by narf203** [comment]
Ok thanks I got It working now :)
works perfect
