### ISSUE TITLE
Build Templates Menu

### ISSUE THREAD

**Issue by SkilledAlpaca** [Friendly0Fire/GW2Radial#205]
**Is your feature request related to a problem? Please describe.**
A menu for choosing build templates

**Describe the solution you'd like**
Another keybind possibly for selecting different build templates.

**Describe alternatives you've considered**
N/A

**Additional context**
There are currently keybinds in game to swap to different templates. You could set a limiter for the amount of slots you have.

**Comment by Friendly0Fire** [comment]
I will leave this (and other such menus) up to the custom menus feature currently in alpha. It would be too complicated to properly support build templates in a generic fashion, whereas with custom menus each player can setup custom menus per character and tailor the experience.
