### ISSUE TITLE
Graphical Issues When Using This Addon

### ISSUE THREAD

**Issue by TheCoderJT** [Friendly0Fire/GW2Radial#206]
I'm have graphical issue when using your addon it only happens when opening the menu using x....have uploaded a video to google drive you can watch it no need to download. The video still may be processing if so just wait and then you can view it without downloading anything. 

I have dx12proxy and arc dps scrolling text addons installed too, maybe its one of these conflicting? 

https://drive.google.com/file/d/1ikXO4NnAQT4Fk4ydXi-aeS-3oFYoDc2o/view?usp=sharing

**Comment by Friendly0Fire** [comment]
Tracking this in #191.

**Comment by TheCoderJT** [comment]
Seem like you still haven't fixed the issue 7 months later

**Comment by Friendly0Fire** [comment]
... The new version isn't even publicly available yet.
