### ISSUE TITLE
Multiboxing with WvW and PvE instances only allows Warclaw mounting

### ISSUE THREAD

**Issue by writzx** [Friendly0Fire/GW2Radial#208]
**Describe the bug**
Multiboxing with GW2Radial keeps flashing the "mount queued" icon. If I am in WvW in one account and PvE in another account, I can only mount Warclaw even with Warclaw turned off (not sure what decides it though, like maybe the order of launching?)

**To Reproduce**
1. Run two instances of the game with the add-on applied.
2. Go to WvW map in one instance.
3. Go to PvE map in the other instance.
4. Try mounting in the PvE instance

**Expected behavior**
PvE instance mounts PvE mounts because Warclaw is turned off.

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: RTX3080
 - Chainloading: arcdps -> GW2Radial -> GW2Hook (also some arcdps plugins)

**Additional context**
There is also a weird issue where unmounting doesn't work in my second account using the usual key. I do not have all mounts in that account. Could be totally off-topic but still just wanted to mention it.

**Comment by dlamkins** [comment]
What are you using for multiboxing?  It is likely that all of your instances are sharing the same mumble link name and that you'll need to specify unique ones for each.  

That being said, it appears Gw2Radial may have the mumble name hardcoded.  🤔

https://github.com/Friendly0Fire/GW2Radial/blob/26266e49548512fd9f534972018ece7ccbd96497/GW2Radial/src/MumbleLink.cpp#L55

**Comment by Friendly0Fire** [comment]
That is correct, the current version of Radial does not support multiboxing at all. I'll see if I can add options.

**Comment by ThermoMan** [comment]
You may not want to explicitly enable support for multi-boxing.
https://help.guildwars2.com/hc/en-us/articles/360013658134-Policy-Dual-or-Multi-Boxing

The stated intent of the multi-boxing policy really looks like they want a human at two or more keyboards and not any automation linking

Also in the final note they state that you may **not** multi-box in a competitive arena - which is the specific scenario this player was asking about.

So while it's not _you_ breaking the rules, I don't want to see Arena-Net revoke their approval of your add-on because of the actions of a few players.

**Comment by Friendly0Fire** [comment]
This is irrelevant to the addon. The changes are necessary to support renamed MumbleLink file mapping anyway, and that was implemented *by ArenaNet*. I will be implementing these changes, I just didn't get around to it, and I see no situation in which this change would cause problems.

**Comment by writzx** [comment]
> What are you using for multiboxing? It is likely that all of your instances are sharing the same mumble link name and that you'll need to specify unique ones for each.

The use case was simply playing in two regions and I stumbled upon it when starting another instance when the other account was in WvW. I am not familiar with the mumble link system so I probably wouldn't understand that immediately.

> Also in the final note they state that you may **not** multi-box in a competitive arena - which is the specific scenario this player was asking about.

Thanks for that link. I did not know about this rule. It is not normal for me to use multiboxing in WvW but accidentally I left one of the two accounts in WvW while trying to play PvE in the other, which is what let me find the issue.


Also, any ideas why the unmounting is bugged? Should I report a bug for it or is it trivial and/or intended?

**Comment by Friendly0Fire** [comment]
> Also, any ideas why the unmounting is bugged? Should I report a bug for it or is it trivial and/or intended?

Radial assumes a working MumbleLink, but also hardcodes the name it expects, so it breaks when more than one game instance is running at once because they're overwriting each other's states.

**Comment by Friendly0Fire** [comment]
MumbleLink is now automatically determined from the command line, so multiboxing should work in the upcoming release.
