### ISSUE TITLE
Multiple radial menus can now share keybinds.

### ISSUE THREAD

**Issue by andrei9669** [Friendly0Fire/GW2Radial#209]
Just read the v2.1.0-pre1 patch notes and I dunno man. This feels like it goes against GW2 TOS.
And if we add the fact that you can create custom radials. Maybe you should rethink this or at least ask Anet for confirmation that it's okay.

Also, one more thing. the anet approved link you linked in README, the account is now deleted so my guess is it's an ex developer? dunno how much weight it has now.

**Comment by ThermoMan** [comment]
I'm not as worried as you are, this is just making that keystroke context-sensitive.  As long as one keystroke does one thing at a time and doesn't queue up a series of actions I think we're OK.

**Comment by andrei9669** [comment]
hmh, if you say so. maybe I understood it differently.

**Comment by Friendly0Fire** [comment]
To clarify: two actions mapped to the same keybind will not work if they attempt to trigger simultaneously. The addon is designed to only trigger one action per key press, so it'll just pick one of them (with nondeterministic ordering, so which would be picked is largely unpredictable).

The primary reason to allow this in the first place is, as @ThermoMan said, to support the same key combination being used for different actions based on various conditions.
