### ISSUE TITLE
Nothing happened?

### ISSUE THREAD

**Issue by ThiagoScala** [Friendly0Fire/GW2Radial#211]
Sorry iam probably been dumb but i just installed the new radial addon and is exactly the same one as i had. I do not see the new features and  even the mount skin ui is the same. What happened?

obs: I deleted the older one on the addon folder on gw2 if anyone is wondering.

**Comment by Friendly0Fire** [comment]
You'll have to detail how you installed and what you have running.

**Comment by ThiagoScala** [comment]
> You'll have to detail how you installed and what you have running.

I installed via addon manager, and i was running a previous version of this same radial.

**Comment by Friendly0Fire** [comment]
The addon manager does not currently have the pre-release available, you need to manually install it. Should just be a matter of copying the DLL over the old one.
