### ISSUE TITLE
Inconsistent activation

### ISSUE THREAD

**Issue by Jademalo** [Friendly0Fire/GW2Radial#212]
After pressing the keybind, often I will simply not mount or somehow mount the wrong mount.

With regards to configuration, I have it set so that there's a 200ms pop-up delay, with centre behaviour set to previous. 
This means that if I want to mount on my previous mount, it's a simple case of tapping the button. If I want to select a mount, I press and hold for just a bit longer. This makes mounting super smooth.
My binds are set up to be `SHIFT+ALT+F1-8`, with the activation key being F13 bound to a button on my mouse with Logitech Gaming Software to prevent conflicts. 

With this however, I am having multiple strange inconsistencies with actually mounting.

- Occasionally, I will mount the wrong mount. 
Every so often, I will just not mount back on the same mount I was on after pressing a quick tap. For some reason it seems to like switching to the Warclaw or the Skimmer.

- A queued mount in combat will often not activate
If I'm in combat and I queue a mount command, it will appear as the circle in the bottom right. However, a substantial portion of the time the mount command will simply be eaten when I leave combat. The circle will disappear, and I'll not mount. 

These issues are intermittent, but frequent enough that they're pretty annoying. 
Thanks!

**Comment by Friendly0Fire** [comment]
First, please specify which build you're using when making an issue.

Next, some details:
* Are you sure you're not in restricted areas? The Warclaw will be automatically mounted in WvW and the Skimmer when on/under water because they're the only valid options in those respective scenarios.
* Queuing will never be perfect because there's a ton of things that can block mounting which the game does not report, and sometimes even when everything should be fine, it still doesn't work. I'm afraid that's just the way it is.

**Comment by Friendly0Fire** [comment]
Next prerelease will also have a customizable delay before a queued input is sent which should help with consistency, and you can increase that delay to make it more consistent at the cost of being a little slower.

**Comment by Jademalo** [comment]
> First, please specify which build you're using when making an issue.

Apologies, thought I had. Rewrote the post at one point, accidentally deleted that.
Using v2.1.0-pre1, through addon loader. Also have dx12pxy and arc loaded.

>     * Are you sure you're not in restricted areas? The Warclaw will be automatically mounted in WvW and the Skimmer when on/under water because they're the only valid options in those respective scenarios.

Absolutely yes, this seems to frequently happen just before the tarir meta at the north gate. There's the event to kill 9 waves of mordrem, and between the waves I try to mount on my raptor. At least once or twice it seems to mount me on the wrong mount. It happens elsewhere too, it's just inconsistent. Warclaw and skimmer seem to be the two it mounts me on in error more than others, however.

My only theory is that it has something to do with mouse movements or mouse position selecting a mount on the radial before the menu appears, but whenever I test it and try to reproduce it everything works as it should (automatically pressing the middle function until the button has been held long enough to bring up the radial menu)

>     * Queuing will never be perfect because there's a ton of things that can block mounting which the game does not report, and sometimes even when everything should be fine, it still doesn't work. I'm afraid that's just the way it is.
>
> Next prerelease will also have a customizable delay before a queued input is sent which should help with consistency, and you can increase that delay to make it more consistent at the cost of being a little slower.

I assumed that might be the case, but thought I'd just check in case only I was experiencing it and it was something to do with my config. I was going to suggest a customisable predelay, so good to know that's coming, thanks!

**Comment by Friendly0Fire** [comment]
> My only theory is that it has something to do with mouse movements or mouse position selecting a mount on the radial before the menu appears

This is likely the case. Maybe try playing with the scale and center scale sliders? Having a larger central region should make it less sensitive to accidental mouse movements. Otherwise, I'm not sure what could be wrong.

**Comment by Jademalo** [comment]
Apologies for the bad timing having just closed it, but I was playing earlier and noticed something which I think might be the cause of the first issue where the wrong mount is selected.

My setup has the radial appear at the centre of the screen, with the mouse snapping to the centre and returning to it's original place once released. 

I think one cause is that sometimes the mouse won't snap to the centre, and will instead stay in it's original position. 
This happened to me earlier as I went to select a specific mount so was extremely noticeable, and would offer a seemingly perfect explanation for that first issue.
Since most of the time my mouse is top left-ish as that's where I have my bag window, this also explains why it almost always mounts the warclaw, as that is pretty much exactly in the right spot for where my bag is. It also explains why the skimmer is the other common wrong mount, as if I was clicking a waypoint on the minimap and then right clicking just above for camera control which I do frequently, the skimmer would be mounted.

In addition to this, I think what could also be happening is there's maybe a frame or two where the wheel is active and looking at the mouse position to choose the mount, but the mouse hasn't yet moved to the centre. So if the hotkey is released during that split second then it will mount whichever mount is in that quadrant instead of selecting the centre area. This is just a theory that's much harder to prove due to the frame perfect nature of it, but could also offer an explanation for those times when the wheel doesn't appear visually like in the above case but the wrong mount was mounted.

I'm going to try having the wheel snap to the mouse position for a few days, to see if that solves the issue. If it does, then I'm fairly confident in this being the root cause.

I have no idea how to reproduce or what could be causing the first, it's only happened to me ~3 times over the last week and it only dawned on me it might be the issue earlier today. 
The second seems easier to solve though. I'd assume the easiest way to fix it would be to delay the wheel reading the mouse position for a couple of frames until the mouse has definitely snapped to the centre.

Thanks!

**Comment by Friendly0Fire** [comment]
This has been resolved in the latest release!
