### ISSUE TITLE
New contextual Wheel

### ISSUE THREAD

**Issue by SthepKnyght** [Friendly0Fire/GW2Radial#215]
Greetings.
With the advent of the equipment and build templates within GW2, as an official feature, me and others have been using hotkeys to switch between them. The feature I'd like added to the radial wheels is an extra wheel or two, with labeled numbers, for build and equipment quickswapping. Simple numbering would work the best for those, I would assume. Thank you for considering my suggestion. GL HF !

**Comment by Friendly0Fire** [comment]
You can do all of this with custom wheels, and even have wheels per character with named builds if you so desire.
