### ISSUE TITLE
Not loading after updating GW2 Addon Loader for DX11

### ISSUE THREAD

**Issue by tkrause** [Friendly0Fire/GW2Radial#216]
**Describe the bug**
The addon does not load and produces this in the log

```
[INFO] core | Loading gw2radial
[WARN] core | Addon "gw2radial" is not loaded due to wrong dependency version "loader_core". Require v0.1(r1) but have v1.0(r27)
[ERR] core | addons/gw2radial/gw2addon_gw2radial.dll dependency outdated
```

**To Reproduce**
1. Install gw2 addon manager 1.4
2. Install gw2 radial

**Comment by Friendly0Fire** [comment]
The new addon loader is broken right now and addons need to be updated for it. I recommend downgrading until the issues are resolved.

**Comment by tkrause** [comment]
Problem is I use arcdps all the time which now requires 1.0 and can't be downgraded because the update changed a ton of things that breaks the previous version.

**Comment by Friendly0Fire** [comment]
Then I'm afraid you'll have to go back to chainloading until the issues have been resolved. I'm just as stuck as you are and trying to fix things as soon as possible.

**Comment by Cion318** [comment]
Is chainloading possible with dx11? If yes how do you do that?

**Comment by Friendly0Fire** [comment]
Yes, arcdps supports chainloading, just rename whatever else you want to load as `d3d11_chainload.dll`. Bear in mind GW2Radial does not support DX11 currently.
