### ISSUE TITLE
Shortcut doesn't work after reinstalling GW2 Addon Manager

### ISSUE THREAD

**Issue by Oliviervdv1990** [Friendly0Fire/GW2Radial#218]
The default shortcut doesn't work for me (shift+alt+m).
It used to work perfectly and so did the plugin but ever since GW2 DX11 rolled out, I had to remove my Plugin Manager and uninstall all addons.

Now when updates have been done, I want to use it again. For some reason it doesn't work but the DX12proxy plugin does so not sure what the issue could be. 

Any pointers on how to make it work again? Addon has been installed in Addon folder where GW2 is.

**Comment by Friendly0Fire** [comment]
Please provide the information the bug report template indicates, namely which version of the addon you're using, how you've installed it (and versions for any dependencies).

**Comment by Oliviervdv1990** [comment]
> Please provide the information the bug report template indicates, namely which version of the addon you're using, how you've installed it (and versions for any dependencies).

No idea which version it is, installed it via Unofficial Addon Manager (v1.4) and updated there to latest version they offered.
Any clue how I can find the version when installing through addon manager?

FYI: I got issues with Addon Manager too, can't open it (403 remote server forbidden) so I assume I opened it too many times while trying to troubleshoot or something...

**Comment by Friendly0Fire** [comment]
GW2Radial is still in pre-release, you will need to download the latest version manually.

**Comment by Oliviervdv1990** [comment]
Hey,

I have checked for you and I got GW2Radial 1.2.4al installed
Got the d3d9.dll in my bin64 directory as well but shortcut key combination is not calling it in game.

So I was wondering if I have changed the key combination to call the interface ingame? Anyway I can trace it back in of the files of GW2Radial? Maybe that's the issue? 

It worked perfectly well until GW2 dropped the DX11 beta and had to remove every single add on to make the game work again. So now after 1 week I want to install it again but so far GW2Radial is the only one I cannot call ingame

**Comment by Friendly0Fire** [comment]
GW2Radial is still in pre-release, you will need to [download the latest version](https://github.com/Friendly0Fire/GW2Radial/releases/tag/v2.1.0-pre2) manually.

**Comment by Oliviervdv1990** [comment]
Thanks for coming back to me but Im confused. You say I need to download the newest version manually but on that same page it also states and I quote: 
_Addon loader support. It is recommended to use the GW2 Addon Manager to handle this easily. This is now the recommended method to install GW2Radial._
Thats exactly what I did and said.

Anyway I downloaded the latest version and copied it over to the addons folder and my game simply won't run anymore..

**Comment by Oliviervdv1990** [comment]
To add: the readme also states installation via GW2 Add On Manager.

It says to copy over the .dll file to bin64 but that file is not in .zip folder  you provided the download for so perhaps this might be the issue? I still have a d3d9.dll file in there but perhaps its from previous version?

**Comment by Oliviervdv1990** [comment]
Ye despite removing GW2radial, my game doesnt run anymore completely. The client refuses to run after clicking Start Game..
Help is needed

**Comment by Thex-PiedDroit** [comment]
@Oliviervdv1990 If you're still having issues launching the game, i would suggest repairing your client (https://help.guildwars2.com/hc/en-us/articles/201863008-Repairing-the-Game-Client)

I am having the same issue. I have tried installing it manually, by placing the dll (renamed to d3d9.dll) into bin64, but this way as through the manager, there is no evidence that the addon is loaded at all.
I have tried by completely uninstalling all addons and only installing that one through the new manager (1.4.2), and tried manually. Neither work.

**Comment by Friendly0Fire** [comment]
Please double/triple check that you are not running the DX11 beta.

**Comment by Thex-PiedDroit** [comment]
Attempted one last time, making sure to go into the game, disabling DX11, exiting, rerunning to make sure it was in DX9, quit again, removed all addons, reinstalled through manager, and it now works!
Thank you!

**Comment by Oliviervdv1990** [comment]
> @Oliviervdv1990 If you're still having issues launching the game, i would suggest repairing your client (https://help.guildwars2.com/hc/en-us/articles/201863008-Repairing-the-Game-Client)
> 
> I am having the same issue. I have tried installing it manually, by placing the dll (renamed to d3d9.dll) into bin64, but this way as through the manager, there is no evidence that the addon is loaded at all. I have tried by completely uninstalling all addons and only installing that one through the new manager (1.4.2), and tried manually. Neither work.

I fixed my client by removing all plugins and Add On Manager.
I reinstalled everything but GW2 radial only one not working. Not sure if its because keyboard shortcut doesn’t work or the add on.  Oh well.
