### ISSUE TITLE
UI hotkey Loss

### ISSUE THREAD

**Issue by WyvrnRipsnarl** [Friendly0Fire/GW2Radial#219]
Is there a way to find which hotkey is used to open the settings pannels if you have forgotten which key you set it up as (not default)?

**Comment by sicu** [comment]
Radial settings hotkey is: Alt+Shift+M
I don't believe you can customize that, so if it doesn't work then Radial did not load for some reason. Check `gw2al_log.txt` in the root folder of your GW2 installation to see if it was loaded or not

**Comment by WyvrnRipsnarl** [comment]
I know it was loaded because I had access to the Radial UI, however all my Keybinds are messed up with this new update and I cannot open the Settings Pannels to swap them around. Alt + Shift + M is not working.

**Comment by Friendly0Fire** [comment]
The keybinds need to be redone due to backend changes. What keyboard layout are you using?

**Comment by WyvrnRipsnarl** [comment]
QWERTY Keyboard
English Multi Canadian Standard

**Comment by Friendly0Fire** [comment]
That should be the standard QWERTY layout for those keys so I really don't see why Alt+Shift+M wouldn't be working. Have you tried temporarily removing/renaming the addon config? It's `config.ini` in the `addons` folder.

**Comment by WyvrnRipsnarl** [comment]
My Config.ini looks to have been modified to have keys signatures instead of tell me which exact keys is associated with which one.
Like The Mount Radial keybind is: [4, 160]
And there is seemingly not entry for the "Settings UI"

**Comment by WyvrnRipsnarl** [comment]
Okay so I figured where the problem lies. 
The Shift + ALT + M was being interfered by Keybinds that used [SHIFT] / [ALT] or [M].

I solved the issue by unbinding all the Keybinds that uses [SHIFT] / [ALT] or [M] (in the Game's Setttings, but I feel I shouldn't have to go down this length to fix that sort of problem.

**Comment by WyvrnRipsnarl** [comment]
I'm going to leave this issue open, in case you want to work on this issue. If you don't want to work on it, feel free to close it.
