### ISSUE TITLE
menu does not remeber keybind unbinding

### ISSUE THREAD

**Issue by herpderplerp** [Friendly0Fire/GW2Radial#220]
**EDIT**
Seemingly fixed it by doing another uninstall of mods and reinstall. And making sure I did not add in on mouse cursor this time, I assume by the post below me that this is a bug.

**Describe the bug**
I bound by a mistake the show on mouse and even if I select unbind it shows it as unbound but on restart of game its bound again. 

This leads to having both show on mouse and show in center active, seemingly show on mouse taking priority, but it leaves the radial open and I cannot select a mount neither does the menu go away.
 
This is on the latest release, installed and uninstalled via the unofficial gw2 addons manager. Also updated gw2 addons manager. 
Do not see a d3d9_chainload.dll with this latest release, tried to find d3d9.dll on here but saw the newest release only had one named something different.

**Comment by Canyonbydesign** [comment]
I am having a similar Issue. 
When I attempt to Clear the "Show on Mouse" Keybind, it appears to clear but the next time I press that keybind it attempts to open the menu and then becomes completely unresponsive (cant open options menu or use any other menus until I restart the client). On Restart, the hot key is bound again.

**Comment by sicu** [comment]
Issue is being tracked here: [#229](https://github.com/Friendly0Fire/GW2Radial/issues/229)

**Comment by Friendly0Fire** [comment]
As mentioned by @sicu this is tracked in #229, closing.
