### ISSUE TITLE
Warclaw only auto-mounts in WvW when not running?

### ISSUE THREAD

**Issue by SOL4RIS** [Friendly0Fire/GW2Radial#223]
Hi there, I am testing out the new build (lovely work by the way!), but when i try to use the SmartWar feature, it seems to only work if my character is standing still.  If I'm running and use the key-bind, my character will just stop running, then I have to press the key-bind again to mount the Warclaw.  Not sure if this is intended, but it's very different from how mounting up typically works outside of WvW.

If it's relevant, I do have Warclaw disabled in the radial menu.

**Comment by Friendly0Fire** [comment]
What are your keybinds set to? I could see this being a conflict with modifier keys.

**Comment by SOL4RIS** [comment]
Key-binds are all set to "Alt+X" where "X" is just a letter that corresponds to each mount.  Warclaw for example is Alt+W.

**Comment by Friendly0Fire** [comment]
This might require some hand contorting, but if you hold whatever key you use to run and then attempt to press Alt+W, my bet is that this will cause your character to stop walking because the Alt key was pressed. I'll try to dig into it on my end, but in the mean time you might want to test using keybinds that don't use modifiers just to see if it fixes it.

**Comment by SOL4RIS** [comment]
Oh... that makes sense, since I would be using W to run.  I tried setting the key-bind to something else (Num 1) and it works fine.  So, now that I have all my mounts on the numpad, here's hoping I don't run out of keys when the expac comes out.  Already trying to figure out where turtle and skiff are going to go... lol.

Thanks!

**Comment by Friendly0Fire** [comment]
I'll leave this up as a reminder to myself to see if I can handle this better, but I'm glad you got it working :)

**Comment by BrentMifsud** [comment]
> Oh... that makes sense, since I would be using W to run.  I tried setting the key-bind to something else (Num 1) and it works fine.  So, now that I have all my mounts on the numpad, here's hoping I don't run out of keys when the expac comes out.  Already trying to figure out where turtle and skiff are going to go... lol.
> 
> 
> 
> Thanks!

Skiff is very janky with the radial as it's not technically a mount.

It's a mastery ability. And there is only one keybind for all your mastery abilities. So if you have fishing selected, the skiff radial will pull out your fishing rod.

AFAIK there's no option to set individual keybinds for each of your mastery abilities.

**Comment by SOL4RIS** [comment]
> > Oh... that makes sense, since I would be using W to run.  I tried setting the key-bind to something else (Num 1) and it works fine.  So, now that I have all my mounts on the numpad, here's hoping I don't run out of keys when the expac comes out.  Already trying to figure out where turtle and skiff are going to go... lol.
> > Thanks!
> 
> Skiff is very janky with the radial as it's not technically a mount.
> 
> With mounts, you get a new keybind option when you unlock them. But since the skiff is a mastery ability it shares the same keybind with fishing and other master abilities. So you have to make sure you have the skiff selected before using the radial.
> 
> If you had the fishing skill selected for example, using the radial for skiff would pull out the fishing rod.
> 
> AFAIK there's no option to set individual keybinds for each of your mastery abilities.

Yeah, I did write that comment before EoD launched and we knew how the weird mastery skill thing was going to work. I did still bind my "skiff" to the mastery ability, but I leave it activated on Fishing instead, since the skiff has some weird placement stuff. It would be nice to be able to change the icon from a boat to a fishing rod, but since I know how I'm using it, it's not a huge deal.  

For skiff, I'm just doing the mastery clicks on the default interface, because with fast casting enabled for ground targets, radial doesn't really work for skiff placement at all.
