### ISSUE TITLE
GW2Radial incompatible with Gw2-Launchbuddy?

### ISSUE THREAD

**Issue by Snaid1** [Friendly0Fire/GW2Radial#224]
When I attempt to use GW2Radial with GW2Launchbuddy it fails to load in my game.
GW2Launchbuddy is an addon loader/multiboxing program and I've been using it to launch my games, however with the latest version of GW2Radial my game fails to load it no matter how I seem to inject it from GW2Launchbuddy. Any thoughts?

**Comment by Friendly0Fire** [comment]
The addon loader and GW2Radial work fine with GW2Launcher (which is what I personally use), so I'm not sure what LaunchBuddy is doing that's different. Does the addon loader work on its own? Does it produce a log file? It's normally called `gw2al_log.txt` in the root GW2 directory, though LaunchBuddy probably moves that around.

**Comment by Snaid1** [comment]
It does function differently. GW2Launchbuddy has a menu for you to choose what dlls get injected on launch and anything in the bin folder will launch automatically.

it works fine installing from the UOAOM and using GW2Launcher to launch.

**Comment by Friendly0Fire** [comment]
Ah, well that's annoying. I'm afraid I have no idea what it's doing and how it's doing it, so I can't really help at the moment. This is also probably more of a problem with the addon loader itself, might need special handling for LaunchBuddy...

**Comment by WolfSabian** [comment]
Working fine for me with LaunchBuddy. You could be experiencing another issue.  I had a REALLY hard time getting it working at all, despite using it for... well I dont' know how long exactly.  I updated it and it wouldn't work.  I tried putting back a previous version, still no go, removing any config that existed each time.  I eventually could get it to run on it's own without ArcDPS, but could not get it to chainload at all.  I had to resort to using Addon Manager.

**Comment by WolfSabian** [comment]
> Ah, well that's annoying. I'm afraid I have no idea what it's doing and how it's doing it, so I can't really help at the moment. This is also probably more of a problem with the addon loader itself, might need special handling for LaunchBuddy...

I faced this issue with and without Launchbuddy.  I think it's just not chainloading for some reason.

**Comment by JMichielsen** [comment]
I think I've the solution to this issue, it is not with GW2Radial but a setting within GW2Launcher.

Settings > Guild Wars 2 > Management

Mode: Virtual
Localized Execution: Enable localized execution
Desired Level: Full
Synchronizing: All
![image](https://user-images.githubusercontent.com/6457278/135734581-3190117c-b685-4c04-966e-98d6ed3a3d6b.png)

this made GW2Radial work for me.

**Comment by Friendly0Fire** [comment]
After some consideration, I'm going to close this issue. I don't think it's relevant for me to look into explicitly supporting LaunchBuddy, rather this is something the addon loader should do, assuming reproducible bug reports can be provided over there.
