### ISSUE TITLE
Hot key to open Radial Wheel not working

### ISSUE THREAD

**Issue by meykel** [Friendly0Fire/GW2Radial#225]
**Describe the bug**
When using the hotkey ("Mouse 3" for example), to open the radial wheel, on center or on cursor, no wheel pops up. Occurs with any hotkey I have tried other than "Mouse 3" including keyboard hotkeys like "L" or "7". In addition, the "Show in Center" keybind does not move the cursor to the center of the window. 

**To Reproduce**
1. In the mounts tab select the desired keybind, "Show on Mouse" or "Show in Center".
2. Bind the desired hotkey to the keybind.
3. Radial wheel fails to open when using either keybind, in addition cursor does not move to center when the "Show in Center" keybind is used 

**Expected behavior**
When the hotkey is bound to the keybind, the radial wheel should open and I should be able to select the mount desired

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: GTX 1060

**Additional context**
1. Running version v2.1.0
2. Downloaded through GW2 Add-On Manager
3. I am running the client on Windowed view and not Fullscreen
4. When playing around with the settings both in game and in the radial mount settings to get around the above issue, on occasion the radial mount settings close while testing in-game hotkeys. When trying to open the radial mount setting again by pressing [Shift+ALT+M] the settings sometimes fails to open and instead the in-game world map expands on screen.  Unsure if the settings, and maybe the wheel pop-up, are properly showing up "above" the in-game window.

EDIT: I believe I was stuck in a cycle where I tried to open the wheel while mounted which will not open the radial wheel, but simply dismount. After dismounting and attempting to mount again the radial wheel opened and functioned as intended

**Comment by SeiferLeonheart** [comment]
Since I asked for a feature might as well try to help around,lol.

I've tried GW2 Addon manager about once a day for at least 1 week now, GW2 radial is not working for me using it. I firmly believe that the issue is with GW2 Addon manager and not with GW2 Radial.

Manual install works flawlessly for me, I suggest trying that.

**Comment by meykel** [comment]
> Since I asked for a feature might as well try to help around,lol.
> 
> I've tried GW2 Addon manager about once a day for at least 1 week now, GW2 radial is not working for me using it. I firmly believe that the issue is with GW2 Addon manager and not with GW2 Radial.
> 
> Manual install works flawlessly for me, I suggest trying that.

I think it ended up being a User Error on my part with the hotkey issue, there are a few new settings that took some time to get used to and know there are no issues on my end.

Also I found a work around for the GW2Addon Manager yesterday actually. Download the previous version and once installed update the app from in-window. I did that and was able to download the latest  GW2 Radial and its all working. Hope that works for you too.

**Comment by kureysalp** [comment]
Same issue for me
