### ISSUE TITLE
Addon keybind to open options menu not working

### ISSUE THREAD

**Issue by willjacksonau** [Friendly0Fire/GW2Radial#227]
**Describe the bug**
Pressing shift+alt+m does not open radial options menu

**To Reproduce**
Addon installed via addon manager. Launched game. Pressed keybind to open menu does not work.

**Expected behavior**
shift+alt+m opens options menu

**Screenshots**

**System configuration (please fill in):**
 - OS: [Windows 10]
 - GPU: [GTX2080]
 - Chainloading[None, only radial mount menu installed]

**Comment by Friendly0Fire** [comment]
Please give me your `gw2al_log.txt` and `gw2radial.log`, if any. They should be in the root folder of the game.

**Comment by Friendly0Fire** [comment]
The addon loader isn't installed in this screenshot (there should be an `addonLoader.dll` plus `d3d11.dll` and `dxgi.dll`), so nothing's currently being loaded. Make sure the addon manager successfully installed the loader and that your directories are set correctly in it.

**Comment by willjacksonau** [comment]
![Path](https://user-images.githubusercontent.com/22456677/135351075-ead25337-1c0a-4b74-b66a-072edaffb2ed.PNG)
![Error](https://user-images.githubusercontent.com/22456677/135351085-47d00155-5660-4708-98ef-80e2decf1e14.PNG)
double checked the path. Hit update on the installer and got this error

**Comment by willjacksonau** [comment]
![Bin64Folder](https://user-images.githubusercontent.com/22456677/135351230-30462776-62ff-4ff6-abf7-e54ca4f43bbc.PNG)

**Comment by Friendly0Fire** [comment]
That's strange, it's not using the right path. You'll need to move those 3 DLLs one folder up.

**Comment by willjacksonau** [comment]
I have this version of the addon manager Addon Manager v1.3.0

**Comment by willjacksonau** [comment]
Got this error after moving the 3dlls and pressing update on the addon manager
![Error 2](https://user-images.githubusercontent.com/22456677/135351784-bab0446d-5561-4934-a653-ae65c104558b.PNG)
.

**Comment by Snipyer** [comment]
I am not using the addon manager and can confirm to have the same issue.

I did a manual install for the addon when the loader was being worked on, after adding gw2radial the option menu appeared fine a couple of times than suddenly didn't work anymore.

and i had the same problem of it not appearing even before v2.1.

**Comment by willjacksonau** [comment]
[gw2al_log.txt](https://github.com/Friendly0Fire/GW2Radial/files/7255254/gw2al_log.txt)

Here is the log file after moving the 3 dll files and starting the game.

**Comment by Friendly0Fire** [comment]
@willjacksonau Please download the latest addon manager, 1.3.0 will *not* work with this release.

**Comment by willjacksonau** [comment]
Do I need to delete the addon files and start fresh with this version "Version 1.4.1"

**Comment by Friendly0Fire** [comment]
If you want to be extra safe, then the three DLLs I mentioned, that bin64 directory in bin64, and the d3d9.dll in bin64 as well, plus the addons folder (probably back that up if you have configs you don't want to lose).

**Comment by willjacksonau** [comment]
Everything seems to be working now. Thank you so much!

**Comment by FlareHeart** [comment]
I had a similar issue where the Radial got stuck open (I couldn't click on anything and the Radial wouldn't respond). During that time, it also prevented me from opening the options menu. I had to alt+tab out to a different window to get the radial to clear and even then the options wouldn't open. I exited the game entirely and reloaded and was able to open both the radial and options menus normally. The first time I opened this new version I tried to set it to use the "Open in center" and cleared the regular keybind. Maybe this had something to do with my issue? Can we use the open in center all the time with the same keybind as the regular open function?

**Comment by willjacksonau** [comment]
Just a quick question. The addon manager and radial still do not work with the dx11 beta is that correct?

**Comment by Friendly0Fire** [comment]
@FlareHeart See issue #229, let's not derail this issue.

@willjacksonau Glad to hear it worked! Currently the addon manager/loader can work with the DX11 beta, but Radial is not yet ported for it.

**Comment by willjacksonau** [comment]
Cool. I'll wait for Radial before turning on the Beta. The addon is just too good to not use.
