### ISSUE TITLE
Frozen menu

### ISSUE THREAD

**Issue by Friendly0Fire** [Friendly0Fire/GW2Radial#229]
I had a similar issue where the Radial got stuck open (I couldn't click on anything and the Radial wouldn't respond). During that time, it also prevented me from opening the options menu. I had to alt+tab out to a different window to get the radial to clear and even then the options wouldn't open. I exited the game entirely and reloaded and was able to open both the radial and options menus normally. The first time I opened this new version I tried to set it to use the "Open in center" and cleared the regular keybind. Maybe this had something to do with my issue? Can we use the open in center all the time with the same keybind as the regular open function?

_Originally posted by @FlareHeart in https://github.com/Friendly0Fire/GW2Radial/issues/227#issuecomment-930600542_

**Comment by Friendly0Fire** [comment]
@FlareHeart can you reproduce this issue in any way? Without reproduction steps it'll be very difficult to diagnose.

**Comment by FlareHeart** [comment]
If I set the "Show in center" keybind, and then clear the "Show on mouse" keybind, the issue returns. The radial will appear once, get stuck, then I have to click on a window outside the game to get it to go away and then nothing will open (crashes invisibly?). I have to totally reload to get Radial to return. At which point it sets the "Show on mouse" back to the previous keybind which keeps it functional.

**Comment by Friendly0Fire** [comment]
Thanks a lot, I'll look into it!

**Comment by Thex-PiedDroit** [comment]
Can confirm i had the same issue once (not happening anymore after restarting the game - haven't tried fiddling with the settings again) after doing exactly as OP:
- First set the binding to center
- Then cleared that binding
- Then set it on mouse
That triggered the frozen wheel, which disappeared on alt+tab but it didn't work until restarting.

Upon restarting, the binding is set on both. Clearing them does not save on restart (they get set again).
