### ISSUE TITLE
Conditions Request

### ISSUE THREAD

**Issue by WolfSabian** [Friendly0Fire/GW2Radial#231]
So, I'm not here to be negative.  I think this is a great addon and I've been using it for a long time.  I am having an issue with the latest version that i suppose is an intended feature, but I'm hoping we can get the problem sorted with conditions.

I am greatly missing the ability to Select a "next" mount via the radial even though I am unable to change mounts.

Lets say I'm flying, be it on Griffin or Skyscale, making my way to a landing where I quickly need to mount back up on a different mount.  It use to be possible to open Radial, and "select" a mount, thus changing the previous mount and once able allowing me to get on the one I chose with a simple click.

Now the Radial menu doesn't show up at all when i'm on a flying mount or in mid air falling a small distance or doing a jump.  I'm not looking to bypass the ability to NOT be able to mount, just hoping it would be possible to some how be able to bring up the Radial menu as before and go on with my quick mounting and my adventure.

**Comment by Friendly0Fire** [comment]
So let me make sure I understand: you used to call up the radial menu on a mount in the air, knowing it wouldn't do anything, but allowing you to set what your "previous" mount would be so you could just tap the key once on the ground.

That's a use case I'd never heard of before. Very interesting!

I'll have to think about how I might implement this without breaking other features. I hope you understand that it might take some time and that bugs currently take priority.

**Comment by WolfSabian** [comment]
> So let me make sure I understand: you used to call up the radial menu on a mount in the air, knowing it wouldn't do anything, but allowing you to set what your "previous" mount would be so you could just tap the key once on the ground.
> 
> That's a use case I'd never heard of before. Very interesting!

Yep that's pretty much it.  I quickly noticed i could no longer do it.

> I'll have to think about how I might implement this without breaking other features. I hope you understand that it might take some time and that bugs currently take priority.

I understand.
