### ISSUE TITLE
Cannot mount under water

### ISSUE THREAD

**Issue by jb-uw** [Friendly0Fire/GW2Radial#235]
**Describe the bug**
Unable to mount under water. Skimmer is "queued" instead, until I surface. Yes I have the mastery, and am able to mount if I select skimmer through the build in GW2 UI

**To Reproduce**
1. go under water
2. use GW2 radial
3. skimmer queued instead of mounting

**Expected behavior**
I should be able to mount the skimmer under water

**Screenshots**
![skimmer_bug](https://user-images.githubusercontent.com/27322622/135574408-12546c09-f820-4cfd-9b0e-c5c63d001226.jpg)

**System configuration (please fill in):**
 - OS:  Windows 10
 - GPU: Nvidia GeForce GTX 1660 Ti

**Additional context**
None

**Comment by SparcoGreddy** [comment]
Did you also check the mastery checkbox in the settings? Radial can't detect if you have the mastery so you have to tell it that you can actually mount underwater.

**Comment by jb-uw** [comment]
OK, there’s a new “enable underwater mount” check box in the tool that is unchecked.

 

Why on earth would the design be turning off an existing ability by default? It used to work.

 

Anyway, fixed now.

 

Thanks

**Comment by SparcoGreddy** [comment]
"Why on earth would the design be turning off an existing ability by default? It used to work."

Because the default state of the ability ingame is also "off" you have to train and earn it first, its not a default ability.
