### ISSUE TITLE
The Marker section's reset_cursor_after part is broken.

### ISSUE THREAD

**Issue by Noellic** [Friendly0Fire/GW2Radial#236]
The checkbox doesn't do anything. It'll reset the mouse to where it was regardless. But its only for the Marker tab. Objective Markers, Mounts, Novelties are fine.

Another problem is the show on center, show on mouse thing.
The first time you keybind it, it works fine. But if you try to change it from like show on center to show on mouse, it doesn't delete the keybind for show on center even though it says it does. And then if you use the wheel menu it becomes stuck on your screen. You can tab out and tab back in to get rid of it, but then radial itself doesn't open. You have to restart the game to make it start again. And even if you restart, the problem persists. You have to delete the config file and rebind everything again to make it work.

Edit: BTW, I don't use Addon Manager. For some reason it doesn't work for me. But I'm assuming that's a different problem related to the manager and not radial.

**Comment by Friendly0Fire** [comment]
> The checkbox doesn't do anything. It'll reset the mouse to where it was regardless. But its only for the Marker tab. Objective Markers, Mounts, Novelties are fine.

This is by design, since the Markers will be put wherever your mouse is located, so it needs to be moved back before sending the key. I'll remove the UI option for the tab.

Your second issue is already tracked in #229.

**Comment by Noellic** [comment]
Ok, understood. Thanks.

**Comment by Friendly0Fire** [comment]
I clarified the readme a few days ago: https://github.com/Friendly0Fire/GW2Radial#manual-installation
