### ISSUE TITLE
spamming to dismount

### ISSUE THREAD

**Issue by Z0T3X** [Friendly0Fire/GW2Radial#238]
when i have mounted and want do dismount i can press my mount/dismount button up to over 20 times and it still wont dismount me 

**Expected behavior**
dismount in  1 click 

**Screenshots**
cant make screenshot of it :)

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: GTX1060

**Comment by sicu** [comment]
This is likely the same issue as was discussed in: https://github.com/Friendly0Fire/GW2Radial/issues/233
Have a read and if it's the same issue you can close this as a fix was committed and will probably come in the next release.

**Comment by Z0T3X** [comment]
alsmost same issue :D 
tho it got fixed when i made new keybindings for it :)
