### ISSUE TITLE
Add a "favorite mount" to center area of the default menu

### ISSUE THREAD

**Issue by SeiferLeonheart** [Friendly0Fire/GW2Radial#240]
First of all, thanks Friendly0Fire for the great mod, it's pretty much a necessity at this point, can't play without it and V2 is SOOO good.

That being said, I'd like you to consider the following feature: Adding a "favorite mount" to the center area of the default menu.

The necessity: 

Before using this awesome mod, I used numpad for the custom bindings for each mount, and left the default binding "X" to the mount I mostly use. (I'd say skyscale is what people will use 80% of the time based on absolutely nothing)

You see, around 90% of the time (another arbitrary number, for the record) I'm opening the menu just to select Skyscale. I'm using Radial for the "deviations" in this process, when I need a specific mount, but that's the minority of the cases. 

Proposed solution: 

In line with contextual Skimmer binding (which is AWESOME btw), I'd like to, with a single press, mount my "favorite mount" without actually "using" Radial. Adding a checkbox to this functionality on the menu, and having this "favorite mount" slot on the center. That way if you use your radial binding AND move the mouse, you select the mount just as it happens today. IF you don't move the mouse you select this "favorite", centered, mount.

I hope my idea is clear and thank you for even considering adding requested features. I also hope that if you do decide to work on this, it's an easy implementation. I know very well how end-users tend to ask for "easy features" that are a huge headache, lol

**Comment by Friendly0Fire** [comment]
Both of these are already implemented. 
![image](https://user-images.githubusercontent.com/3399000/135739557-aac3fa30-d6a2-4b7c-8084-043b4a5bbce0.png)

**Comment by SeiferLeonheart** [comment]
> 
> 
> Both of these are already implemented. ![image](https://user-images.githubusercontent.com/3399000/135739557-aac3fa30-d6a2-4b7c-8084-043b4a5bbce0.png)

Damn... I'm blind! Thank you! It's perfect!
Sorry for the useless post!
