### ISSUE TITLE
New v2.1.1 Gw2Radial crashed with ArcDPS (DPS, Healing stat, boon table, buildpad) with last updates at 2021.10.02

### ISSUE THREAD

**Issue by MiryksV** [Friendly0Fire/GW2Radial#241]
**Describe the bug**
I tried the very new fixed v2.1.1 of the big one v2.1.0 but it crashs when I moust/unmount during mouting with the associated keybind that clashing with ArcDPS (DPS, Healing stat, boon table, buildpad) last updates (all dowloaded from official github/website) at 02.10.2021.

**To Reproduce**
Setup:
- Keybind : for Mount > Show in center > M4 (precedent button on mouse)

1. Log in (account with all mount or not, main or alt account)
2. Press keybind to mount then unmount several time
3. Gw2 crashed due to a clash between 2.1.1 and ArcDPS

**Expected behavior**

**Screenshots**
![arcdps_lastcrash-2021 10 03](https://user-images.githubusercontent.com/45184594/135741436-fe41c0bd-61f3-42d8-be40-116c53243bf6.png)

**System configuration:**
- windows: 10.0
- cpu: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
- ram: 8083MB / 16278MB used 			
- gpu: NVIDIA GeForce GTX 1060 6GB
- Addons:
  - ArcDPS (DPS _d3d9.dll_, Healing Stat _arcdps_healing_stats.dll_, Boon Table _d3d9_arcdps_table.dll_, BuildPad _d3d9_arcdps_buildpad_2021-09-24.dll_) manually installed located in _/bin64_.
  - Gw2Radial _gw2addon_gw2radial.dll_ of v2.1.1 is renamed in _d3d9_chainload.dll_.

**Additional files**
_arcdps_lastcrash.log_: [arcdps_lastcrash.log](https://github.com/Friendly0Fire/GW2Radial/files/7272765/arcdps_lastcrash.log)

**Comment by marvicnet** [comment]
Hello,

I probably got the same error. Happend two times yesterday after I did the update to latest version.
Happend again today, so I put it back last version for now. Will see if it will happen again.

I only use vanillia arcdps with radial as "d3d9_chainload.dll"

Here is the error file from acrdps after crash:
[arcdps_lastcrash-mv.txt](https://github.com/Friendly0Fire/GW2Radial/files/7277551/arcdps_lastcrash-mv.txt)

**Comment by Friendly0Fire** [comment]
The crash reports from arcdps aren't very useful to me, but if you have `.dmp` files I can use those.

**Comment by sn0opy** [comment]
I can easily reproduce this on my client by starting a raid instance (Spirit Vale in my case), holding down radial key and and releasing it without actually choosing any mount. After releasing the mouse button, the client crashes. 

My setup: arcdps as d3d9.dll loading radial menu as d3d9_chainload.dll which is loading d912pxy as d912pxy.dll in case that's relevant.

**Comment by Arkkhalis64** [comment]
**Describe the Bug**
The game crashes when opening the mount radial menu.

**To Reproduce**
Steps to reproduce the behavior:
1. Load into any map.
2. Press your hotkey for the mount radial menu to appear.
3. Game freezes for 1-2 seconds then crashes.

**System Configuration:**
- OS: Windows 10 Pro (x64) Build 19043.1237 (21H1)
- CPU: Intel Core i7-8700K
- GPU: NVIDIA GeForce GTX 1080 Ti
- Multiple addons installed through GW2-UOAOM: ArcDPS, Blish HUD Integration, Boon Table, Clears, Healing Stats, Killproof-me Plugin, Mechanics Plugin, BuildPad, libimgui

**Additional Files**
[arcdps_lastcrash.log](https://github.com/Friendly0Fire/GW2Radial/files/7283714/arcdps_lastcrash.log) (addon replaces game's default crash log)
[ArenaNet.log](https://github.com/Friendly0Fire/GW2Radial/files/7283723/ArenaNet.log) (deleted ArcDPS addon folder to re-enable default crash log)

**Comment by Noirtales** [comment]
i had seemingly the same error, but a newer bugreport from two days ago also mentioned it and they came to the conclusion that it crashes if you leave the cursor in the center without selecting anything. So what worked for me is to put center behavior on previous until its fixed

https://github.com/Friendly0Fire/GW2Radial/issues/244#issuecomment-935872299

**Comment by Friendly0Fire** [comment]
This should be fixed by commit 3c7d3c4160a917c2a004e193086de2d3db205ab5.
