### ISSUE TITLE
Radial does not show up in any way

### ISSUE THREAD

**Issue by MWShurikan** [Friendly0Fire/GW2Radial#242]
Since a few days, my radial does not show up, no matter what i try.
Steps i tried to fix this:
- remove and re - install addon manager
- remove and re - install radial
- removing all other addons except radial
- clearing all files in the GW2 folder (except GW2 exe and GW2.dat
- installing radial manually

The problem exists regardless of using DX9 and DX11.
If i start up GW2, radial just does not appear and also pressing the keys (shift + alt + m) does not work.
The file gw2radial.log is just empty.
in the addons folder (within the GW2 folder) there is a gw2radial folder that contains 2 files (gw2addon_gw2radial.dll and readme.md)

**Comment by Friendly0Fire** [comment]
Please check if you have a `gw2al_log.txt` in your root GW2 folder and if so, quote/attach it.

**Comment by MWShurikan** [comment]
[gw2al_log.txt](https://github.com/Friendly0Fire/GW2Radial/files/7274377/gw2al_log.txt)

**Comment by Friendly0Fire** [comment]
Try installing lib_imgui, SelectRender is currently not running without that and it could have an impact.

Do you have `.dmp` files in the root GW2 directory?

**Comment by MWShurikan** [comment]
Currently getting errors on AddonManager (because i started it to much, apparently this is a thing). Will try to install lib_imgui if my addon manager runs again (may take until tomorrow for feedback). Currently no .dmp files on my gw2 root, it looks like the attached screenshot

![2021-10-03 21_15_18-Window](https://user-images.githubusercontent.com/79650807/135768213-4f1b9e4a-f3a5-432d-a13b-96fd5f6406aa.png)
