### ISSUE TITLE
Using backslash "\" as a mount keybind will not auto-unmount

### ISSUE THREAD

**Issue by FlareHeart** [Friendly0Fire/GW2Radial#243]
One of my mounts was bound to the backslash key and it used to work for both mount and unmount using radial. After upgrading, the auto-unmount when pressing my radial keybind no longer works. Pressing backslash manually in-game still works for both mount and unmount. Only the auto-unmount on radial activation seems to fail. Re-binding to a different keybind for that particular mount solves the problem. 

(If this is a problem with my choice of keybind and can't be resolved, then that's OK, I have found a different one that does work). 
Thank you for this awesome add-on! I couldn't live without it anymore! 

Windows 10
GeForce GTX 1080
I am not chainloading any other add-ons

**Comment by Friendly0Fire** [comment]
You mean you had both the menu keybind and one of your mounts on the same key? As much as I totally understand the lack of keys on a keyboard to do everything, I'm afraid that's really not a behavior I can support properly, it's far too prone to overlaps and weird edge cases.

**Comment by FlareHeart** [comment]
No, I use Shift for the radial menu. I used backslash for the
mount/unmount. For some reason the dismount doesn't work when activating
the radial. But it works when I press the backslash key manually.

~Trista
No trees were destroyed in the sending of this message, though a
significant number of electrons were terribly inconvenienced.

**Comment by FlareHeart** [comment]
Let me clarify a little. I'm not sure I'm explaining this correctly. 

Steps to reproduce:
1. Bind a mount to backslash (The one above the enter key "\\")
2. Bind Radial menu key to Shift
3. Activate Radial and mount the one bound to backslash
4. Press Radial key again to attempt to dismount
5. What should happen: Dismount. What actually happens: Nothing.
