### ISSUE TITLE
[Solved] Does not work ingame since dx11

### ISSUE THREAD

**Issue by Dajova** [Friendly0Fire/GW2Radial#245]
I have the same issues as this guy: https://github.com/Friendly0Fire/GW2Radial/issues/242

Problem is, i have those installed and it still doesnt work. arcdps still works fine, just not GW2R.

here's the log: [gw2al_log](https://gist.github.com/8b9cae685a242602b45cf728e34610e5)

**Comment by Dajova** [comment]
> 
> 
> See Issue #213: "DX11 support?"

... yes? was that supposed to show me something i've missed? I am using that to install both addons. arcdps works, gw2r does not.

**Comment by nakami** [comment]
Afaik no addons that hook the game work on dx11 as of yet. The only ones so far are overlays.
