### ISSUE TITLE
GW2Radial breaks GPU power management

### ISSUE THREAD

**Issue by Jademalo** [Friendly0Fire/GW2Radial#246]
**Describe the bug**
This is a weird one, and I'm not even sure the best way to describe it.

Modern GPUs are designed to constantly change their clockspeed depending on the load they're under. My 3080ti idles at 210mhz, and under a heavy load goes up to 1985mhz.
When running GW2 normally, it's usually at a lower clockspeed during loading screens etc, and then goes up high during actual 3d rendered gameplay. 
When I then close the game, the clock goes back down to 210. In this idle state it pulls around 20-30w of power, and hovers around 40c.

When GW2Radial is installed and active, the card seems to get stuck in maximum performance mode. 
The entire time GW2 is open, it is pegged at the maximum clock speed, even during loading screens. This isn't the biggest issue though, the real issue is that even when the game is closed and the executable is ended, the GPU stays locked in this max power mode.
This results in an idle power draw of 150w, and an idle temperature of up to 60c.

I have only discovered two ways to get the card "unstuck" - A cold reboot, or loading GW2 with radial disabled and then closing out of the game. 
It almost seems as if some sort of cache isn't being correctly flushed when radial is active, because even with no remnants of GW2 open the card refuses to go back down to idle.

**To Reproduce**
1. Load the game
2. Close the game

**Expected behavior**
Once the game is closed, the GPU changes power state and clockspeed depending on the load.

**Screenshots**
![image](https://user-images.githubusercontent.com/386846/136320533-66d1f2fa-04f5-4bce-8f6e-dc16ae5209be.png)

To elaborate on this screenshot slightly - The beginning of the graph is my PC at idle stuck after having closed GW2 with radial open. I then open GW2 in the middle without radial, then close it. You can see that closing GW2 without radial takes it down to a low power state, but at the start it was stuck in a high power state.
You can see when I had GW2 open by looking at the System Memory usage, for reference.

**System configuration (please fill in):**
 - OS: Windows 11 (but this also happened on 10)
 - GPU: 3080ti
 - Addon Loader

**Comment by Jademalo** [comment]
Still having this issue, but I have written a quick little batch script to disable radial, load the game, kill the game, and re-enable radial. It's not the most elegant solution, but it works.

```@echo off
if exist "S:\Guild Wars 2\addons\gw2radial\gw2addon_gw2radial.dll" (
    rename "S:\Guild Wars 2\addons\gw2radial\gw2addon_gw2radial.dll" "gw2addon_gw2radial.dll.bak"
)

start "" "S:\Guild Wars 2\Gw2-64.exe"
timeout /t 20
taskkill /im Gw2-64.exe

if exist "S:\Guild Wars 2\addons\gw2radial\gw2addon_gw2radial.dll.bak" (
    rename "S:\Guild Wars 2\addons\gw2radial\gw2addon_gw2radial.dll.bak" "gw2addon_gw2radial.dll"
)```

If anyone else is having this issue and uses this script, make sure to change `S:\Guild Wars 2` to your gw2 install directory. Also you might need to modify the timeout value if it's not closing automatically.

**Comment by Friendly0Fire** [comment]
Since this seems to be an extremely rare issue and will most likely be resolved by the eventual move to D3D11, I really can't justify spending a long time trying to track this down, sorry.

**Comment by Jademalo** [comment]
Alright, that's fair! 
Hopefully the workaround will suffice for anyone else struggling with it until then.
