### ISSUE TITLE
Disabling "move cursor to original location after release" crashes the game.

### ISSUE THREAD

**Issue by Venrexx** [Friendly0Fire/GW2Radial#247]
Basically what the title says, if you disable "move cursor to original location after release" in mounts menu, the game crashes. I have tried every combination, but the basic of what I tried was to set open in center, and disable move cursor option, and game crashes every single time.

**To Reproduce**
1. Disable "Move cursor to original location after release"
2. Enable "Show in center"
3. Use mount wheel
4. Enjoy the new view of your desktop

**Expected behavior**
I expect to have the mount wheel show up, my mouse cursor to move to the center of the screen, and stay there afterwards.

**System configuration (please fill in):**
 - OS: Windows 10 Pro
 - GPU: GTX1070 Hybrid
 - No chain loading. This is the only mod installed.

**Additional context**
This wheel menu works every single time in every way except when that option is disabled. Nothing else seems to cause this.

**Comment by Ghostkat9** [comment]
Why was this closed? I am still having this problem. I don't know how to implement void-method's fix or if it even works properly.

Will this be fixed in the next version? Without this working properly, it becomes a pain to use the mount menu.
