### ISSUE TITLE
Can't (always) dismount using hotkey for radial menu

### ISSUE THREAD

**Issue by mwellstein** [Friendly0Fire/GW2Radial#250]
**Describe the bug**
I can properly mount, but dismounted doesn't work (for some mounts) depending on the chosen hotkey.  
Dismounting using (any) full mount hotkey ofc still works and is my current workaround.

There might be a relation between this and #243. But in case it's something different, i wouldn't want to disturb the discussion over there.

**To Reproduce**
I encountered this issue with the following hotkeys:

- Raptor: Shift + V
- Springer: Strg + V
- Skimmer: Ctrl + Space
- Jackal: Shift + Strg + V
- Griffon: Shift + Space
- Roller Beetle: Ctrl + B
- Warclaw: Ctrl + Shift + B
- Skyscale: Shift + B
- Radial Hotkey: V

Mounting onto the selected mount always works.  
But i'm not being dismounted from Raptor, Springer and Jackal.
My initial guess was that it's a problem that i use V as part of the mounts hotkey and as hotkey for the radial menu.  
Binding the radial menu to K for example solved the above issue completly.
But using Shift for the radial menu makes it strange. Now all mounts dismount, except for Skimmer. Skimmer doesn't even use Shift in it's hotkey.

I'm using neither V nor Shift (alone) for any other hotkey in Guild Wars 2. At least i didn't find anything.
Same effect using Show on Mouse and Show on Center, if it even matters.

**Expected behavior**
To get properly dismounted from all of my mounts, not just from a subset.

**System configuration (please fill in):**
 - OS: Windows 10 (21H2)
 - GPU: 1660 TI
 - Chainloading: happens always
   - using only radial
   - arcdps -> gw2radial
   - arcdps -> gw2radial (next to killproof and unofficial extras
   
**Additional context**
Other than hotkeys the only radial options changed was "Enable underwater Skimmer" (but tested without it too), and i once had a condition on my hotkey to see what it does.

**Comment by AudioEmu** [comment]
Can confirm that "overlapping" keybinds seems to have been the issue for me as well.

I presently only have 3 mounts, originally bound to ctrl+z, ctrl+x, and ctrl+c. My radial key was z, and I was having issues dismounting. Keeping my radial key set to z, but bumping all the mount binds a key to the right and freeing up ctrl+z has solved the issue completely as far as I can tell.
