### ISSUE TITLE
Radial fatal error

### ISSUE THREAD

**Issue by UmbraSilver** [Friendly0Fire/GW2Radial#251]
Upon downloading Addon Manager and installing gw2radial through it, while gw2 starts normally and I see the freshly installed radial window on character select screen, game crashes while trying to load into a map.
I do not have anything else installed, no shaders, no extra addons, nothing at all. Discord overlay is disabled. Not using dx11 either. Only gw2radial.
![Screenshot (650)a](https://user-images.githubusercontent.com/92585638/137491670-8e12dcce-954b-4191-a4a1-6a4ea3721f54.png)

**Comment by Matuc1337** [comment]
I have the same issue. I only have ArcDPS installed. 

My Specs
CPU: Intel core i5 4460
GPU: MSI Geforce 750 Ti
OS: Win 8.1 64bit
RAM: 16 Gb

**Comment by Matuc1337** [comment]
nevermind. fount the fix with the 47.dll

**Comment by UmbraSilver** [comment]
Found fix as well in older threads. Installed manually without addon manager. Issue caused by non compatibility with win 8.1
