### ISSUE TITLE
Input queueing circle icon consistently showing up.

### ISSUE THREAD

**Issue by Anthrozil7** [Friendly0Fire/GW2Radial#256]
https://user-images.githubusercontent.com/15947855/139370054-b9a8e099-7b36-41a5-90f9-800f5afd28f3.mp4

As shown in the video, I'm having the icon for what I think is input queueing showing up/flickering repeatedly despite me not inputting any commands.  I also have input queueing turned off as shown.  This happens more frequently while I have multiple instances of the game open via gw2launchbuddy or gw2launcher, but I've seen it happen with only a single instance open as well.  This happens regardless of if  I install through addon manager or directly in bin64.

Wondering if there's a setting that I'm not able to find to prevent this behavior or if this is a bug.

**Comment by Friendly0Fire** [comment]
The improvements I've made should help, but important reminder: make sure your Mumble Link settings are correct in GW2Launcher. Each game instance needs its own "Mumble link name", otherwise there'll be a lot of conflicting information that'll cause odd behavior.
