### ISSUE TITLE
Auto select Skyscale while gliding?

### ISSUE THREAD

**Issue by Rorhi** [Friendly0Fire/GW2Radial#259]
Love this addon, it simplifies using mounts a lot, I particularly like the option to auto-select mounts in particular circumstances.
I'd like the option to auto-select the Skyscale mount while Gliding and/or falling if you have the requisite mastery.  Would this be possible?
Love your work, Thanks :)

**Comment by Friendly0Fire** [comment]
Sadly the game doesn't provide any way to detect when you're gliding/falling/jumping. If they ever add flags for these, I'll definitely implement this.

**Comment by Rorhi** [comment]
That's a shame, thanks for the response
