### ISSUE TITLE
Don't fail silently, warn or activate glider if mounting is not allowed.

### ISSUE THREAD

**Issue by PaterFrog** [Friendly0Fire/GW2Radial#260]
**Is your feature request related to a problem? Please describe.**
Unexpectedly not being able to mount sometimes causes your death in areas where mounting is not allowed and mounting fails. Normally this is not a problem, but if you are falling and trying to mount your skyscale/griffon, you will fall to your death before you have the time to realize _why_ you're not mounting up and hit your glider.

**Describe the solution you'd like**
If mounting is not allowed, please display an error message or big red X across the wheel or sth similar. A strong visual clue that warns you that you will not be mounting, instead of failing silently. 

**Describe alternatives you've considered**
If GW2Radial doesn't succeed in mounting try the glider instead.

**Comment by Friendly0Fire** [comment]
I cannot detect unauthorized areas, and I also cannot implement a fallback output as a result. These are all things I've asked ANet to implement but have yet to see any update on.
