### ISSUE TITLE
Game crash when using the activation key after aALT+ Tabbing out and coming back in to game.

### ISSUE THREAD

**Issue by Venrexx** [Friendly0Fire/GW2Radial#262]
**Describe the bug**
This really only seems to happen when I ALT + TAB out of the game to check a website or something, then when I come back into the game, I use the key to summon the mount, and my game crashes. Mount key is currently set to ALT.

**To Reproduce**
1. Hit ALT + TAB to leave the game and use a browser
2. Return to the game
3. Use the bound key (ALT, if you want to copy the one I am using for testing purposes)

**Expected behavior**
When I click the button, I expect the mount radial menu to appear, regardless whether or not I have kept the game in focus the entire time I have been playing. If I select nothing, I expect the favored mount to be selected, in this case, the Skyscale.

**System configuration (please fill in):**
 - OS: Windows 10 Pro
 - GPU: GTX1070 Hybrid
 - No chainloading, this is the only mod installed. I have even tried a clean install of this mod, and problem still persists.

**Comment by Friendly0Fire** [comment]
Does this happen with keys besides Alt?

**Comment by Venrexx** [comment]
No, this only seems to happen when ALT is set as the mount key.
