### ISSUE TITLE
Requesting an option to disable menu when in Trading Post

### ISSUE THREAD

**Issue by Venrexx** [Friendly0Fire/GW2Radial#263]
**Is your feature request related to a problem? Please describe.**
Whenever I try to use an easy to access keybind, such as E, it will activate in the Trading Post and reset my cursor back to the beginning of the search box when I use that key in the search, which as you can imagine, E is used quite a lot, and this makes it impossible to type so long as that keybind is set. 

**Describe the solution you'd like**
I would like an option to have the radial menu not function at all when Trading Post window is open.

**Describe alternatives you've considered**
Disable it when Trading Post window is open, when typing in chat, and when using any other menu that requires use of typing. Another option would be to have it not reset my cursor to the beginning of the line, while also leaving the radial menu active, although I am not sure how to accomplish this.

**Comment by Friendly0Fire** [comment]
Unfortunately I cannot detect the trading post or anything related to it.
