### ISSUE TITLE
Expanding Conditional Keybinds menu triggers with Elite specialization flags

### ISSUE THREAD

**Issue by whiteaden** [Friendly0Fire/GW2Radial#265]
**Is your feature request related to a problem? Please describe.**

I've been expanding upon your sample custom menu (attunements) to help someone with arthritis play classes with lots of F skills.
It's been super helpful that I'm able to trigger menus based on which class they're playing, but I wonder if it's possible to expand those conditional keybinds to include elite spec flags.
For example Necromancer only needs F1 for Core/Reaper/Harbinger while Scourge requires access to F1-F5 on the menu. 
I use a generic class icon bound to an unused GW2 key (F8 in my menu) to provide a cancel cast option.
![samples](https://user-images.githubusercontent.com/6457278/145693771-0a31412e-4fb2-433e-82a8-f57cfa130544.png)
(sample of some of my class menus)

Is it possible to expand the existing conditional options to check for which elite specialization you have equipped?

**Describe the solution you'd like**
The ability to select elite specializations as a trigger for the conditional keybind to work, either as an option in the top level menu:
![conditionalKeybinds_2](https://user-images.githubusercontent.com/6457278/145692410-8217ffee-89d0-4c6f-b1fb-3902b09f9d44.png)

or as a sub-section using the *and if* conditional
![conditionalKeybinds](https://user-images.githubusercontent.com/6457278/145692246-10fad058-a48c-47cc-b2ab-e8c4b2de863a.png)

**Describe alternatives you've considered**
Currently I've set up a single menu per class; with each possible F-skill set as it's own keybind, this enabled the user to switch which skills are visible on their radial menu as required by the equipped elite spec, this means that they have to switch their menu settings every time they swap elite specs.
![image](https://user-images.githubusercontent.com/6457278/145692610-cd6ee17c-78a6-4aaa-b0d4-cc66de6cdcce.png)

**Additional context**
Ranger is one of the classes that prompted this request (the other being Engineer/Mechanist) as they have so many F-skills already, and with the Untamed moving the "attack my target / Return to me" to new keybinds it's become a bit messy creating keybinds for each of them and ensuring the correct ones are visible on mouse.

Here's my current setup for ranger with all keybinds visible 
![Ranger_Mess](https://user-images.githubusercontent.com/6457278/145693423-b2730159-9a88-49fa-a9df-0fe961f45d37.png)

(Skill Icons aren't final, I plan to add visual queues to skills that are ground targeted; and show both icons for flip-over skills (e.g. Soulbeast Pet+Merged skills, Untamed Unleashed+Pet skills)

**Comment by jimmon89** [comment]
I'd like to second a request for this, i am doing something similar for my own usage and this would be amazing

**Comment by Friendly0Fire** [comment]
@jimmon89 @whiteaden If you go ahead and grab [2.1.2 prerelease 2](https://github.com/Friendly0Fire/GW2Radial/releases/tag/v2.1.2-pre2), I'd appreciate a little bit of testing and feedback on whether this works properly for you now that this feature has been implemented. If so, I'll close the issue.

**Comment by jimmon89** [comment]
> @jimmon89 @whiteaden If you go ahead and grab [2.1.2 prerelease 2](https://github.com/Friendly0Fire/GW2Radial/releases/tag/v2.1.2-pre2), I'd appreciate a little bit of testing and feedback on whether this works properly for you now that this feature has been implemented. If so, I'll close the issue.

testing it out now, currently creating the 2 new configs for each class
i will let you know how it works once i get it all set up

**Comment by whiteaden** [comment]
> @jimmon89 wrote:
what about adding the ability to enable conditional keybinds and set it's parameters in the config and also an easy way to detect if the character is using a core build, not an elite specialization

I thought about the same thing actually, if there's a way to set/save it in the config file that'd alleviate some of the fiddling for users.

I'll get to testing my custom menu configs once work simmers down a little today. will add a detailed report of my findings later.

**Comment by whiteaden** [comment]
It looks to be working when I set the conditional keybinds up as follows:
**Core**
![image](https://user-images.githubusercontent.com/6457278/150013830-208dd749-e3ab-427b-916f-d3bc2caec4fa.png)

If I set up only "Only enable keybinds if character is profession: Ranger" it will supersede the Druid/Soulbeast conditional binds.


**Druid**
![image](https://user-images.githubusercontent.com/6457278/150013921-4922d0dc-9b70-4f28-bc9b-86aceabe5a29.png)

**Soulbeast**
![image](https://user-images.githubusercontent.com/6457278/150013955-9336e85c-afd3-455a-829e-9c529b3eceeb.png)

Is that working as expected @Friendly0Fire ?

**Comment by Friendly0Fire** [comment]
That looks correct, yes! The final version will also have an explicit "No Elite" condition which you can combine with a profession to target core builds.

**Comment by jimmon89** [comment]
> That looks correct, yes! The final version will also have an explicit "No Elite" condition which you can combine with a profession to target core builds.

excellent, the only thing more i could ask for is a way to preconfigure conditional keybinds inside each custom radial ini

**Comment by Friendly0Fire** [comment]
You can configure them in the INI since that's where the entire config is stored at the end anyway, but it's not a very human readable format and redesigning it to be more human readable would be a pretty complicated task. If I end up doing it, it'll be in a later update.

Since this looks to be satisfactorily resolved, I'll close the issue now.
