### ISSUE TITLE
Pressing the hotkey quickly to auto select the Favorited mount will often select a different mount instead

### ISSUE THREAD

**Issue by Venrexx** [Friendly0Fire/GW2Radial#267]
**Describe the bug**
I more often than not just tap my assigned mount wheel button (Q) to just select the default favorited mount (Skyscale). About half the time it will instead pick different mounts, and I will have to dismount and click it again to make it pick the right mount. I've had it select pretty much every single mount now, when it should just be selecting Skyscale, and I have multiple times expected to mount up on the Skyscale and hit jump to start flying, but instead what happens is it will pick something like the Roller Beetle, and I will speed off a cliff or something by accident.

**To Reproduce**
1. Set a favorite mount in the Mod's configuration menu
2. Quickly tap the assigned wheel menu button (I also have reset cursor to center option enabled, if that helps)
3. Sometimes it will work correctly, other times it likely won't. Happens to my wife, my friend, and myself, so I assume it's not just us.

**Expected behavior**
I expect to tap the button, and have it automatically select the favorite mount every time, unless another mount is otherwise selected.

**System configuration (please fill in):**
 - OS: Windows 10 Pro
 - GPU: GTX1070 Hybrid
 - No chainloading, this is the only mod installed

**Comment by Friendly0Fire** [comment]
You'll want to adjust the various delays and timers in the settings. Specifically, increase the "Pop-up delay" and add a "Behavior when released before delay has lapsed" choice (this can be different from your regular favorite!).

What happens is that the mouse doesn't get moved until the menu is fully opened, so if you go too fast it won't have been moved to the center of the wheel. The pair of options I mention above were added to address this specific use case.
