### ISSUE TITLE
Chainload for arcdps and radial no longer works

### ISSUE THREAD

**Issue by Vicartori** [Friendly0Fire/GW2Radial#268]
Hi all, I just encountered this issue after updating the latest arcdps. It seems the chainload for arcdps and GW2 radial no longer works. Has anyone encountered the same issue? Any solutions please?

**Comment by ichJan1970** [comment]
Hi,

using 
https://github.com/gw2-addon-loader/GW2-Addon-Manager/releases
runs fine with Radial+ArcDPS+d912pxy all together.

but manually chainloading any other after ArcDPS is broken for me too after last ArcDPS-Update (dec.14.2021).

**Comment by Vicartori** [comment]
Thanks for sharing. Good to know that I am not the only one encountering this issue. I too encountered this issue after downloading the Dec 14 2021 Arcdps update. If anyone is encountering this issue too, appreciate if you can share so as to get the developer's attention. 

Thanks :)

**Comment by itVictor** [comment]
The issue is with arc's latest update, if you use an older version of arc chainloading works fine. However delta (arc maintainer) has publicly stated that he is strongly considering dropping support for manual chainloading in favor of using the addon manager for using multiple addons so you might as well just start using that.

**Comment by Vicartori** [comment]
Thanks for the info itVictor. Unfortunately for me, when I use addon manager, I was unable to use arcdps and radial with ReShade. ReShade application just stops working :(

**Comment by Friendly0Fire** [comment]
From arcdps's changelog:

> dec.18.2021: chainloading will no longer be supported, other wrapper loading should be done through addon manager.

It's dead, Jim.
