### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by the-void997** [Friendly0Fire/GW2Radial#271]
Install the latest update using GW2 addon Manager.  Initially the Radial was not loading at all.  I followed a recommendation from another user regarding the manager putting the file in the wrong location.  I moved it to the recommended location in their post (https://github.com/gw2-addon-loader/GW2-Addon-Manager/issues/175), and now the radial appears but does not save any settings, with an error message stating No such file or directory. I also tried using a direct installation with the ZIP and received the same issue.

**To Reproduce**
GW2 is installed in C:\Program Files\Guild Wars 2
GW2-Addon-Manager is installed in C:\Users\<user>\Documents\gw2\GW2-Addon-Manager
Addons installed gw2radial 
**Expected behavior**
**Screenshots**
![GW2Radial bug](https://user-images.githubusercontent.com/98233762/150657343-c56f4279-993b-4b34-b10d-abd5899c83af.JPG)

**System configuration:**
 - OS: Windows 10

 - GPU: GTX 770M
 - Chainloading, NA, just using GW2 Radial

**Comment by varris1** [comment]
What fixed it for me was creating an empty "config.ini" file in the addons/gw2radial folder.

**Comment by Sylarheart** [comment]
I am also having this exact problem. I didnt understand this structure thing @Friendly0Fire  posted. @varris1 can you please be more detailed about it? I tried to create a config.ini notepad in the gw2 addon folder it didnt work.

**Comment by Sylarheart** [comment]
@the-void997 have you fixed it?

**Comment by Ric-F** [comment]
Following up on what Varris1 said, create an empty file at "%programfiles%\Guild Wars 2\addons\gw2radial\config.ini" and re-start.  In many cases this will be "C:\Program Files\Guild Wars 2\addons\gw2radial\config.ini".

**Comment by Sylarheart** [comment]
> Following up on what Varris1 said, create an empty file at "%programfiles%\Guild Wars 2\addons\gw2radial\config.ini" and re-start. In many cases this will be "C:\Program Files\Guild Wars 2\addons\gw2radial\config.ini".

I tried this and didnt work. I guess it must be some instructions at the config.ini file.

**Comment by SquigglesXX** [comment]
> 

@Sylarheart make sure when you create the text file you have extensions shown and not hidden in file explorer. So when you change the .txt to .ini it changes the file type and not just the name of the text file. You should get a pop up saying changing the file extension can make the file unusable. This did work for me as well.

**Comment by CoinFlowerFish** [comment]
In case anyone is getting confused in the filepath directions given, you add the config.ini inside the gw2radial folder, inside addons. 
So a more user friendly method to explain this could be [and this is my setup: 
'THISPC>Games>Guildwars2>addons>gw2radial [in here you slot the ini file. you can create it straight from the folder and just change the .txt to .ini]
this may or may not have shed any light for anyone at all but it cant have hurt - but this resolved the issue for me as well.

**Comment by Sylarheart** [comment]
> > 
> 
> @Sylarheart make sure when you create the text file you have extensions shown and not hidden in file explorer. So when you change the .txt to .ini it changes the file type and not just the name of the text file. You should get a pop up saying changing the file extension can make the file unusable. This did work for me as well.

Thankyou, this solved.

**Comment by Sylarheart** [comment]
> In case anyone is getting confused in the filepath directions given, you add the config.ini inside the gw2radial folder, inside addons. So a more user friendly method to explain this could be [and this is my setup: 'THISPC>Games>Guildwars2>addons>gw2radial [in here you slot the ini file. you can create it straight from the folder and just change the .txt to .ini] this may or may not have shed any light for anyone at all but it cant have hurt - but this resolved the issue for me as well.

Thank you, it worked <3

**Comment by Friendly0Fire** [comment]
Anyone still having this issue (or anyone who can reproduce it easily enough), please test [this](https://github.com/Friendly0Fire/GW2Radial/suites/5115635923/artifacts/153551320) build and let me know if it fixes things. Greatly appreciate any reports!

**Comment by ItzVictini** [comment]
> 

yes, it works!

**Comment by ItzVictini** [comment]
> Anyone still having this issue (or anyone who can reproduce it easily enough), please test [this](https://github.com/Friendly0Fire/GW2Radial/suites/5115635923/artifacts/153551320) build and let me know if it fixes things. Greatly appreciate any reports!

Yes, it works!
