### ISSUE TITLE
Release archive for 2.1.2 does not contain the expected folder structure

### ISSUE THREAD

**Issue by voidburn** [Friendly0Fire/GW2Radial#272]
The zip file contains the .dll and readme files directly now, whereas 2.1.1 included both files within a "gw2radial" folder. 

Addon managers that use Loader Core (https://github.com/gw2-addon-loader/loader-core) must deploy the files in the specific path requested by it, which often means unzipping to a target location. 

While this is not a problem for manual installs, with this change the archive is unzipped by addon managers directly inside the "/addons" folder expecting its "gw2radial" folder to be created/overwritten by the process of unzipping. It will not be loaded. 

For consistency with other addons, and previous releases, I would suggest to re-introduce the "gw2radial" folder in the next ones, but to avoid disruption is probably just better to release a 2.1.3 version with the expected archive contents so it can be picked up by addon managers as a required upgrade and it will only result in an extra dangling dll in the addons folder.

Thank you.

**Comment by Friendly0Fire** [comment]
Thanks for catching it. I've updated the archive now and I'll release a new version as soon as I've fixed #271.

**Comment by voidburn** [comment]
No problem! Thanks for the great work you do :)
