### ISSUE TITLE
Could not save addon configuration. Reason given was: No such file or directory.

### ISSUE THREAD

**Issue by rl92** [Friendly0Fire/GW2Radial#273]
Hi, As the title says, I'm getting the error when trying to use the addon.

I just installed the addon via GW2 addon manager.

Thanks.

**Comment by GGiry** [comment]
I had the same issue here.

I fixed it by creating a file **config.ini** in the folder **...\Guild Wars 2\addons\gw2radial**

Until it is fixed.

**Comment by Friendly0Fire** [comment]
Duplicate of #271.

**Comment by rl92** [comment]
creating an empty config.ini file in that folder fixed it for me, sorry for the duplicate. Thanks.
