### ISSUE TITLE
Can not pull up the radial mount

### ISSUE THREAD

**Issue by JoshuaRowsom** [Friendly0Fire/GW2Radial#274]
I have installed the add-on using the manager and manually. Unfortunately, I have not gotten the popup with either installation method, and when I press SHIFT-ALT-M, the map opens up. 

**To Reproduce**
1. Do '...'
2. Then do '...'
3. Bad stuff happens

**Expected behavior**
The add-on to work.

**Screenshots**

**System configuration (please fill in):**
 - OS: Windows 11 
 - GPU: RTX 2070
 - Chainloading, none

**Additional context**
I have no other add-ons.

**Comment by Friendly0Fire** [comment]
* Have you confirmed that the addon loader is working? There should be a `gw2al_log.txt` file in the root Guild Wars 2 installation directory. If there is one, attach it.
* Have you looked for a log file? It's called `gw2radial.log` and is also found in the root GW2 installation directory. If there is one, attach it.
* Are you using D3D9 or D3D11? The addon is not compatible with DirectX 11 mode.

**Comment by JoshuaRowsom** [comment]
Oh. DX11

**Comment by Friendly0Fire** [comment]
I see. Then you can either wait for the upcoming DirectX 11 version or fall back to DirectX 9 for now.
