### ISSUE TITLE
Could not save addon configuration. Reason given was: No configuration folder could be located.

### ISSUE THREAD

**Issue by FrozenTrout** [Friendly0Fire/GW2Radial#275]
I updated to version 2.1.3, but now when I launch GW2, Radial throws the error "No configuration folder could be located". I've tried creating a "config.ini" file in GW2/addons/gw2radial/, and there's also an existing folder in ~/Documents/Guild Wars 2/addons/gw2radial/ with config files, which I have tired removing, which didn't help, and putting back, to not avail. I roll back to 2.1.2 and it works fine (aside from the "new version available" alert).

**Comment by Friendly0Fire** [comment]
First, sorry for the belated reply. From the way you type your file paths, are you using Linux? I've had to change a lot of things with the path lookups and it's possible those changes aren't very compatible with Linux since it's full of Win32 API calls.

**Comment by FrozenTrout** [comment]
No worries! And no, this is on Windows 10 (the path habits are from a history of macOS use)

**Comment by Friendly0Fire** [comment]
If you can join the GW2 Dev Community Discord server (https://discord.gg/K47yhGxD), I'd be able to drop you a build tomorrow with additional debug options and iterate quickly on the problem.
