### ISSUE TITLE
The "Shift+Alt+M" pop-up menu doesn't open

### ISSUE THREAD

**Issue by ChaosInMyBody** [Friendly0Fire/GW2Radial#276]
**Describe the bug**
Instead of the "Shift+Alt+M" menu popping up, the action bound to the "M" key (mounting) happens (I've tried unbinding the "M" key, to no avail). I went through the FAQ's and tried changing the file's location to the same folder as the Gw2.exe as well as having tried to install it using the "Gw2 Addon Manager".

**Expected behavior**
The menu to configure and rebind the radial mountwheel actions pops up.

**System configuration:**
 - OS: Windows 11
 - GPU:  GTX1070

**Comment by SparcoGreddy** [comment]
Do you have dx11 enabled? If so it does not work with that (yet)

**Comment by ChaosInMyBody** [comment]
> Do you have dx11 enabled? If so it does not work with that (yet)

I was unaware of this issue! Works now! Thank you so much!
