### ISSUE TITLE
Alt tab crashes game

### ISSUE THREAD

**Issue by Jellodaddy** [Friendly0Fire/GW2Radial#278]
**Describe the bug**
the new version of GW2 Radial works just fine until I alt-tab, which causes it to crash and tell me my shader compiler is outdated.

**To Reproduce**
1. Install GW2 Radial using Addon Manager and nothing else
2. Launch game and select character
3. Alt-tab out of game
4. Game crashes and shows error message

**Expected behavior**
I can alt tab in and out of the game without issue

**Screenshots**
![gw2radialcrash](https://user-images.githubusercontent.com/16126645/155746902-e1764a91-eccf-444e-bd3b-9c7d65df0391.PNG)

**System configuration (please fill in):**
 - OS: Windows 7
 - GPU: GTX 1050ti

**Additional context**
Tried installing the required shader compiler from online but it says it's already installed

**Comment by Friendly0Fire** [comment]
Please try the new D3D11 pre-release: https://github.com/Friendly0Fire/GW2Radial/releases/tag/v2.2.0-pre1

**Comment by Jellodaddy** [comment]
I enabled dx11 in-game and installed that version, but the game now crashes instantly after launching. Am I missing something?

**Comment by Friendly0Fire** [comment]
Hmm... It sure sounds like your computer might be missing some dependency. Do you have `.dmp` or `.log` files in your GW2 directory?

**Comment by Jellodaddy** [comment]
there's crash.dmp and gw2radial.log.

**Comment by Friendly0Fire** [comment]
To make sure they're not unrelated, delete both files then try running the game again. If they generate again, you'll want to give them to me. Probably the easiest would be to DM me the files on Discord, you can join the server here: https://discord.gg/K47yhGxD
