### ISSUE TITLE
Cant open Radial on GW2 Addon Manager

### ISSUE THREAD

**Issue by TheUnfortunatePeasant** [Friendly0Fire/GW2Radial#288]
I cant Open the GW2 addon manager. I tried reinstalling it and then downloading it manually. Still didn't work. I checked the logs and saw this but didn't know what it meant.
I really like radial and i want to have the turtle as well, so I was shocked that it didn't work. Thing is, it still worked fine yesterday

[INFO] core | Addon loader v1.0 (v1.1 r33) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading d3d9_wrapper
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[INFO] core | Loading gw2radial
[INFO] core | Loaded gw2radial v2.2 r0
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system d3d9
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system d3d11
[INFO] core | Unloading core addon
[INFO] core | Unloaded

I dont know what i should do with this info sadly.

**Comment by TheUnfortunatePeasant** [comment]
Just deleted the d3d9 and dxgi and got left with this : 

[INFO] core | Addon loader v1.0 (v1.1 r33) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading d3d9_wrapper
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[INFO] core | Loading gw2radial
[INFO] core | Loaded gw2radial v2.2 r0
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system d3d11
[INFO] core | Unloading core addon
[INFO] core | Unloaded

Kinda scared to delete the d3d9 wrapper, but maybe i should do that aswell?

**Comment by TheUnfortunatePeasant** [comment]
Okay deleted that aswell and it just says this: 

[INFO] core | Addon loader v1.0 (v1.1 r33) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading gw2radial
[WARN] core | Addon "gw2radial" is not loaded due to missing dependency "d3d9_wrapper"
[ERR] core | addons/gw2radial/gw2addon_gw2radial.dll dependency missing
[INFO] core | Done loading addons
[INFO] core | Unloading core addon
[INFO] core | Unloaded

Why does it unload my addons?

**Comment by Friendly0Fire** [comment]
You don't want to uninstall anything, the addon won't load without the D3D wrapper. Are you sure you're on the DirectX 11 beta?

**Comment by TheUnfortunatePeasant** [comment]
Shit, well let me just make a quick install  to get the files back. I dont know if im on the directX 11 Beta. Isnt the launcher DirectX 11?

**Comment by Friendly0Fire** [comment]
The DirectX 11 beta is in the graphics options in the game's in-game settings. It's not on by default.

**Comment by yoriaiko** [comment]
Side help, also had problems for launching new radial alone, few reinstalls with cleanses of main, addon, bin64, uoaom folders, not enough, till cleared settings in uoaom launcher, the bottom left button in addon launcher, then clear all, finally works. hope this helps.

**Comment by TheUnfortunatePeasant** [comment]
Okay thank you, i will check if i can turn them on. 
I also did the full clear,nothing happened. Will try the directX 11 now

**Comment by TheUnfortunatePeasant** [comment]
HAHAHHAH YES IT WORKED. Holy shit dude thank you so much. The ingame settings, thats it jesus. Thank you so much!
