### ISSUE TITLE
add notification to switch to DX11

### ISSUE THREAD

**Issue by andrei9669** [Friendly0Fire/GW2Radial#289]
**Is your feature request related to a problem? Please describe.**
When I installed the latest version I was confused at first as to why I couldn't open the menu.

**Describe the solution you'd like**
Add some sort of notification to switch to DX11 if DX9 is currently used when the user presses Shift+Alt+M

**Comment by Friendly0Fire** [comment]
The addon isn't even loaded when in DirectX 9 mode, so I can't react to events like someone pressing the keybind. I've added a mention in the addon loader's log, it's the best I can do.
