### ISSUE TITLE
Crash on Launch after switching to DX11 Beta and Installing Radial

### ISSUE THREAD

**Issue by Leyori** [Friendly0Fire/GW2Radial#290]
**Describe the bug**
After switching to the dx11 beta, and installing the Radial release, GW2 crashes on launch.

**To Reproduce**
1. Install only Radial via the Addon Manager
2. Launch GW2
3. Game crashes before character select and shows crash report message.

**Expected behavior**
I launch the game without issue.

**Screenshots**
![1328-Gw2-64_02-28-2022](https://user-images.githubusercontent.com/100600475/156013836-882d2dc3-5203-4048-88fa-0f79972d8508.png)

**System configuration (please fill in):**
 - OS: Windows 8.1
 - GPU: GTX 965M

**Additional context**
gw2al_log.txt data:
[INFO] core | Addon loader v1.0 (v1.1 r33) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading d3d9_wrapper
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[INFO] core | Loading gw2radial
[INFO] core | Loaded gw2radial v2.2 r0
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system d3d11
[INFO] d3d9_wrapper | D3D11CreateDeviceAndSwapChain failed

**Comment by Leyori** [comment]
I sent the Crash.dmp on discord.

**Comment by Friendly0Fire** [comment]
I'm tracking this with @megai2 but it doesn't seem like it'll be an easy fix unfortunately.

**Comment by Friendly0Fire** [comment]
Please try the new pre-release to assess if this is still present.

**Comment by Leyori** [comment]
Still crashed with the pre-release. It seems to be an issue with the d3d9_wrapper as it crashes with arcdps too.

**Comment by Friendly0Fire** [comment]
If the crash happens with arcdps *only* (i.e., only arcdps is installed and loaded through the addon loader), then the problem is not with this addon.

If you're still on Windows 8.1, I'd consider that to be the most likely culprit.

**Comment by Leyori** [comment]
It happens with only Radial too. It's probably an Windows 8.1 issue.

**Comment by Friendly0Fire** [comment]
Do you have any antivirus software installed beyond Windows Defender? Those can sometimes cause strange issues.

**Comment by Leyori** [comment]
I don't.

**Comment by Friendly0Fire** [comment]
Then I'm afraid I have no further solutions for you. I would heavily recommend moving on to any recent OS, seeing as 8.1 is about to be EOL.

If you do upgrade and still encounter the crash, please reopen this issue and I'll do my best to assist.
