### ISSUE TITLE
No Longer Working

### ISSUE THREAD

**Issue by Ampersammich** [Friendly0Fire/GW2Radial#292]
Simply put, the addon stopped working after I updated last night. Shift + Alt + M won't bring up the menu. My original control bind for the radial isn't pulling it up in-game, and reinstalling didn't work.

**Comment by Zyian** [comment]
The latest version only works with DX11, make sure that is enabled, otherwise make sure to install the d3d9 version available in the Addon Manager or https://github.com/gw2-addon-loader/GW2Radial/releases/tag/v2.1.4

**Comment by AstanVizu** [comment]
What is the reason to make the addon only work with an experimental feature, i.e. DX11?
Like probably half of the GW2 community, DX11 is not working well for me and I'm not going to use it.
