### ISSUE TITLE
Manual installation instructions not being clear enough

### ISSUE THREAD

**Issue by nakami** [Friendly0Fire/GW2Radial#293]
> README.md:
> Manual Installation
>  -  Install the [addon loader](https://github.com/gw2-addon-loader/loader-core) and [d3d wrapper](https://github.com/gw2-addon-loader/d3d9_wrapper).

Well, how do install those? Neither of those repos have instructions and there isn't any instructions here either.

**Comment by nakami** [comment]
addon loader:
- put its zip's content (bin64, addonLoader.dll, d3d11.dll, dxgi.dll) in the gw2 installation directory

d3d wrapper
- put its zip's content (folder named "d3d9_wrapper") under addons

**Comment by Friendly0Fire** [comment]
As much as I understand your request, I really prefer referring to their respective Github pages for installation instructions so that if anything were to change, my own instructions wouldn't become outdated.

I'll see if I can get updated instructions posted on both addon repos.

**Comment by nakami** [comment]
Pull requests:

- loader-core: https://github.com/gw2-addon-loader/loader-core/pull/5
- d3d9_wrapper: https://github.com/gw2-addon-loader/d3d9_wrapper/pull/2

**Comment by Friendly0Fire** [comment]
Thank you so much, all merged!

**Comment by nakami** [comment]
Thank you for your time on gw2radial!
