### ISSUE TITLE
High DPI / Scaling issue

### ISSUE THREAD

**Issue by FuriousProgrammer** [Friendly0Fire/GW2Radial#294]
Running on a Surface Pro 4, 2736x1824 with 200% scaling in Windows.

Gw2-64.exe has high-dpi setting set to allow the application to control it, and the game's UI respects the in-game high-dpi tick box. This bug occurs no matter what the Windows high-dpi application settings is actually set to.

Game is running fullscreen at 1024x768 resolution.

GW2Radial is displaying at double the size, but the controls are not also being scaled, making the UI nearly unusable:

![image](https://user-images.githubusercontent.com/8884729/156077432-6ea0e1bc-1cf4-4510-bf2c-520b4716a8de.png)

I'd show the radial menus as well, but hassling with the config with the broken scaling is too much to handle.

**Comment by AdarkTheCoder** [comment]
Managed to assign my keybinds by copying someone elses' config and I can confirm that the radial menu itself is doing the exact same thing : inputs work based on real mouse position, visuals are doubled (both in size and position from top-left corner)

**Comment by Friendly0Fire** [comment]
Yeah, I can replicate the issue as well, it's on my list.

**Comment by Friendly0Fire** [comment]
I believe this is fixed in the next version, but let me know if you encounter it again.
