### ISSUE TITLE
Cna't get skiff to work

### ISSUE THREAD

**Issue by barcelosluan** [Friendly0Fire/GW2Radial#296]
Skiff, just like fishing, is under "mastery" skills, and actualy needs to be deployed at water. There is no hotkey to bind at game options, and only biding at GW2Radial didn't work at all.

**Comment by Friendly0Fire** [comment]
I implemented the skiff before the expansion came out. Quite obviously, there are no skiff hotkeys in the game. Nothing I can fix.
