### ISSUE TITLE
Unable to open the GW2Radial Menu

### ISSUE THREAD

**Issue by Critshappen** [Friendly0Fire/GW2Radial#297]
**Describe the bug**
Unable to open the GW2Radial Menu with Shift+Alt+M.

**To Reproduce**
1. Install GW2Radial (DX11 version) with the GW2 Addon Manager (DX11 beta is checked in the in-game settings)
2. Launch game
3. Unable to open the GW2Radial menu with Shift+Alt+M.

**Expected behavior**
To be able to open the GW2Radial Menu with Shift+Alt+M.

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: GTX 1080
 - DX11 Beta
 
**Additional context**
After making the change from D912PXY installed via. GW2 Addon manager to DX11 Beta, I have been unable to open the GW2Radial Menu with Shift+Alt+M.

When going back to DX9 (Uncheck D11 Beta in the in-game settings, installing the DX9 variant of GW2Radial and reinstalling D912PXY in the GW2 Addon Manager) the menu is able to be opened again with Shift+Alt+M.

**Attachments**
[gw2al_log.txt](https://github.com/Friendly0Fire/GW2Radial/files/8158745/gw2al_log.txt)

**Comment by Friendly0Fire** [comment]
Is there a gw2radial.log file?

**Comment by Critshappen** [comment]
[gw2radial.log](https://github.com/Friendly0Fire/GW2Radial/files/8159000/gw2radial.log)

**Comment by Critshappen** [comment]
When running DX11, there are no config.ini file being generated "G:\Guild Wars 2\addons\gw2radial" (If there should be)
When running DX9, the config file in "G:\Guild Wars 2\addons\gw2radial" gets generated.

**Comment by Friendly0Fire** [comment]
This is really weird, the log seems to indicate the addon just isn't being loaded at all... I'll make a version with a lot more logging to see if we can pinpoint the issue and I'll upload it here when it's ready.

**Comment by RockyGateway** [comment]
This is happening for me as well, except I can at least open the options with Shift + Alt + M. The actual radial menu will not work, though, and after pressing the button I have it bound to I can no longer move the camera with my mouse until I reset the game.

[gw2radial.log](https://github.com/Friendly0Fire/GW2Radial/files/8163500/gw2radial.log)

**Comment by Silentsword45** [comment]
For me, I use Gw2-UAOM and when updated to radial 2.2, it stopped working with D912pxy. but when I uninstalled 2.2 and switched to the D3D9 version of radial (which i believe is new), radial worked with D912pxy again.

**Comment by Friendly0Fire** [comment]
> This is happening for me as well, except I can at least open the options with Shift + Alt + M. The actual radial menu will not work, though, and after pressing the button I have it bound to I can no longer move the camera with my mouse until I reset the game.
> 
> [gw2radial.log](https://github.com/Friendly0Fire/GW2Radial/files/8163500/gw2radial.log)

Please open a separate issue, seeing as your problem is completely different.

**Comment by Friendly0Fire** [comment]
Please try the new pre-release to assess if this is still present.
