### ISSUE TITLE
Update on ReadMe for those who want to manually add ArcDPS with GW2Radial Mount on D3D11

### ISSUE THREAD

**Issue by Zien4** [Friendly0Fire/GW2Radial#299]
**Is your feature request related to a problem? Please describe.**

✅ Working for D3D11
This is for those who want to manually update ArcDPS with GW2Radial Mount on D3D11. I don't know where your gonna put it. But I guess where **Manual Installation** is good. 

------------------------------------------------------------------------
**Describe the solution you'd like**
To Update ArcDps,
1. Download the latest here -- https://www.deltaconnected.com/arcdps/x64/
2. Save d3d9.dll into **_Guild Wars 2\addons\arcdps_** and rename to _**gw2addon_arcdps.dll**_ lastly replace/overwritten the file.
3. Thats it!
------------------------------------------------------------------------
**Describe alternatives you've considered**

[❌](https://emojipedia.org/cross-mark/) replace **d3d11.dll** with updated arcdps.dll **With** [addon loader](https://github.com/gw2-addon-loader/loader-core) and [d3d wrapper](https://github.com/gw2-addon-loader/d3d9_wrapper) installed.
[❌](https://emojipedia.org/cross-mark/) replace and rename **d3d9.dll** to **dxgi.dll** with updated arcdps.dll [addon loader](https://github.com/gw2-addon-loader/loader-core) and [d3d wrapper](https://github.com/gw2-addon-loader/d3d9_wrapper) installed.

------------------------------------------------------------------------
**Additional context**
N/A

**Comment by jimmoua1** [comment]
Needed more testing
