### ISSUE TITLE
Game crashes (probably d3d9_wrapper issue) 

### ISSUE THREAD

**Issue by glupiaczacza** [Friendly0Fire/GW2Radial#305]
**Describe the bug**
I wanted to install the newest gw2radial version, but I didn't remember how I did it the last time, so I uninstalled the game entirely and installed it again. From fresh I installed the "addon loader" and then "d3d wrapper". Both as in their respective instructions (d3d wrapper - by coping the "d3d9_wrapper" folder with its content into the "addons" folder within the game folder, but I also tried to copy the contents of "d3d9_wrapper" folder into the "addons" folder directly).
And then when I try to start the game, I'm able to log in, but then it crashes after pressing start button. If I delete the d3d wrapper files, the game starts normally - but the gw2radial does not work.
Radial log:
[INFO] core | Addon loader v1.0 (v1.1 r33) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading d3d9_wrapper
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[INFO] core | Loading gw2radial
[INFO] core | Loaded gw2radial v2.2 r1
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system d3d11
[INFO] d3d9_wrapper | D3D11CreateDeviceAndSwapChain failed

**To Reproduce**
1. Install the game from scratch
2. Then install addon loader
3. Then d3d wrapper
4. Then radial (manually)
5. Try turning on the game
6. Error, game does not open

**Expected behavior**
Game loading and the gw2radial with the newest options (turtle etc) working.

**Screenshots**
-

**System configuration (please fill in):**
 - OS: Windows 8.1
 - GPU: Inter core i7-5500U @ 2.40 GHz
 - Chainloading, -

**Additional context**
I am not well versed in programming nor software stuff, so I decided to ask here for help - I hope it is okay.

**Comment by glupiaczacza** [comment]
Additional info:
when I turned off the D11 in the game options, the game loaded with the wrapper installed. But the GW2radial does not work, the log says:
[INFO] core | Addon loader v1.0 (v1.1 r33) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading d3d9_wrapper
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[INFO] core | Loading gw2radial
[INFO] core | Loaded gw2radial v2.2 r1
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system d3d9
[WARN] gw2radial | Addon unable to load in D3D9 mode, activate D3D11 in game options to enable!

I checked and the DirectX 11 is installed on my computer.

**Comment by Friendly0Fire** [comment]
Please try the new pre-release to assess if this is still present.
