### ISSUE TITLE
Radial addon didnt appear

### ISSUE THREAD

**Issue by TagashiChiro** [Friendly0Fire/GW2Radial#307]
The below is the  gw2_al.log 

[INFO] core | Addon loader v1.0 (v1.1 r33) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading arcdps
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[INFO] core | Loaded arcdps v1.0 r415
[INFO] core | Loading d3d9_wrapper
[INFO] core | Loading gw2radial
[INFO] core | Loaded gw2radial v2.2 r1
[INFO] core | Loading gw2radial_d3d9
[INFO] core | Loaded gw2radial_d3d9 v2.1 r4
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system d3d11
[INFO] core | Unloading core addon
[INFO] core | Unloaded

**Comment by Friendly0Fire** [comment]
You're using the D3D9 version and the D3D11 version at the same time, please stick to just one.

**Comment by TagashiChiro** [comment]
Ok. After clean uninstall and reinstalling arcdps and radial mount for d3d11, it still doesn't work. 

[INFO] core | Addon loader v1.0 (v1.1 r33) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading arcdps
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[INFO] core | Loaded arcdps v1.0 r425
[INFO] core | Loading d3d9_wrapper
[INFO] core | Loading gw2radial
[INFO] core | Loaded gw2radial v2.2 r1
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system d3d11

**Comment by Friendly0Fire** [comment]
Closing, following in #320.
