### ISSUE TITLE
Unhandled Exception in GW2 Process, Custom Radial Menus

### ISSUE THREAD

**Issue by dchase94** [Friendly0Fire/GW2Radial#308]
**Describe the bug**
Game crashes upon start when any custom radial menu is added to the addon folder, /Guild Wars 2/addons/gw2radial_d3d9/custom/<custom name>

**To Reproduce**
1. Place a folder in /Guild Wars 2/addons/gw2radial_d3d9/custom/<custom name>, with a config.ini file present in it.
2. Start the Guild Wars 2 executable.
3. "Intercepted Unhandled exception in GW2 Process" and game closes on confirmation of this dialogue box.

**Expected behavior**
Expected GW2 to run and have access to a custom radial menu.

**Screenshots/Logs**
Information from gw2al_log:

[INFO] core | Addon loader v1.0 (v1.1 r33) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading arcdps
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[INFO] core | Loaded arcdps v1.0 r415
[INFO] core | Loading d3d9_wrapper
[INFO] core | Loading d912pxy
[INFO] core | Loaded d912pxy v2.4 r703
[INFO] core | Loading gw2radial_d3d9
[INFO] core | Loaded gw2radial_d3d9 v2.1 r4
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system d3d11
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading custom lib from D3D_wrapper_custom_d3d9_lib_query
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi
[INFO] core | Unloading core addon
[INFO] core | Unloaded

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: RTX 2070 Super
 - Multiple addons through GW2 Addon Loader, I don't think this counts as chainloading?

**Additional context**
I am using the d3d9 version of GW2Radial, is the custom menu addition only available/working on the current (dx11) version?

**Comment by Friendly0Fire** [comment]
Custom menus should work in both versions, but I will not be supporting the D3D9 version anymore. If this still occurs in the D3D11 version, please provide `gw2radial.log` and any `.dmp` file so I can diagnose.
