### ISSUE TITLE
Cannot mount under water with mod. Can mount under water without it.

### ISSUE THREAD

**Issue by speedyconzales** [Friendly0Fire/GW2Radial#310]
this is easy. Title says it all.

**Comment by Friendly0Fire** [comment]
Please give actual details, configuration, other addons installed, etc.

**Comment by speedyconzales** [comment]
Try it yourself! This does not need anymore information. Try to use the wheel while under water to mount your skimmer. It doesn’t work. If you don’t use the wheel, you can mount under water. The add-on thinks that the player is not allowed to mount under water and is waiting for the player to reach the surface. But you can mount the skimmer under water. That‘s it!
