### ISSUE TITLE
Enable underwater skimmer always enabled

### ISSUE THREAD

**Issue by BobotheHutt** [Friendly0Fire/GW2Radial#311]
**Describe the bug**
Enable underwater Skimmer is always enabled, checked or not.  This prevents me from ever using radial mount for the skiff since it will instantly go to skimmer

**To Reproduce**
check it and see its enabled.  uncheck and it is acts as if its enabled.

**Expected behavior**
unchecked, radial wheel should appear to allow picking any mount or the skiff

**System configuration:**
 - OS: Windows 10
 - GPU:  GTX3080

**Comment by Friendly0Fire** [comment]
This is fixed in the next version.
