### ISSUE TITLE
Radial does not allow turtle to be used underwater

### ISSUE THREAD

**Issue by voidbeast** [Friendly0Fire/GW2Radial#312]
**Describe the bug**
The Siege Turtle mount is able to be used underwater but GW2Radial does not seem to be aware of this and just gives the timer as if it is waiting for you to get onto land to activate the turtle.

**To Reproduce**
Swim down underwater, open the radial menu and try to mount the siege turtle.

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: RTX 2060
 - Chainloading: I'm not really sure what this means, but if it is about other addons, I have TacO and ArcDPS installed also, the latter installed using the Unofficial Guild Wars 2 Addon Manager.

**Additional context**
I didn't even know the turtle could be used underwater myself until I saw someone else doing just that, so it's totally understandable if this were just an oversight from being unaware of it. Just figured I'd let someone know here in case you were in the same boat as me and didn't even know this was possible. =)

Also, I do NOT have the underwater skimmer mastery, and therefore do not have that option enabled in the GW2Radial settings. I do not know if this has any effect on it or if it would cause any conflict. Unlike the skimmer, the turtle does not need any mastery to be used underwater.

**Comment by Friendly0Fire** [comment]
This is fixed in the next version.
