### ISSUE TITLE
No Overlay/Keybind Option In Menu

### ISSUE THREAD

**Issue by Eguzky** [Friendly0Fire/GW2Radial#313]
I installed both Radial Mount addons from the addon manager. When going into my options; there is no overlay toggle option.

**To Reproduce**
1. Install either or both radial mount addons.
2. Go into keybinds on a character
3. There is no option for the radial mount. Thus, no keybind can be set

**Expected behavior**
Expected a keybind in the keys menu.

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: GTX 1070
 - No chainloading. Just either radial mounts mod.

**Comment by Zyian** [comment]
Double check the usage instructions:

https://github.com/Friendly0Fire/GW2Radial#usage=

Most of the configuration happens in the Radial menu under `Shift+Ctrl+M`

You need to **copy** the keybinds you set in-game to Radial

**Comment by Eguzky** [comment]
Apologies! I missed that. I have it up and working now. Though it's shit+alt+m
