### ISSUE TITLE
The addon won't load v2.2 r1

### ISSUE THREAD

**Issue by Patchupp** [Friendly0Fire/GW2Radial#314]
**The Radial won't load**
I used the GW2-UOAOM to install the Radial addon, using the link on your page.
I ran the Manager and picked GW2 Radial (v2.2.1)
There is another option on the installer but that is version D3D9.
I have no clue where this D3D11 version is. I assumed the Addon Manager would get it, per your instructions.
Thank you for your assistance.

Here is my gw2al_log
[INFO] core | Addon loader v1.0 (v1.1 r33) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading d3d9_wrapper
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[INFO] core | Loading gw2radial
[INFO] core | Loaded gw2radial v2.2 r1
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system d3d11
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system d3d9
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] gw2radial | Addon unable to load in D3D9 mode, activate D3D11 in game options to enable!

**Comment by Friendly0Fire** [comment]
It says to activate D3D11 in the game options. Did you do that?

**Comment by Patchupp** [comment]
That worked. Thank you!
You might want to add this step in the Automatic installation instructions, for those of us that are not fully enmeshed in how these things work.
Thanks again.
