### ISSUE TITLE
missing gw2addon_sct

### ISSUE THREAD

**Issue by enramot** [Friendly0Fire/GW2Radial#316]
Nothing happens when i press the keybind.

OS: Windows 11
GPU:  RTX 3080

This is waht my gw2al_log.txt says:
[INFO] core | Addon loader v1.0 (v1.1 r33) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading arcdps
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[INFO] core | Loaded arcdps v1.0 r432
[INFO] core | Loading d3d9_wrapper
[INFO] core | Loading d912pxy
[INFO] core | Loaded d912pxy v2.4 r703
[INFO] core | Loading gw2radial
[INFO] core | Loaded gw2radial v2.2 r1
[INFO] core | Loading gw2radial_d3d9
[INFO] core | Loaded gw2radial_d3d9 v2.1 r4
[INFO] core | Loading sct
[ERR] core | addons/sct/gw2addon_sct.dll not found
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system d3d11
[INFO] core | Unloading core addon
[INFO] core | Unloaded

**Comment by Friendly0Fire** [comment]
This isn't a GW2Radial issue.
