### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by edwloef** [Friendly0Fire/GW2Radial#318]
I installed ArcDPS as well as the Boon Table using Addon Manager, and the game worked fine. Once Radial Mount Menu was added the game crashed in the character selection screen. gw2radial.log is empty, however the mod is being loaded:
[gw2al_log.txt](https://github.com/Friendly0Fire/GW2Radial/files/8837330/gw2al_log.txt)

**To Reproduce**
Install ArcDPS and Radial Mount Menu from Addon Manager and launch the game.

**Expected behavior**
No crash in the character selection screen.

**System configuration (please fill in):**
 - OS: Arch Linux with Wine 7.7
 - GPU: GTX 950M
 - Chainloading: arcdps -> GW2Radial

**Additional context**
dx11 rendering is being used, and the dx11 version of gw2radial, as well as arcdps, was installed.

**Comment by Friendly0Fire** [comment]
Sorry, I've already said in the past that I can't support Linux, it's too many different configurations and layers and I have no way to debug it.
