### ISSUE TITLE
Suggestion: Default Surface Mount Choice (for Skiffs)

### ISSUE THREAD

**Issue by MorickClive** [Friendly0Fire/GW2Radial#321]
## Suggestion:
Guildwars has finally added in Skiff mapping.

Gameplay shows that mechanically `Skiffs` only deploy on surface, however,  this clashes with the `auto-skimmer` feature; having a default-mount(choice) assigned to surface deploy would be preferable, this would allow us to set Skiff instead of Skimmer.

### Alts:
- There is the possibility that players might want `control of their mount wheel on surface` rather than a default for future iterations, perhaps this can be an alternative option to disable the the auto feature to re-enable player control for unforeseen feature updates .

**Comment by Friendly0Fire** [comment]
This is fixed in the next version.
