### ISSUE TITLE
Suggestion Jade Bot Waypoint and Fishing Options

### ISSUE THREAD

**Issue by Draakkon-Brightweave** [Friendly0Fire/GW2Radial#322]
I would like Jad Bot Waypoint and Start Fishing added to the Novelties Menu (Along side the chairs/interments/tonics). Seeing all of the mastery skills have their own key bind options like mounts

![image](https://user-images.githubusercontent.com/109103870/178332692-c4e9ece9-086f-4dc5-b1e5-c92ce14d8d6f.png)

**Comment by Friendly0Fire** [comment]
Both are added in the next version.
