### ISSUE TITLE
crash when launching game with addons radial menu

### ISSUE THREAD

**Issue by spn1998vn** [Friendly0Fire/GW2Radial#323]
**Describe the bug**
i dont know what wrong but when i open the game it just give me Gw2-64.exe didnt even get in to the launcher when i uninstall radial menu i can go in game normal

**To Reproduce**
1. install auto or manual
3. Then open the game
4. And it just crash

**Screenshots**
![image](https://user-images.githubusercontent.com/109958294/180759736-c983cb87-5d6b-4f46-9527-b167f978fb82.png)

**System configuration (please fill in):**
 - OS: Windows 11
 - GPU: GTX 2070
 
**Additional context**
*--> Crash <--*
Assertion: Failed to load Coherent DLL. Error code: 0x7e 
File: D:\Perforce\Live\NAEU\v2\Code\Arena\Engine\ArenaWeb\CoherentUi\AwCoh.cpp(58)
App: Gw2-64.exe 
Pid: 10156
BaseAddr: 00007FF7CB1C0000
ProgramId: 101
Build: 131907
When: 2022-07-25T10:39:47Z 2022-07-25T17:39:47+07:00
Uptime:   0 days  0:00:03
Flags: 0
DumpFile: Crash.dmp

*--> System <--*
Name: 1196cca7
IpAddr: 192.168.55.112
Processors: 12 [GenuineIntel:6:13:1]
OSVersion: Windows 10.0 (64 bit)

*--> System Memory <--*
Physical: 11272MB/16147MB  69%
Paged:    12690MB/19091MB  66%
Virtual:  134213272MB/134217727MB  3%
Load: 30%
CommitTotal:   6400MB
CommitLimit:  19091MB
CommitPeak:    7945MB
SystemCache:   2546MB
HandleCount:  76011
ProcessCount:   200
ThreadCount:   2397

*--> Process Memory <--*
Private:          120MB
WorkingSet:       111MB
PeakWorkingSet:   249MB
PageFaults:    270247

*--> Memory Category Usage (Inclusive) <--*
[Category]              [Size(MB)]  [Count]     
Root                    88.89       6169        
Uncategorized           47.17       4531        
Programmer Data         35.27       883         
I/O                     34.74       571         
Archive                 33.40       25          
Collide                 6.45        755         
Collide Havok           6.45        755         
File Service            1.24        12          
Collections             0.26        75          
Dictionary              0.25        43          
Networking              0.11        14          
Asset Service           0.10        529         
Event                   0.07        3           
Game                    0.05        56          
Content                 0.02        1           
Engine                  0.02        12          
Threading               0.01        14          
Model-Programmer        0.01        1           
Install                 0.00        30          
BTree                   0.00        6           
Platform                0.00        65          
CharClient              0.00        5           
Services                0.00        8           
File Core               0.00        2           

*--> Memory Category Usage (Exclusive) <--*
[Category]              [Size(MB)]  [Count]     
Uncategorized           47.17       4531        
Archive                 33.40       25          
Collide Havok           6.45        755         
File Service            1.24        12          
Dictionary              0.25        43          
Networking              0.11        9           
Asset Service           0.10        529         
Event                   0.07        3           
Game                    0.03        46          
Content                 0.02        1           
Threading               0.01        14          
Model-Programmer        0.01        1           
Collections             0.01        25          
Engine                  0.01        6           
Install                 0.00        30          
BTree                   0.00        6           
Platform                0.00        65          
CharClient              0.00        5           
Services                0.00        8           
File Core               0.00        2           
Text                    0.00        1           
Download                0.00        3           
UI                      0.00        14          
Programmer Data         0.00        2           

*--> DllList <--*
00007FF7CB1C0000 - D:\Guild Wars 2\Gw2-64.exe
00007FFBF3A20000 - C:\WINDOWS\SYSTEM32\ntdll.dll
00007FFBF1A80000 - C:\WINDOWS\System32\KERNEL32.DLL
00007FFBF0F00000 - C:\WINDOWS\System32\KERNELBASE.dll
00007FFBF1B40000 - C:\WINDOWS\System32\USER32.dll
00007FFBF1600000 - C:\WINDOWS\System32\win32u.dll
00007FFBF2FC0000 - C:\WINDOWS\System32\GDI32.dll
00007FFBF16F0000 - C:\WINDOWS\System32\gdi32full.dll
00007FFBF1810000 - C:\WINDOWS\System32\msvcp_win.dll
00007FFBF1460000 - C:\WINDOWS\System32\ucrtbase.dll
00007FFBF1EB0000 - C:\WINDOWS\System32\ADVAPI32.dll
00007FFBF3090000 - C:\WINDOWS\System32\msvcrt.dll
00007FFBF1CF0000 - C:\WINDOWS\System32\sechost.dll
00007FFBF3840000 - C:\WINDOWS\System32\RPCRT4.dll
00007FFBF3960000 - C:\WINDOWS\System32\WS2_32.dll
00007FFBF13F0000 - C:\WINDOWS\System32\WINTRUST.dll
00007FFBF2F10000 - C:\WINDOWS\System32\PSAPI.DLL
00007FFBE78D0000 - C:\WINDOWS\SYSTEM32\VERSION.dll
00007FFBF3550000 - C:\WINDOWS\System32\ole32.dll
00007FFBEA0D0000 - C:\WINDOWS\SYSTEM32\WTSAPI32.dll
00007FFBE8680000 - C:\WINDOWS\SYSTEM32\WINMM.dll
00007FFBF1F60000 - C:\WINDOWS\System32\combase.dll
00007FFBF36F0000 - C:\WINDOWS\System32\OLEAUT32.dll
00007FFBF22E0000 - C:\WINDOWS\System32\SHELL32.dll
00007FFBD6990000 - C:\WINDOWS\SYSTEM32\MSACM32.dll
00007FFBD6BE0000 - C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.22000.675_none_ce846f9a12fab040\gdiplus.dll
00007FFBF1280000 - C:\WINDOWS\System32\CRYPT32.dll
00007FFBCFBC0000 - C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22000.1_none_271a8fad6a2d1b1e\COMCTL32.dll
00007FFBDB140000 - C:\WINDOWS\SYSTEM32\MSIMG32.dll
00007FFBDB020000 - C:\WINDOWS\SYSTEM32\Secur32.dll
00007FFBE1220000 - C:\WINDOWS\SYSTEM32\USP10.dll
00007FFBF0760000 - C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
00007FFBF0310000 - C:\WINDOWS\SYSTEM32\SSPICLI.DLL
00007FFBF33C0000 - C:\WINDOWS\System32\IMM32.DLL
00007FFBF07C0000 - C:\WINDOWS\SYSTEM32\MSASN1.dll
00007FFBF1580000 - C:\WINDOWS\System32\bcryptPrimitives.dll
00007FFBEE910000 - C:\WINDOWS\SYSTEM32\dbghelp.dll
00007FFBEF080000 - C:\WINDOWS\SYSTEM32\windows.storage.dll
00007FFBEEF10000 - C:\WINDOWS\SYSTEM32\wintypes.dll
00007FFBF3160000 - C:\WINDOWS\System32\SHCORE.dll
00007FFBF3300000 - C:\WINDOWS\System32\shlwapi.dll
00007FFBF0E30000 - C:\WINDOWS\SYSTEM32\profapi.dll
00007FFBF00F0000 - C:\WINDOWS\SYSTEM32\kernel.appcore.dll
00007FFBF0C20000 - C:\WINDOWS\SYSTEM32\DEVOBJ.dll
00007FFBF0BD0000 - C:\WINDOWS\SYSTEM32\cfgmgr32.dll
00007FFBEE270000 - C:\WINDOWS\SYSTEM32\dxcore.dll
00007FFBEB940000 - C:\WINDOWS\system32\uxtheme.dll
00007FFBE7890000 - C:\WINDOWS\SYSTEM32\cryptnet.dll
00007FFBF2FA0000 - C:\WINDOWS\System32\imagehlp.dll
00007FFBF0770000 - C:\WINDOWS\SYSTEM32\CRYPTSP.dll
00007FFBF0050000 - C:\WINDOWS\system32\rsaenh.dll
00007FFBF08E0000 - C:\WINDOWS\SYSTEM32\bcrypt.dll
00007FFBF3250000 - C:\WINDOWS\System32\clbcatq.dll
00007FFBEE510000 - C:\WINDOWS\SYSTEM32\ntmarta.dll
00007FFBD4BA0000 - C:\WINDOWS\system32\napinsp.dll
00007FFBCE890000 - C:\WINDOWS\system32\pnrpnsp.dll
00007FFBF0520000 - C:\WINDOWS\System32\mswsock.dll
00007FFBEFC90000 - C:\WINDOWS\SYSTEM32\DNSAPI.dll
00007FFBEFC20000 - C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
00007FFBF3080000 - C:\WINDOWS\System32\NSI.dll
00007FFBBF810000 - C:\WINDOWS\System32\winrnr.dll
00007FFBE7570000 - C:\WINDOWS\system32\wshbth.dll
00007FFBD69B0000 - C:\WINDOWS\system32\nlansp_c.dll
00007FFBE74E0000 - C:\WINDOWS\System32\fwpuclnt.dll
00007FFBE6E10000 - C:\Windows\System32\rasadhlp.dll
00007FFBF1D90000 - C:\WINDOWS\System32\msctf.dll
00007FFBCF5E0000 - C:\WINDOWS\SYSTEM32\textinputframework.dll
00007FFBE5060000 - C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
00007FFBC0120000 - C:\WINDOWS\system32\explorerframe.dll
00007FFBC1FE0000 - C:\WINDOWS\SYSTEM32\TextShaping.dll

*--> Game Context <--*
MapId: 0
Flags: 0x241
ElapsedTime: 00:00:01

*--> World State <--*
<WorldState />

[DbgHelp.dll is C:\WINDOWS\SYSTEM32\dbghelp.dll]
[DbgHelp.dll version 10.0.22000.1 (64/32-bit compatible)]

*--> ClientContextThreadProc Thread 0x23c4 <--*

*--> Trace <--*
Pc                Rt                : Args
00007ff7`cb299285 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`cbcc154d 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`cb634185 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`cb632f73 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`cb580b90 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`cb57fcb9 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`cb275dc6 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`cb275adf 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`cb4e1bc9 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`cb4dffa0 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`cb4dfc28 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`cb4e0fa7 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`cb4e1076 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`cb4df3a5 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`cb28f43d 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`cb49c000 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffb`f1a954e0 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffb`f3a2485b 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 

*--> Thread registers <--*
rax=0000000000000001 rbx=00007ff7ccc921e0 rcx=0000005b4e7fe480
rdx=0000000000000200 rsi=00000234d9351a40 rdi=000000000000003a
rip=00007ff7cb299221 rsp=0000005b4e7fe420 rbp=0000005b4e7fecd0
 r8=000000000000002d  r9=00007ff7cb1c0000 r10=0000000000000008
r11=0000005b4e7fe97b r12=0000000000000002 r13=0000000000000002
r14=00000234d7f3d1e0 r15=0000000000000000
cs=0033 ss=002b ds=002b es=002b fs=0053 gs=002b efl=00000202

rbx-32 00007FF7CCC921C0  65686f43`5c626557 415c7447`746e6572 00707063`2e744777 00000000`00000000 
rbx +0 00007FF7CCC921E0  6f667265`505c3a44 6576694c`5c656372 32765c55`45414e5c 72415c65`646f435c 
rbx+32 00007FF7CCC92200  69676e45`5c616e65 616e6572`415c656e 65686f43`5c626557 415c6955`746e6572 
rcx-32 0000005B4E7FE460  0000005b`4e7feb98 00007ff7`cb299221 0000005b`4e7fe420 0000005b`4e7fecd0 
rcx +0 0000005B4E7FE480  00000234`d7f1b580 00000234`d7f42800 00000000`a9c7b88a 00000000`00000000 
rcx+32 0000005B4E7FE4A0  00000000`7ffe0384 00000000`7ffe0385 00009f80`0010000f 0053002b`002b0033 
 r9 +0 00007FF7CB1C0000  00000003`00905a4d 0000ffff`00000004 00000000`000000b8 00000000`00000040 
 r9+32 00007FF7CB1C0020  00000000`00000000 00000000`00000000 00000000`00000000 00000188`00000000 

*--> Code <--*
00007ff7`cb299201  8d4c2440 e8363cfe ff488d0d 0fa81302 .L$@.6<..H......
00007ff7`cb299211  e8aa6bfe ff488d4c 2460ff15 07814f01 ..k..H.L$`....O.
00007ff7`cb299221  488b8424 58010000 4c8d05e0 b2500148 H..$X...L....P.H
00007ff7`cb299231  89442448 488d9424 30050000 488b8424 .D$HH..$0...H..$
00007ff7`cb299241  f8000000 4885db48 89442450 448bcf48 ....H..H.D$PD..H
00007ff7`cb299251  8b842400 0100004c 0f45c348 89442458 ..$....L.E.H.D$X

*--> Stack <--*
0000005b`4e7fe420  00007ff7`ccc921e0 00000000`00000000 00000000`000d000c 00007ffb`86bf722a .!......................*r......
0000005b`4e7fe440  0000005b`4e7fe468 0000005b`4e7fe480 00000000`00000000 00000234`d7f42848 h..N[......N[...........H(..4...
0000005b`4e7fe460  0000005b`4e7feb98 00007ff7`cb299221 0000005b`4e7fe420 0000005b`4e7fecd0 ...N[...!.)..... ..N[......N[...
0000005b`4e7fe480  00000234`d7f1b580 00000234`d7f42800 00000000`a9c7b88a 00000000`00000000 ....4....(..4...................
0000005b`4e7fe4a0  00000000`7ffe0384 00000000`7ffe0385 00009f80`0010000f 0053002b`002b0033 ........................3.+.+.S.
0000005b`4e7fe4c0  00000202`002b002b 00007ffb`f3a701f6 00000000`00000000 0000005b`4e7fe620 +.+..................... ..N[...
0000005b`4e7fe4e0  00000000`00000000 00133000`57503cc5 0000005b`00000010 00000000`00000001 .........<PW.0......[...........
0000005b`4e7fe500  0000005b`4e7fe480 00000000`00000200 00007ff7`ccc921e0 0000005b`4e7fe420 ...N[............!...... ..N[...
0000005b`4e7fe520  0000005b`4e7fecd0 00000234`d9351a40 00000000`0000003a 00000000`0000002d ...N[...@.5.4...:.......-.......
0000005b`4e7fe540  00007ff7`cb1c0000 00000000`00000008 0000005b`4e7fe97b 00000000`00000002 ................{..N[...........
0000005b`4e7fe560  00000000`00000002 00000234`d7f3d1e0 00000000`00000000 00007ff7`cb299221 ............4...........!.).....
0000005b`4e7fe580  00000000`0000027f 00000000`00000000 00000000`00000000 0000ffff`00009f80 ................................
0000005b`4e7fe5a0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000005b`4e7fe5c0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000005b`4e7fe5e0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000005b`4e7fe600  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000005b`4e7fe620  00007ff7`cd2b5fc0 00000234`d594e7d0 746e6572`65686f43 6c6c642e`34364955 ._+.........4...CoherentUI64.dll
0000005b`4e7fe640  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000005b`4e7fe660  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000005b`4e7fe680  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000005b`4e7fe6a0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000005b`4e7fe6c0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000005b`4e7fe6e0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000005b`4e7fe700  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000005b`4e7fe720  00000000`00000100 00000234`d5940150 00000000`00000001 00000000`7ffe0380 ........P...4...................
0000005b`4e7fe740  00000000`00000029 00007ffb`f3a420fa 00000234`d59402e8 00000234`d932e8d0 )........ ..........4.....2.4...
0000005b`4e7fe760  00000234`d5940000 00000000`00000029 00000000`00000100 00000234`d932e8d0 ....4...).................2.4...
0000005b`4e7fe780  00000000`00000080 00007ffb`f3a464b1 00000234`d5940000 00000234`d932e8d0 .........d..........4.....2.4...
0000005b`4e7fe7a0  00000234`d932e8c0 0000005b`4e7fe960 0000005b`00000029 00000000`00000029 ..2.4...`..N[...)...[...).......
0000005b`4e7fe7c0  00007ffb`f3b510f8 0000005b`0000052e 00000000`4e7fea01 0000005b`4e7f0048 ............[......N....H..N[...
0000005b`4e7fe7e0  00007ffb`f3b51100 00000000`00000029 00000001`4e7fe8b8 0000005b`4e7fe900 ........)..........N.......N[...
0000005b`4e7fe800  00000234`d7f42800 0000005b`4e7fe8fc 00000000`00000000 00000234`d5a40000 .(..4......N[...............4...

*--> Error Logs <--*
10:39:47Z Coherent DLL load filepath: D:\Guild Wars 2\bin64\CoherentUI64.dll
Crashed at 10:39:47Z

**Comment by Friendly0Fire** [comment]
This is a Coherent UI crash, the addon does not touch that, so either you have an unrelated issue, or something is interfering with the game. Make sure you don't have overlays (GeForce overlay, RTSS, etc.) or known problematic applications (BitDefender) running.
