### ISSUE TITLE
2.3.0 Pre-Releases and Boon Table causing Crash

### ISSUE THREAD

**Issue by WolfSabian** [Friendly0Fire/GW2Radial#324]
So i'm aware it's still in testing and what not, and yes bugs or crashes are to be expected, but thought i'd post this here just incase. This way people are aware and if anyone else is having the issue and found a work around can let us know.

So far every release of 2.3.0 causes a crash when i try open the [boon table](https://github.com/knoxfighter/GW2-ArcDPS-Boon-Table).

Not sure why this is, but unfortunately I can't run it until this is resolved, wherever the issue is.  Hopefully will be fixed. :)

**Comment by Friendly0Fire** [comment]
This is all on @knoxfighter finishing his rework. I can't do anything about it on my end.

**Comment by WolfSabian** [comment]
Radial 2.2.1 and Boon Table working fine.  That's why i posted it here, it's only with the 2.3.0 pre-releases. :)

**Comment by Friendly0Fire** [comment]
I implemented a workaround until @knoxfighter patches his addon, hopefully it does not cause further issues.
