### ISSUE TITLE
Radial Menu Suddenly Stopped Working

### ISSUE THREAD

**Issue by ksbonta** [Friendly0Fire/GW2Radial#325]
**Describe the bug**
I played GW2 in the morning on Sat 8/27, the DX11 version of the menu worked as expected. When I came back later that afternoon, the menu stopped showing up at all. When I installed and run the DX9 version, it works just fine. I have tried to uninstalled both and then reinstalled the DX11 version, I can't get it to work again. As far as I know, literally nothing changed with my system or setup.

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: GeForce GTX 1650

**Additional context**
[gw2al_log.txt](https://github.com/Friendly0Fire/GW2Radial/files/9457290/gw2al_log.txt)

**Comment by Friendly0Fire** [comment]
Well the addon doesn't self-update, so either the game or some other application on your machine was updated and that caused an issue with the addon.

I'd recommend trying the pre-release just in case (manual install only), but otherwise I'd check for something (re-) enabling itself such as Nvidia's overlay, an antivirus, etc.

**Comment by ksbonta** [comment]
Thanks for the response and suggestions, unfortunately nothing I have tried seems to help. I have tried turning off my firewall briefly, turned off any background program I could find, uninstalling and reinstalling manually both the full release and then pre-release. I can only get the DX9 version to work.

**Comment by Friendly0Fire** [comment]
Yeah, I'll need the dump files. If you don't want to upload them here, you can also DM them to me over Discord.

**Comment by Ghandara** [comment]
Hello, i had the same issue and it's happened several time.
I found out how fix it but i have to do it everyday...
1- Uninstall the nvidia driver with DDU 
2- delete manualy all files in folder GW2 regardin the addon
3- delete all addon folders
4- re install the addon 
Everythings works fine until it happened again

Do you have ideas to fix it permanently ?

Thank you 
Ps: i am french ^^ sorry for my english :)

**Comment by ksbonta** [comment]
It wouldn't let me upload the .dmp directly, so here they are in .zip form.
[GW2Radial .dmp files.zip](https://github.com/Friendly0Fire/GW2Radial/files/9496574/GW2Radial.dmp.files.zip)

**Comment by ksbonta** [comment]
So, I finally fixed it. I ended up uninstalling everything. I then updated my .net framework and my C++, just to see what would happen. I reinstalled all of my addon programs and sure enough, it works now.
