### ISSUE TITLE
CTD on startup with radial installed.

### ISSUE THREAD

**Issue by teawitherby** [Friendly0Fire/GW2Radial#330]
**Describe the bug**
Game refuses to start with a "send report to aNet" option while radial is installed after a clean reinstall.
**To Reproduce**
1. Do '...'
Install radial (either through addonManager, or manually - neither works)
2. Then do 'start the game'
3. Bad stuff happens

**Expected behavior**
I expected the game to start with radial working.

**Screenshots**

**System configuration (please fill in):**
 - OS: win11
 - GPU: Nvidia GeForce GTX 1650 Ti
 - Chainloading, if any [e.g. arcdps -> GW2Radial -> GW2Hook]
 doesn't work by itself, neither with arcdps

**Additional context**
Idk what else to write here, should be all.

**Comment by Friendly0Fire** [comment]
Please provide logs and dumps if any.

**Comment by teawitherby** [comment]
Will try, how do I access those?

**Comment by teawitherby** [comment]
*--> Crash <--*
Assertion: Failed to load Coherent DLL. Error code: 0x7e 
File: D:\Perforce\Live\NAEU\v2\Code\Arena\Engine\ArenaWeb\CoherentUi\AwCoh.cpp(58)
App: Gw2-64.exe 
Pid: 13036
BaseAddr: 00007FF6C0BF0000
ProgramId: 101
Build: 134370
When: 2022-09-16T20:00:05Z 2022-09-16T22:00:05+02:00
Uptime:   0 days  0:00:01
Flags: 0
DumpFile: Crash.dmp

*--> System <--*
Name: ee473b95
IpAddr: 10.2.0.2 192.168.0.201
Processors: 16 [AuthenticAMD:15:0:1]
OSVersion: Windows 10.0 (64 bit)

*--> System Memory <--*
Physical:  9287MB/15741MB  58%
Paged:     9641MB/18685MB  51%
Virtual:  134213268MB/134217727MB  3%
Load: 40%
CommitTotal:   9043MB
CommitLimit:  18685MB
CommitPeak:   13130MB
SystemCache:   7288MB
HandleCount:  89449
ProcessCount:   201
ThreadCount:   3228

*--> Process Memory <--*
Private:          123MB
WorkingSet:       114MB
PeakWorkingSet:   236MB
PageFaults:    238128

*--> Memory Category Usage (Inclusive) <--*
[Category]              [Size(MB)]  [Count]     
Root                    89.47       6176        
Uncategorized           47.48       4537        
Programmer Data         35.54       884         
I/O                     35.02       571         
Archive                 33.67       25          
Collide                 6.45        755         
Collide Havok           6.45        755         
File Service            1.24        12          
Collections             0.26        75          
Dictionary              0.25        43          
Networking              0.11        14          
Asset Service           0.10        529         
Event                   0.07        3           
Game                    0.05        56          
Content                 0.02        1           
Engine                  0.02        12          
Threading               0.01        14          
Model-Programmer        0.01        1           
Install                 0.00        31          
BTree                   0.00        6           
Platform                0.00        65          
CharClient              0.00        5           
Services                0.00        8           
File Core               0.00        2           

*--> Memory Category Usage (Exclusive) <--*
[Category]              [Size(MB)]  [Count]     
Uncategorized           47.48       4537        
Archive                 33.67       25          
Collide Havok           6.45        755         
File Service            1.24        12          
Dictionary              0.25        43          
Networking              0.11        9           
Asset Service           0.10        529         
Event                   0.07        3           
Game                    0.03        46          
Content                 0.02        1           
Threading               0.01        14          
Model-Programmer        0.01        1           
Collections             0.01        25          
Engine                  0.01        6           
Install                 0.00        31          
BTree                   0.00        6           
Platform                0.00        65          
CharClient              0.00        5           
Services                0.00        8           
File Core               0.00        2           
Text                    0.00        1           
Download                0.00        3           
UI                      0.00        14          
Programmer Data         0.00        2           

*--> DllList <--*
00007FF6C0BF0000 - C:\Program Files\Guild Wars 2\Gw2-64.exe
00007FFE906A0000 - C:\Windows\SYSTEM32\ntdll.dll
00007FFE8F510000 - C:\Windows\System32\KERNEL32.DLL
00007FFE8DDD0000 - C:\Windows\System32\KERNELBASE.dll
00007FFE8EA30000 - C:\Windows\System32\USER32.dll
00007FFE8E3E0000 - C:\Windows\System32\win32u.dll
00007FFE8EBE0000 - C:\Windows\System32\GDI32.dll
00007FFE8E410000 - C:\Windows\System32\gdi32full.dll
00007FFE8E2C0000 - C:\Windows\System32\msvcp_win.dll
00007FFE8DC40000 - C:\Windows\System32\ucrtbase.dll
00007FFE8F070000 - C:\Windows\System32\ADVAPI32.dll
00007FFE8FDE0000 - C:\Windows\System32\msvcrt.dll
00007FFE8ED40000 - C:\Windows\System32\sechost.dll
00007FFE8F840000 - C:\Windows\System32\RPCRT4.dll
00007FFE8EE40000 - C:\Windows\System32\WS2_32.dll
00007FFE8DD60000 - C:\Windows\System32\WINTRUST.dll
00007FFE8A520000 - C:\Windows\SYSTEM32\VERSION.dll
00007FFE90650000 - C:\Windows\System32\PSAPI.DLL
00007FFE86ED0000 - C:\Windows\SYSTEM32\WINMM.dll
00007FFE8FC40000 - C:\Windows\System32\ole32.dll
00007FFE887C0000 - C:\Windows\SYSTEM32\WTSAPI32.dll
00007FFE8F180000 - C:\Windows\System32\combase.dll
00007FFE8FA10000 - C:\Windows\System32\OLEAUT32.dll
00007FFE8FE90000 - C:\Windows\System32\SHELL32.dll
00007FFE87C90000 - C:\Windows\SYSTEM32\MSACM32.dll
00007FFE8E150000 - C:\Windows\System32\CRYPT32.dll
00007FFE7F1A0000 - C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.22000.978_none_ce87762a12f7f3ba\gdiplus.dll
00007FFE7EC10000 - C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22000.1_none_271a8fad6a2d1b1e\COMCTL32.dll
00007FFE65F50000 - C:\Windows\SYSTEM32\USP10.dll
00007FFE7F360000 - C:\Windows\SYSTEM32\MSIMG32.dll
00007FFE8A530000 - C:\Windows\SYSTEM32\Secur32.dll
00007FFE8CB50000 - C:\Windows\SYSTEM32\CRYPTBASE.DLL
00007FFE8C820000 - C:\Windows\SYSTEM32\SSPICLI.DLL
00007FFE8FBE0000 - C:\Windows\System32\IMM32.DLL
00007FFE8CC30000 - C:\Windows\SYSTEM32\MSASN1.dll
00007FFE8E360000 - C:\Windows\System32\bcryptPrimitives.dll
00007FFE8D520000 - C:\Windows\SYSTEM32\dbghelp.dll
00007FFE8ADB0000 - C:\Windows\SYSTEM32\windows.storage.dll
00007FFE8AC40000 - C:\Windows\SYSTEM32\wintypes.dll
00007FFE8FAF0000 - C:\Windows\System32\SHCORE.dll
00007FFE8F120000 - C:\Windows\System32\shlwapi.dll
00007FFE8DAB0000 - C:\Windows\SYSTEM32\profapi.dll
00007FFE8BED0000 - C:\Windows\SYSTEM32\kernel.appcore.dll
00007FFE8D8C0000 - C:\Windows\SYSTEM32\DEVOBJ.dll
00007FFE8D850000 - C:\Windows\SYSTEM32\cfgmgr32.dll
00007FFE8A680000 - C:\Windows\SYSTEM32\dxcore.dll
00007FFE8A3C0000 - C:\Windows\system32\uxtheme.dll
00007FFE84850000 - C:\Windows\SYSTEM32\cryptnet.dll
00007FFE8EA10000 - C:\Windows\System32\imagehlp.dll
00007FFE8D830000 - C:\Windows\SYSTEM32\CRYPTSP.dll
00007FFE8BE30000 - C:\Windows\system32\rsaenh.dll
00007FFE8D3E0000 - C:\Windows\SYSTEM32\bcrypt.dll
00007FFE8F960000 - C:\Windows\System32\clbcatq.dll
00007FFE8D490000 - C:\Windows\SYSTEM32\ntmarta.dll
00007FFE870C0000 - C:\Windows\system32\napinsp.dll
00007FFE7EAD0000 - C:\Windows\system32\pnrpnsp.dll
00007FFE8CBC0000 - C:\Windows\System32\mswsock.dll
00007FFE8B990000 - C:\Windows\SYSTEM32\DNSAPI.dll
00007FFE8B920000 - C:\Windows\SYSTEM32\IPHLPAPI.DLL
00007FFE8F500000 - C:\Windows\System32\NSI.dll
00007FFE7EAB0000 - C:\Windows\System32\winrnr.dll
00007FFE84ED0000 - C:\Windows\system32\wshbth.dll
00007FFE445B0000 - C:\Windows\system32\nlansp_c.dll
00007FFE84960000 - C:\Windows\System32\fwpuclnt.dll
00007FFE7EE40000 - C:\Windows\System32\rasadhlp.dll
00007FFE8EC10000 - C:\Windows\System32\msctf.dll
00007FFE73310000 - C:\Windows\SYSTEM32\textinputframework.dll
00007FFE849F0000 - C:\Windows\SYSTEM32\WindowsCodecs.dll
00007FFE693D0000 - C:\Windows\system32\explorerframe.dll
00007FFE76620000 - C:\Windows\SYSTEM32\TextShaping.dll

*--> Game Context <--*
MapId: 0
Flags: 0x241
ElapsedTime: 00:00:01

*--> World State <--*
<WorldState />

[DbgHelp.dll is C:\Windows\SYSTEM32\dbghelp.dll]
[DbgHelp.dll version 6.2.22000.1 (64/32-bit compatible)]

*--> ClientContextThreadProc Thread 0x17d4 <--*

*--> Trace <--*
Pc                Rt                : Args
00007ff6`c0cc9775 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`c16feb7f 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`c1069c21 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`c10685b5 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`c0fb60d0 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`c0fb51d9 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`c0ca5ed6 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`c0ca5bf3 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`c0f157e9 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`c0f13bc0 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`c0f13848 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`c0f14bc7 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`c0f14c96 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`c0f12fc5 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`c0cbf8fd 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`c0ecec88 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffe`8f5254e0 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffe`906a485b 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 

*--> Thread registers <--*
rax=0000000000000001 rbx=00007ff6c26d2980 rcx=000000e082cfe1f0
rdx=0000000000000200 rsi=000002c5b1186630 rdi=000000000000003a
rip=00007ff6c0cc9711 rsp=000000e082cfe190 rbp=000000e082cfea40
 r8=000000000000002d  r9=00007ff6c0ebf918 r10=0000000000000008
r11=0000000000000000 r12=0000000000000002 r13=0000000000000000
r14=000002c5b0df1e50 r15=0000000000000000
cs=0033 ss=002b ds=002b es=002b fs=0053 gs=002b efl=00000202

rbx-32 00007FF6C26D2960  65686f43`5c626557 415c7447`746e6572 00707063`2e744777 00000000`00000000 
rbx +0 00007FF6C26D2980  6f667265`505c3a44 6576694c`5c656372 32765c55`45414e5c 72415c65`646f435c 
rbx+32 00007FF6C26D29A0  69676e45`5c616e65 616e6572`415c656e 65686f43`5c626557 415c6955`746e6572 
rcx-32 000000E082CFE1D0  000000e0`82cfe908 00007ff6`c0cc9711 000000e0`82cfe190 000000e0`82cfea40 
rcx +0 000000E082CFE1F0  000000e0`82cfe2a8 000000e0`82cfe7d0 00000000`00000001 00007ffe`906f1a73 
rcx+32 000000E082CFE210  00000000`00000000 000002c5`aefa1e30 00009f80`0010000f 0053002b`002b0033 
 r9-32 00007FF6C0EBF8F8  c30e5088`440c4889 44084ab7`0f028b4c 6600894c`0a4ab60f c30a4888`44084889 
 r9 +0 00007FF6C0EBF918  90c30889`660ab70f 440442b7`0f440a8b 44660889`064ab60f c3064888`44044089 
 r9+32 00007FF6C0EBF938  0f44084a`8b028b4c 48890089`4c0c4ab7 0fc30c48`89446608 660242b6`0f440ab7 

*--> Code <--*
00007ff6`c0cc96f1  8d4c2440 e8c638fe ff488d0d 6fc71602 .L$@..8..H..o...
00007ff6`c0cc9701  e83a68fe ff488d4c 2460ff15 176c5001 .:h..H.L$`...lP.
00007ff6`c0cc9711  488b8424 58010000 4c8d0560 9e510148 H..$X...L..`.Q.H
00007ff6`c0cc9721  89442448 488d9424 30050000 488b8424 .D$HH..$0...H..$
00007ff6`c0cc9731  f8000000 4885db48 89442450 448bcf48 ....H..H.D$PD..H
00007ff6`c0cc9741  8b842400 0100004c 0f45c348 89442458 ..$....L.E.H.D$X

*--> Stack <--*
000000e0`82cfe190  00007ff6`c26d2980 000000e0`82cfe2b0 000002c5`b29db090 000002c5`00000030 .)m.....................0.......
000000e0`82cfe1b0  000000e0`82cfe1d8 000000e0`82cfe1f0 00000000`00000000 00000000`00000000 ................................
000000e0`82cfe1d0  000000e0`82cfe908 00007ff6`c0cc9711 000000e0`82cfe190 000000e0`82cfea40 ........................@.......
000000e0`82cfe1f0  000000e0`82cfe2a8 000000e0`82cfe7d0 00000000`00000001 00007ffe`906f1a73 ........................s.o.....
000000e0`82cfe210  00000000`00000000 000002c5`aefa1e30 00009f80`0010000f 0053002b`002b0033 ........0...............3.+.+.S.
000000e0`82cfe230  00000202`002b002b 00007ffe`906f1975 00000000`00000000 000002c5`b29dd380 +.+.....u.o.....................
000000e0`82cfe250  000002c5`b29dd380 000002c5`aefa1e30 000000e0`82cfe2a8 00000000`00000001 ........0.......................
000000e0`82cfe270  000000e0`82cfe1f0 00000000`00000200 00007ff6`c26d2980 000000e0`82cfe190 .................)m.............
000000e0`82cfe290  000000e0`82cfea40 000002c5`b1186630 00000000`0000003a 00000000`0000002d @.......0f......:.......-.......
000000e0`82cfe2b0  00007ff6`c0ebf918 00000000`00000008 00000000`00000000 00000000`00000002 ................................
000000e0`82cfe2d0  00000000`00000000 000002c5`b0df1e50 00000000`00000000 00007ff6`c0cc9711 ........P.......................
000000e0`82cfe2f0  00000000`0000027f 00000000`00000000 00000000`00000000 0002ffff`00009f80 ................................
000000e0`82cfe310  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
000000e0`82cfe330  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
000000e0`82cfe350  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
000000e0`82cfe370  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
000000e0`82cfe390  00007ff6`c2d17fd0 000002c5`aefa5d20 00650068`006f0043 0074006e`00650072 ........ ]......C.o.h.e.r.e.n.t.
000000e0`82cfe3b0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
000000e0`82cfe3d0  00000000`00000000 00000000`00000000 00720065`0068006f 00550074`006e0065 ................o.h.e.r.e.n.t.U.
000000e0`82cfe3f0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
000000e0`82cfe410  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
000000e0`82cfe430  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
000000e0`82cfe450  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
000000e0`82cfe470  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
000000e0`82cfe490  00000000`00000100 000002c5`aef90150 00000000`00000001 000002c5`b11e22b0 ........P................"......
000000e0`82cfe4b0  00000000`00000048 00007ffe`906c1dfa 000002c5`aef902e8 000002c5`b29db010 H.........l.....................
000000e0`82cfe4d0  000002c5`aef90000 00000000`00000048 00000000`00000100 000002c5`b29db010 ........H.......................
000000e0`82cfe4f0  00000000`00000080 00007ffe`906c61b1 000002c5`aef90000 000002c5`b29db010 .........al.....................
000000e0`82cfe510  000002c5`b29db000 00000000`00000080 000000e0`00000048 00000000`00000048 ................H.......H.......
000000e0`82cfe530  00007ffe`907d10f8 000000e0`0000052e 00000000`82cfe701 000000e0`82cf004c ..}.....................L.......
000000e0`82cfe550  00007ffe`907d1100 00000000`00000048 00000001`82cfe628 000000e0`82cfe600 ..}.....H.......(...............
000000e0`82cfe570  000002c5`b29dd240 000000e0`82cfe688 00000000`00000000 000002c5`aee90000 @...............................

*--> Error Logs <--*
20:00:05Z Coherent DLL load filepath: C:\Program Files\Guild Wars 2\bin64\CoherentUI64.dll
Crashed at 20:00:05Z

---------------------------------------

this is what i get when my game crashes, right after installing radial.
i dont know why this happens, worked just fine until wednesday.

**Comment by teawitherby** [comment]
i have tried the dx9, dx11 versions through addon manager
also tried the manual install, neither works.

**Comment by Friendly0Fire** [comment]
This is a Coherent UI crash, it shouldn't have anything to do with this addon. Does the game run correctly if you remove the addon?

**Comment by teawitherby** [comment]
Yes, it runs perfectly without.

**Comment by Friendly0Fire** [comment]
Did you resolve the issue?
