### ISSUE TITLE
In water hotkey always use skimmer

### ISSUE THREAD

**Issue by angomania** [Friendly0Fire/GW2Radial#334]
Every time I use the hotkey in water, the skimmer is selected. Can´t select the skiff.
Selection: Center behavior is nothing.

The skiff can be selected only near water on land.

**Comment by angomania** [comment]
center behavior is nothing.

**Comment by Friendly0Fire** [comment]
Use the latest pre-release and make sure you are *on* the water surface, otherwise the skiff cannot be summoned.

**Comment by angomania** [comment]
That did the trick ! :)
...used the Addon Manager for install.

Thank You!
