### ISSUE TITLE
Configuration could not be saved!

### ISSUE THREAD

**Issue by supernovanexus** [Friendly0Fire/GW2Radial#337]
**Describe the bug**
Error Message "Could not save addon configuration. Reason given was: No configuration folder could be located."

**To Reproduce**
1. Start GW2
2. Error shows up immediately

**System configuration (please fill in):**
 - OS: Windows 12
 - GPU: RTX3060

**Comment by supernovanexus** [comment]
Windows 11*

**Comment by rossw969** [comment]
I get the same issue. I have to run gw2 as administrator to work , but then I always get the annoying Windows UAC. this has only been a problem since the lunar festival patch.

**Comment by Friendly0Fire** [comment]
Please provide log files and game install location.
