### ISSUE TITLE
Mount wheel menu does not open

### ISSUE THREAD

**Issue by Zenith2198** [Friendly0Fire/GW2Radial#342]
**Describe the bug**
After today's update, the mount wheel doesn't seem to want to work anymore. I use GW2 Addon Manager, and with the removal of DX9 I had to remove my addon to force DX12 from DX9. The manager hasn't allowed me to "disable" or "remove" individual addons, so I was forced to do a clean reset of my two addons. However, after reinstalling the mount wheel, it did not open the menu when pressing shift+alt+m. I fresh reinstalled GW2 and the addon manager to the most recent updates to no avail.

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: 2070 Super

**Additional context**
When the game is running, gw2radial.log has no information. After closing the game, the log updates to the INF line "This is GW2Radial v2.2.1". The gw2al_log.txt file reads:

> [INFO] core | Addon loader v1.0 (v1.1 r33) initialized
> [INFO] core | Loading addons from "./addons" path
> [INFO] core | Loading d3d9_wrapper
> [INFO] core | Loaded d3d9_wrapper v2.0 r21
> [INFO] core | Loading gw2radial
> [INFO] core | Loaded gw2radial v2.2 r1
> [INFO] core | Done loading addons
> [INFO] d3d9_wrapper | Loading system dxgi
> [WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
> [INFO] d3d9_wrapper | Loading system dxgi
> [WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
> [INFO] d3d9_wrapper | Loading system dxgi

**Comment by Zyian** [comment]
Please provide a screenshot of your Guild Wars 2 folder, that way we can verify all of the correct files are present.

**Comment by Zenith2198** [comment]
![image](https://user-images.githubusercontent.com/22260835/232931333-231dc052-5f8b-46d4-be00-2d2352d279c0.png)
![image](https://user-images.githubusercontent.com/22260835/232931363-8ea2f14c-ff22-498b-8c54-aa6fbe312f51.png)
![image](https://user-images.githubusercontent.com/22260835/232931391-9f2f2aa1-8cda-4f5c-a1fe-604dbd8010a6.png)

**Comment by Friendly0Fire** [comment]
Is there a `dxgi.dll` file in `bin64`?

Do you use any of the following applications (exceptions/turning them off may not be enough):
- Razer Cortex
- BitDefender
- groupy
- Citrix Workspace (v22 or later)
- mydesk shield
- Nvidia's GeForce Overlay
- ASUS GPU Tweak III, Afterburner, RTSS (RivaTuner Statistics Server) or any other GPU overclock/control software

**Comment by Zenith2198** [comment]
![image](https://user-images.githubusercontent.com/22260835/232935498-97a50eab-1739-4317-bf09-cd321f0256cf.png)
![image](https://user-images.githubusercontent.com/22260835/232935509-1c553439-a11a-4053-a663-005f1a1bdd70.png)
![image](https://user-images.githubusercontent.com/22260835/232935525-6d5823be-b7d9-406b-bc8c-312d960a9c28.png)

I use Nvidia's overlay, but I had been using it in the past with no issues prior to today's update.

I'm starting to wonder if this is the fault of GW2 Addon Manager instead of your addon directly. If certain files aren't there that should be, I would point the blame more at the addon manager. I'm going to do a clean wipe of the addons using the manager and then manually install GW2Radial and get back to you.

**Comment by Friendly0Fire** [comment]
> I use Nvidia's overlay, but I had been using it in the past with no issues prior to today's update.

That's irrelevant, the game changed its rendering pipeline and you also changed which API you're using. Please turn it off and try again.

**Comment by Zenith2198** [comment]
Turning off Nvidia Overlay did in fact solve the issue. I would certainly like to be able to use both at once, still. However, the culprit has been found!

**Comment by Friendly0Fire** [comment]
You can disable just the problematic part of the overlay from the overlay settings -> "Photo Mode/Game Filter" -> Turn off.

**Comment by bboxall** [comment]
I came here to report the same issue. I have Nvidia GeForce, but the overlay is turned off.

**Comment by dang-nabbit** [comment]
im having the same issue but im not running any of the listed programs, should i start a separate issue?

**Comment by Friendly0Fire** [comment]
@dang-nabbit Yes, please. I'll close this one.
