### ISSUE TITLE
Gw2radial and arcdps not working since this morning ( 06:00 GMT+ 2)

### ISSUE THREAD

**Issue by S1rDonkey** [Friendly0Fire/GW2Radial#345]
Hi there. 

My first time posting here and so I hope I've followed procedure properly.
I don't know if this is a bug or if just user error.

**Describe the bug**
Since I logged in this morning, my arcdps, arcdps blishud and gw2radial are not working. I have tried completely uninstalling all addon related files and reinstalling to no avail.
I can however get my arcdps to work if I install it manually, but as soon as I use the addon manager it breaks.

**To Reproduce**
1. Install addon manager and run it.
2. Select arcdps, arcdps blishud and gw2radial. (I did try with just gw2radial selected with the same result below)
3. Update.
4. Run the client and load into the game.
5. Press the default hotkeys for each ctrl + alt + m or ctrl + alt + t
6. Nothing happens.

**Expected behavior**
Gw2radial and arcdps to work as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/131514673/233768092-16b62f50-48ef-44c8-a6ae-016b4241a362.png)
![image](https://user-images.githubusercontent.com/131514673/233768133-91a87cf9-f552-49be-8436-853a89853cdd.png)
![image](https://user-images.githubusercontent.com/131514673/233768137-6168ac99-54c6-4246-b9a1-0419b2f67f7c.png)
![image](https://user-images.githubusercontent.com/131514673/233768147-3bd0a02d-d305-468a-9167-fb8a1ee4e38c.png)
![image](https://user-images.githubusercontent.com/131514673/233768157-1ed2f957-a7fe-4c14-8415-2d8f8b56590c.png)

gw2radial log:
![image](https://user-images.githubusercontent.com/131514673/233768305-0fc76232-b043-4309-93c4-bc69de48375e.png)

gw2al_log:
![image](https://user-images.githubusercontent.com/131514673/233768326-68d82520-c3ac-44d5-a8a1-02e986e950cf.png)

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: RX 6600XT
 - CPU: Ryzen 5 3600 3.59GHz

**Additional context**

**Comment by Friendly0Fire** [comment]
Copy `dxgi.dll` to your root GW2 folder and try again. If that doesn't work, you can try copying it into `bin64` too.

**Comment by S1rDonkey** [comment]
Wow, that was exactly what was needed. Thank you!

Issue resolved.
