### ISSUE TITLE
GW2Radial DMP files Flooding GW2 Base Directory

### ISSUE THREAD

**Issue by WolfSabian** [Friendly0Fire/GW2Radial#346]
I'm hoping someone can provide some info on this and hopefully stop it.

My GW2 folder is being flooded with THOUSANDS of GW2Radial_[DATE]_[TIME]-[NUMBER].dmp files.

Not long ago I removed over 83,000 of these files when i noticed the problem.  Within approx 1 month time over 14,000 more have been generated.

Anyone else having this issue or have suggestions on what might be the cause or solution?
![gw2radial_dmp1](https://github.com/Friendly0Fire/GW2Radial/assets/49987935/32c74f75-e84a-4600-bf51-dda7af1f15df)
![gw2radial_dmp2](https://github.com/Friendly0Fire/GW2Radial/assets/49987935/b05ec685-4d90-415a-b4cf-b51ecff59ae3)

**Comment by FrozenTrout** [comment]
My system started doing this the other day as well

**Comment by Friendly0Fire** [comment]
These indicate that something is wrong with your GW2 install. Without uploading some of them (and your logs), there's no telling what.

**Comment by FrozenTrout** [comment]
I reinstalled the game and it's all good now, something must have gotten messed up

**Comment by WolfSabian** [comment]
> These indicate that something is wrong with your GW2 install. Without uploading some of them (and your logs), there's no telling what.

Let me know what you need and I'll provide it. I don't have radial installed at the moment but everything is backed up and should be there to send you.

**Comment by WolfSabian** [comment]
@Friendly0Fire what files do you need?

**Comment by Friendly0Fire** [comment]
Dumps, logs, whatever you have.

**Comment by WolfSabian** [comment]
> Dumps, logs, whatever you have.

Was looking over the files, and sadly I'm not sure they will be of use but can send some if you like.  All the DMP files have a size of 0 and i believe have nothing written in them.  As for a related log, I may have lost that during one of my re-installs. The only one i have is newer and likely not related to the issue.

I've provided an archive with the last 6 DMP files created.

[Radial DMPs.zip](https://github.com/Friendly0Fire/GW2Radial/files/12690453/Radial.DMPs.zip)

**Comment by Friendly0Fire** [comment]
Strange, I don't think I've ever seen empty dump files, but I unfortunately cannot do anything with these.

If you can replicate at some point, feel free to reopen an issue, but I'll close this for now.
