### ISSUE TITLE
Feature Suggestion: Let us disable RivaTuner error message

### ISSUE THREAD

**Issue by WatchThemFall** [Friendly0Fire/GW2Radial#347]
Please add a way to disable this message. I use RTSS for scanline sync since it's way better than the built in Vsync. (Less input delay, more consistent framerate). The addon works fine with this enabled, yet this error message pops up every single time I open the game.

**Comment by negr0man3r** [comment]
Hi,
I second this message.
The addons works well with RTSS so please, let us disable those errors.

**Comment by Charybdis** [comment]
Came here to create an issue to track this - the popup is an annoyance in 2.3 pre8 (for Nvidia Ansel in my case).

Would suggest that the message pops up once if presence has been detected since the last time Radial was run (or the user ticks a box to make it go away permanently).

**Comment by Friendly0Fire** [comment]
It's been removed from the pre-release.

**Comment by negr0man3r** [comment]
Hi

I had the message reappeared even by disabling Photo Mode, after upgrading from GeForce Experience to the the new Nvidia App.


![image](https://github.com/user-attachments/assets/d7797894-bf06-4083-81c0-0d91bf6b2812)
![image](https://github.com/user-attachments/assets/40f0d809-45b9-4946-84af-0ef420f0a315)
