### ISSUE TITLE
GW2 - crashes when i enter WvW with nerco

### ISSUE THREAD

**Issue by Stahlbesen** [Friendly0Fire/GW2Radial#348]
**Describe the bug**

GW2 crashes very often as soon as I want to go into WvW with the Necro and only with the Necro

log file is attached

... and dont know if the problem depenads on that but i have to copy and rename d3d11.dll to d3d9.dll other wise Arcdps will not work. I tried to keep the system clean and reinstall all, but still the same porblem.

**To Reproduce**
1. Do '...'
2. Then do '...'
3. Bad stuff happens

**Expected behavior**

**Screenshots**

**System configuration (please fill in):**
 - OS: [e.g. Windows 10]
 - GPU: [e.g. GTX1080]
 - Chainloading, if any [e.g. arcdps -> GW2Radial -> GW2Hook]

**Additional context**
[arcdps_lastcrash.log](https://github.com/Friendly0Fire/GW2Radial/files/11798012/arcdps_lastcrash.log)

**Comment by Friendly0Fire** [comment]
Your install is most likely completely corrupted. Without further information, the only suggestion I can make is to remove every addon you have and start from scratch *with the Addon Manager*.

Either way though, this is very very unlikely to be a GW2Radial crash.
