### ISSUE TITLE
Add `Scan for Rift` and `Summon Conjured Doorway` as Novelties

### ISSUE THREAD

**Issue by tiyn** [Friendly0Fire/GW2Radial#350]
With the new Guild Wars 2 expansion Secrets of the Obscure the skill `Scan for Rift` has been added.
It is available in-game via the same menu as the `Jade Bot: Personal Waypoint`, `Start Fishing` and the `Summon Skiff`.
It would be really nice to access it with GW2Radial under the the Novelties menu like comparable options.
Similar to the `Scan for Rift` function the `Summon Conjured Doorway` function also could be added similarly.

**Comment by Fikett** [comment]
> With the new Guild Wars 2 expansion Secrets of the Obscure the skill `Scan for Rift` has been added. It is available the same way as the `Jade Bot: Personal Waypoint`, `Start Fishing` and the `Summon Skiff`. It would be really nice to access it via the Novelties menu like comparable options.

how do you activate EoD skills? i dont see them(

**Comment by tiyn** [comment]
Get on the newest version.
The Skiff is listed under Mounts, the other skills under Novelties.
Setup is identical to the other mounts and novelties.

**Comment by Fikett** [comment]
> Get on the newest version. The Skiff is listed under Mounts, the other skills under Novelties. Setup is identical to the other mounts and novelties.

i have last version 2.2.1, but dont see skills in Novelties(
Have only skiff in mounts.
Did i miss something?

![image](https://github.com/Friendly0Fire/GW2Radial/assets/74620393/a9d9167c-5673-4c6a-877d-b5503d6d341f)
![image](https://github.com/Friendly0Fire/GW2Radial/assets/74620393/d2a70f8c-3a1d-4568-bba1-bb7174688d4a)

**Comment by tiyn** [comment]
There is a Prerelease called "Version v2.3.0-pre8" you can find it in the Releases list. 
![screenshot-2023-08-26_15-00-51](https://github.com/Friendly0Fire/GW2Radial/assets/43725244/0af9997b-f8e8-49ce-bd6f-e3a013360fc6)
![screenshot-2023-08-26_15-01-02](https://github.com/Friendly0Fire/GW2Radial/assets/43725244/467bb491-7036-4b64-b647-d8416fcf72f5)

**Comment by tiyn** [comment]
EDIT: updated this feature request to include `Summon Conjured Doorway` to prevent cluttering the issues with many similar issues.

**Comment by Friendly0Fire** [comment]
I'm looking at the game's options and, as is typical for ANet, there doesn't seem to be a keybind for `Summon Conjured Doorway` so I can't currently support it. `Scan for Rift` is on the list though.

**Comment by Friendly0Fire** [comment]
This is in the pre-release now.
