### ISSUE TITLE
Allow GW2Radial to mount the Skyscale in combat if the SotO mastery Combat Launch is active

### ISSUE THREAD

**Issue by tduffy49** [Friendly0Fire/GW2Radial#351]
**Is your feature request related to a problem? Please describe.**
Currently, GW2Radial does not work with the new SotO mastery [Combat Launch](https://wiki.guildwars2.com/wiki/Combat_Launch). This mastery allows you to mount your Skyscale while in combat once every 3 minutes. However, if you use GW2Radial to attempt to mount the Skyscale in combat one of two things happens:
1. If the input queuing option is selected: it queues the Skyscale and mounts it when out of combat.
2. If the input queuing option is not selected: it ignores the attempt to mount the Skyscale in combat.

**Describe the solution you'd like**
If the Combat Launch mastery is earned and off cooldown and the Skyscale is selected in GW2Radial while in combat, it should trigger the mastery and mount the Skyscale in combat.

**Describe alternatives you've considered**
- If the in game mount/dismount keybind is different from the show GW2Radial keybind and the Skyscale is set as the active mount, you can press it to trigger Combat Launch.
- If the Skyscale mount/dismount keybind is different from the show GW2Radial keybind, you can press it to trigger Combat Launch.
- If you use the same keybind to open GW2Radial as your mount/dismount you have to set the Skyscale as the active mount, enable conditional keybinds in the GW2Radial options, and set a conditional keybind to only enable keybinds if the character isn't in combat. However, this isn't ideal if you want to be able attempt to mount/queue a mount other than the Skyscale in combat using GW2Radial.

**Comment by kureysalp** [comment]
With jantir wilds, now you can mount up warclaw in combat but addon doesn't trigger keybinds while in combat (makes 0 sense). There should be option to toggle that.

**Comment by Friendly0Fire** [comment]
> With janthir wilds, now you can mount up warclaw in combat but addon doesn't trigger keybinds while in combat (makes 0 sense). 

It makes perfect sense given all of the mounts prior to SotO couldn't be used in combat, and mounts post-SotO are only conditionally available in combat.

As the game does not expose the conditional availability, it's not straightforward to fix. I currently do not have a good solution that does not regress features in some other way.

**Comment by kureysalp** [comment]
> > With janthir wilds, now you can mount up warclaw in combat but addon doesn't trigger keybinds while in combat (makes 0 sense).
> 
> It makes perfect sense given all of the mounts prior to SotO couldn't be used in combat, and mounts post-SotO are only conditionally available in combat.
> 
> As the game does not expose the conditional availability, it's not straightforward to fix. I currently do not have a good solution that does not regress features in some other way.

What's the harm of triggering a keybind while player is in combat, there is no harm and because of that we can't mount up warclaw while in combat.

**Comment by ItIsI-Orient** [comment]
> > With janthir wilds, now you can mount up warclaw in combat but addon doesn't trigger keybinds while in combat (makes 0 sense).
> 
> It makes perfect sense given all of the mounts prior to SotO couldn't be used in combat, and mounts post-SotO are only conditionally available in combat.
> 
> As the game does not expose the conditional availability, it's not straightforward to fix. I currently do not have a good solution that does not regress features in some other way.

You could add a checkbox to the settings which the user could enable/disable based on them (not) having the mastery, right?

**Comment by Ric-F** [comment]
Any movement on this? At the moment the addon is redundant for me due to this restriction.

**Comment by Friendly0Fire** [comment]
You should look at the [pre-release](https://github.com/Friendly0Fire/GW2Radial/releases/tag/v2.4.0-pre1) then because that's the solution I've had to settle on.
