### ISSUE TITLE
GW2 Crash on Start, atan2 not defined

### ISSUE THREAD

**Issue by MvBonin** [Friendly0Fire/GW2Radial#353]
**Describe the bug**
Guildwars 2 doesn't start and gw2radial throws an error message at the beginning.
"Compilation failed: 0x80004005".

**To Reproduce**
1. Manually install gw2radial as described in README.md
2. Start gw2

**Expected behavior**
GW2 starts and the addon loads

**Screenshots**
![image](https://github.com/Friendly0Fire/GW2Radial/assets/41330432/e05ff47d-590b-4b63-b8b5-dff84bf31bd9)

**System configuration (please fill in):**
 - OS: Endeavour OS with Proton steam
 - GPU: AMD Radeon R9 380

**Additional context**
This is the logfile:
`
[13:26:21.5542742|INF] This is GW2Radial v2.2.1 (0abc260b056d7f40837b45048ef50ac201ad2f98)

[13:26:22.0693883|INF] Config folder is now 'Z:\home\m\.local\share\Steam\steamapps\common\Guild Wars 2\addons\gw2radial'.

[13:26:22.4693794|ERR] Compilation failed: 0x80004005

[13:26:22.4694991|ERR] Compilation errors:

Wheel.hlsl:528:51: E5005: Function "atan2" is not defined.
`

--> Looks like atan2 in Wheel.cpp is not defined.

**Comment by Friendly0Fire** [comment]
Sorry, I don't support Linux. There are just too many variables with all the distros and layers for me to manage.

Feel free to participate in the [Linux users discussion thread](https://github.com/Friendly0Fire/GW2Radial/discussions/281), you may find answers or help there.
