### ISSUE TITLE
Radial Menu doesn't appear

### ISSUE THREAD

**Issue by calvissuperman** [Friendly0Fire/GW2Radial#355]
**Describe the bug**
I went into settings, and only added one keybind. The radial menu at cursor location. I press the key, nothing shows up, and if I move my mouse somewhere and let go it rubber bands my cursor back to the original location.

The addon is obviously starting, as I'm able to open the in-game menu and change keybinds. The radial menu just doesn't seem to overlay, so this leads me to believe it's an issue with another addon. I have a couple installed:

GW2TACO
ArcDPS (through addon mngr)
GW2Radial (through addon mngr)
directx 12 mod

**System configuration (please fill in):**
 - OS: Windows 11
 - GPU: Nvidia 2070
 - Chainloading: Not sure, using above addons through the GW2 Addon Manager.

**Additional context**
I am almost certain this is an issue with GW2Taco, but searching the internet gives no results for this type of issue. I will try not running Taco and see if that fixes it.

**Comment by Friendly0Fire** [comment]
You need to setup all of your mount keybinds in the settings, otherwise there's nothing for the menu to show.

**Comment by calvissuperman** [comment]
Thanks for the quick reply, I skipped right over the instructions like an average internet know it all and this is what happens.

After reading the directions for 30 seconds I now have a perfectly working menu and it's great! Thank you so much!
