### ISSUE TITLE
Shift+Alt+M doesn't show config, addon doesn't work

### ISSUE THREAD

**Issue by rinart73** [Friendly0Fire/GW2Radial#356]
**Describe the bug**
I installed GW2 Radial on a fresh install of GW2 using Addon Manager. I launched the game, saw no config window (if I remember correctly it usually appears automatically). I tried pressing `Shift+Alt+M` to open it manually. It didn't work.

**To Reproduce**
1. Instal the latest version of GW2 Addon Manager
2. Instal GW2 Radial addon
3. Launch the game, press `Shift+Alt+M`, no config menu displayed
4. Install the latest debug version from Github
5. Launch the game, press `Shift+Alt+M`, still no config menu

**Expected behavior**
Configuration menu should have appeared.

**System configuration (please fill in):**
 - OS: Windows 11
 - GPU: GeForce RTX 4060 Laptop (selected for GW2 both in Nvidia Control Panel and in the Windows Graphics settings)
 - Chainloading: Addon Loader > GW2Radial (standard recommended install)

**Additional context**
[gw2al_log.txt](https://pastebin.com/ehPGPVpP)
[gw2radial.log](https://pastebin.com/Pa18QXVS)

No special apps installed aside from Nvidia Control Panel (NOT GeForce Experience) and Intel Arc Control.
Intel Arc and Discord overlays are disabled.

Please tell me if you need any more info.

**Comment by knoxfighter** [comment]
Send a screenshot of your gw2 folder (with file sizes) please.

Do you use any of the following?
- BitDefender
- groupy
- Citrix Workspace (v22 or later)
- mydesk shield
- Nvidia's GeForce Overlay
- ASUS GPU Tweak III, Afterburner, RTSS (RivaTuner Statistics Server) or any other GPU overclock/control software

**Comment by rinart73** [comment]
![image](https://github.com/Friendly0Fire/GW2Radial/assets/1765611/01463488-b63c-44a5-b02f-dfefad3b15c4)
No, I don't use any of these programs.

**Comment by knoxfighter** [comment]
unlock d3d11.dll:
- rightclick d3d11.dll -> options -> unlock at the bottom.
Image:
![Unlock Button Image](https://cdn.discordapp.com/attachments/718866934015459400/1071867744351428648/image.png)

**Comment by Myster-Marz** [comment]
I got mines to work by changing the name of the d3d11.dll file to dxgi.dll (I renamed the original dxgi.dll to dxgi.old.dll). I randomly decided to try this as nothing else worked.

**Comment by Friendly0Fire** [comment]
Sorry for not noticing this earlier, but you have an Intel iGPU on a laptop, unfortunately Intel's drivers interfere with Radial and there is no fix for the time being.
