### ISSUE TITLE
GW2 crashes at start due to shader compilation failure on Arch.

### ISSUE THREAD

**Issue by dolour** [Friendly0Fire/GW2Radial#357]
**Describe the bug**
Well, the title pretty much says it. Running via Steam with GE-Proton (Experimental doesent work either).

**To Reproduce**
Happens everytime on launch.

**Screenshots**
![crash](https://github.com/Friendly0Fire/GW2Radial/assets/47855667/00270dc8-c723-4cf4-8a7d-6a1e204a6d3c)

**System configuration (please fill in):**
 - OS: Arch Linux
 - GPU: rx580
 - Chainloading, arcdps -> GW2Radial

**Comment by knoxfighter** [comment]
Please consult https://github.com/Friendly0Fire/GW2Radial/discussions/281 for help with this issue.

**Comment by dolour** [comment]
Same thing with Proton Experimental, which "used" to work fine. Guess some ARC update isnt playing nicely.
Cant test Lutris, since GW2 Steam accounts arent compatible with the standalone client.

**Comment by Friendly0Fire** [comment]
Sorry, your initial post mentions *chainloading*?

That hasn't been supported for ages, are you on the latest version?

**Comment by dolour** [comment]
First of all, that protontricks fix worked for GE-Proton9-5, so hooray. Weird that experimental wont budge...
So, big thanks! And secondly, i use the UOAOM and am on whatever version they push, but i had no idea CL isnt a thing.
Pretty much all games i play are VERY picky about the order in whick you load addons or mods, good lesson in not jumping to conclusions.

**Comment by Friendly0Fire** [comment]
Sounds good, glad to hear you got it fixed!
