### ISSUE TITLE
When on water, would like to see radial options instead of auto mounting skimmer.

### ISSUE THREAD

**Issue by emmetotter** [Friendly0Fire/GW2Radial#358]
**Is your feature request related to a problem? Please describe.**
I would like the ability to see the mount radial when floating on water and have the option to option to select my skiff or turtle or skimmer instead of giving no choice and automatically mounting the skimmer.

**Describe the solution you'd like**
Ideally I would like to see the 3 options possible to mount when floating on water: skimmer, turtle, skiff.  However, if that isn't possible I would accept seeing the full radial and if I select something I can't mount, that's on me.  At least that way I could select a skiff or turtle when those are actually options.

**Describe alternatives you've considered**
Tried disabling mounting skimmer underwater which does not enable a radial for when I'm floating ON the water.  I am still auto mounted on the skimmer

**Additional context**

**Comment by emmetotter** [comment]
I guess this is a feature only in the 2.3 _pre-release_ which is dated Oct 2022 and the latest actual release (which I had) was 2.2.1.  When will the pre-release become a release?

**Comment by Zyian** [comment]
Go ahead and use the pre-release, as Radial is going under some work behind the scenes, many people have used the pre-release without any issues.
