### ISSUE TITLE
Recognise the new Janthir Wilds flowing water type (mount activation)

### ISSUE THREAD

**Issue by Charybdis** [Friendly0Fire/GW2Radial#359]
**Is your feature request related to a problem? Please describe.**
The new Janthir Wilds expansion has introduced a new type of flowing water - one that isn't recognised by GW2Radial (using 2.3.0 pre 5).

An example location is Divinity's Falls POI, SE of the Moon Camp spawn location on the first map.

Thanks for taking a look!

**Describe the solution you'd like**
The flowing water is recognised as being on/under the water, so the mount selection for water mounts works again.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Charybdis** [comment]
Will look at the pre8 release (I'm a bit out of date apparently), but suspect it will still be there

**Comment by Friendly0Fire** [comment]
This is unfortunately impossible, sorry.
