### ISSUE TITLE
GW2 game client crashes on game exit with GW2 radial addon Version 2.3.0 Pre-release 8

### ISSUE THREAD

**Issue by emmetotter** [Friendly0Fire/GW2Radial#360]
**Describe the bug**
Since the Janthir expac was installed every time I exit gw2 I get the crash screen with Module: gw2addon_gw2radial.dll listed as the cause.

**To Reproduce**
1. Install the Version 2.3.0 Pre-release 8 of gw2 radial and the d3d9_wrapper v2.0_r21
2. Start gw2
3. At the character select screen, exit the game.  NOTE: I can play for hours and the same thing will eventually happen: crash on exit
4. GW2 Crash "notify anet" dialogue appears

**System configuration (please fill in):**
 - OS: Windows 11 Home 64-bit (10.0, Build 22631)
 - GPU: Nvidia GeForce GTX 1060 6GB
 - Chainloading, only gw2 radial and d3d9 wrapper

**Additional context**
Details from GW2 crash dialogue:

*--> Crash <--*
Exception: c0000005 
Memory at address 00007ffe`48ae0de8 could not be read
App: Gw2-64.exe 
Pid: 158528
BaseAddr: 00007FF6CB9C0000
ProgramId: 101
Build: 167239
Module: gw2addon_gw2radial.dll
When: 2024-08-21T12:42:23Z 2024-08-21T08:42:23-04:00
Uptime:   0 days  0:01:16
Flags: 0
DumpFile: Crash.dmp

*--> System <--*
Name: d9ade551
IpAddr: 192.168.1.185
Processors: 12 [GenuineIntel:6:14:10]
OSVersion: Windows 10.0 (64 bit)

*--> System Memory <--*
Physical: 16206MB avail/32574MB total  49% avail
Paged:    12582MB avail/34622MB total  36% avail
Virtual:  134175522MB avail/134217727MB total  3% avail
Load: 50%
CommitTotal:  22039MB
CommitLimit:  34622MB
CommitPeak:   27181MB
SystemCache:  15727MB
HandleCount:  226652
ProcessCount:   298
ThreadCount:   4950

*--> Process Memory <--*
Private:         3209MB
WorkingSet:      1662MB
PeakWorkingSet:  3324MB
PageFaults:   2321953

*--> Memory Category Usage (Inclusive) <--*
[Category]              [Size(MB)]  [Count]     
Root                    667.80      130955      
Programmer Data         600.40      76911       
Game                    370.95      38379       
Content                 296.48      37039       
Collections             128.23      3406        
Dictionary              126.77      469         
Text                    74.42       1329        
Uncategorized           60.85       53216       
Engine                  51.21       18363       
I/O                     40.50       632         
Archive                 39.16       38          
Gr                      36.23       991         
Gr Umbra                35.03       653         
Map                     11.24       15555       
Map Zone                11.10       15547       
Collide Havok           6.49        823         
Collide                 6.49        823         
Debugging               4.00        1           
UI                      3.64        244         
Audio                   3.59        154         
Frame                   2.07        69          
Services                1.33        15572       
File Service            1.24        12          
Gr Texture              1.03        31          

*--> Memory Category Usage (Exclusive) <--*
[Category]              [Size(MB)]  [Count]     
Content                 296.48      37039       
Dictionary              126.77      469         
Text                    74.42       1329        
Uncategorized           60.85       53216       
Archive                 39.16       38          
Gr Umbra                35.03       653         
Map Zone                11.10       15547       
Collide Havok           6.49        823         
Debugging               4.00        1           
Audio                   3.59        154         
Frame                   2.07        69          
UI                      1.55        152         
Services                1.33        15572       
File Service            1.24        12          
Gr Texture              1.03        31          
Collections             0.88        2903        
Msg                     0.36        93          
BTree                   0.32        28          
Set                     0.27        6           
Map                     0.13        8           
Event                   0.13        4           
Model-Programmer        0.11        16          
Asset Service           0.10        580         
Gr Transform            0.09        298         

*--> DllList <--*
00007FF6CB9C0000 - E:\Program Files\Guild Wars 2\Gw2-64.exe
00007FFE50970000 - C:\WINDOWS\SYSTEM32\ntdll.dll
00007FFE4FCC0000 - C:\WINDOWS\System32\KERNEL32.DLL
00007FFE4E2F0000 - C:\WINDOWS\System32\KERNELBASE.dll
00007FFE4F9D0000 - C:\WINDOWS\System32\USER32.dll
00007FFE4E000000 - C:\WINDOWS\System32\win32u.dll
00007FFE50570000 - C:\WINDOWS\System32\GDI32.dll
00007FFE4DD50000 - C:\WINDOWS\System32\gdi32full.dll
00007FFE4E1D0000 - C:\WINDOWS\System32\msvcp_win.dll
00007FFE4DE70000 - C:\WINDOWS\System32\ucrtbase.dll
00007FFE4FBF0000 - C:\WINDOWS\System32\ADVAPI32.dll
00007FFE4E6A0000 - C:\WINDOWS\System32\msvcrt.dll
00007FFE4F0B0000 - C:\WINDOWS\System32\sechost.dll
00007FFE4E1A0000 - C:\WINDOWS\System32\bcrypt.dll
00007FFE4EDB0000 - C:\WINDOWS\System32\RPCRT4.dll
00007FFE4EBD0000 - C:\WINDOWS\System32\WS2_32.dll
00007FFE4DF90000 - C:\WINDOWS\System32\WINTRUST.dll
00007FFE4F160000 - C:\WINDOWS\System32\SHELL32.dll
00007FFE4CA40000 - C:\WINDOWS\SYSTEM32\WTSAPI32.dll
00007FFE46E60000 - C:\WINDOWS\SYSTEM32\WINMM.dll
00007FFE488C0000 - C:\WINDOWS\SYSTEM32\VERSION.dll
00007FFE50760000 - C:\WINDOWS\System32\ole32.dll
00007FFE4E840000 - C:\WINDOWS\System32\combase.dll
00007FFE4FD90000 - C:\WINDOWS\System32\OLEAUT32.dll
00007FFE4E750000 - C:\WINDOWS\System32\IMM32.dll
00007FFE4E030000 - C:\WINDOWS\System32\CRYPT32.dll
00007FFE407A0000 - C:\WINDOWS\SYSTEM32\MSIMG32.dll
00007FFE3BAC0000 - C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.3527_none_b43b7f4b638cc64f\COMCTL32.dll
00007FFDF3860000 - C:\WINDOWS\SYSTEM32\USP10.dll
00007FFE405E0000 - C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.22621.3810_none_57f8d842ce19d879\gdiplus.dll
00007FFE35EA0000 - C:\WINDOWS\SYSTEM32\MSACM32.dll
00007FFE4CA60000 - C:\WINDOWS\SYSTEM32\Secur32.dll
00007FFE4CEE0000 - C:\WINDOWS\SYSTEM32\SSPICLI.DLL
00007FFE4D8A0000 - C:\WINDOWS\SYSTEM32\MSASN1.dll
00007FFE39AA0000 - C:\WINDOWS\SYSTEM32\dbghelp.dll
00007FFE4E270000 - C:\WINDOWS\System32\bcryptPrimitives.dll
00007FFE4BB90000 - C:\WINDOWS\SYSTEM32\windows.storage.dll
00007FFE4BA50000 - C:\WINDOWS\SYSTEM32\wintypes.dll
00007FFE4FF10000 - C:\WINDOWS\System32\SHCORE.dll
00007FFE4FB90000 - C:\WINDOWS\System32\shlwapi.dll
00007FFE4DBC0000 - C:\WINDOWS\SYSTEM32\profapi.dll
00007FFE4CC80000 - C:\WINDOWS\SYSTEM32\kernel.appcore.dll
00007FFE4D8C0000 - C:\WINDOWS\SYSTEM32\DEVOBJ.dll
00007FFE4D8F0000 - C:\WINDOWS\SYSTEM32\cfgmgr32.dll
00007FFE4B2A0000 - C:\WINDOWS\SYSTEM32\dxcore.dll
00007FFE4B1A0000 - C:\WINDOWS\system32\uxtheme.dll
00007FFE44FB0000 - C:\WINDOWS\SYSTEM32\cryptnet.dll
00007FFE4D2F0000 - C:\WINDOWS\SYSTEM32\cryptbase.dll
00007FFE50910000 - C:\WINDOWS\System32\imagehlp.dll
00007FFE4D360000 - C:\WINDOWS\SYSTEM32\CRYPTSP.dll
00007FFE4CBE0000 - C:\WINDOWS\system32\rsaenh.dll
00007FFE4D420000 - C:\WINDOWS\SYSTEM32\wldp.dll
00007FFE44560000 - C:\WINDOWS\SYSTEM32\drvstore.dll
00007FFDF0240000 - C:\WINDOWS\system32\nvspcap64.dll
00007FFE4CCA0000 - C:\WINDOWS\SYSTEM32\ntmarta.dll
00007FFE4D150000 - C:\WINDOWS\SYSTEM32\gpapi.dll
00007FFDF00E0000 - C:\WINDOWS\System32\DriverStore\FileRepository\nvddsi.inf_amd64_bab961ac9981a58c\nvppex.dll
00007FFE506B0000 - C:\WINDOWS\System32\clbcatq.dll
00007FFE19250000 - C:\WINDOWS\system32\napinsp.dll
00007FFE19230000 - C:\WINDOWS\system32\pnrpnsp.dll
00007FFE4D0E0000 - C:\WINDOWS\System32\mswsock.dll
00007FFE4C760000 - C:\WINDOWS\SYSTEM32\DNSAPI.dll
00007FFE4C6F0000 - C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
00007FFE4FE70000 - C:\WINDOWS\System32\NSI.dll
00007FFE19210000 - C:\WINDOWS\System32\winrnr.dll
00007FFE45650000 - C:\WINDOWS\system32\wshbth.dll
00007FFE191E0000 - C:\WINDOWS\system32\nlansp_c.dll
00007FFE45840000 - C:\WINDOWS\System32\fwpuclnt.dll
00007FFE43690000 - C:\Windows\System32\rasadhlp.dll
00007FFE4EC50000 - C:\WINDOWS\System32\msctf.dll
00007FFE3C5B0000 - C:\WINDOWS\SYSTEM32\textinputframework.dll
00007FFE4AFA0000 - C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
00007FFE13B80000 - C:\WINDOWS\system32\explorerframe.dll
00007FFE436C0000 - C:\WINDOWS\SYSTEM32\TextShaping.dll
00007FFD70280000 - E:\Program Files\Guild Wars 2\bin64\cef\libcef.dll
00007FFE505B0000 - C:\WINDOWS\System32\COMDLG32.dll
00007FFE4A130000 - E:\Program Files\Guild Wars 2\bin64\cef\dxgi.dll
00007FFE4AAD0000 - C:\WINDOWS\SYSTEM32\PROPSYS.dll
00007FFE1A930000 - C:\WINDOWS\SYSTEM32\UIAutomationCore.DLL
00007FFE3C9E0000 - C:\WINDOWS\SYSTEM32\OLEACC.dll
00007FFE4D180000 - C:\WINDOWS\SYSTEM32\USERENV.dll
00007FFE34360000 - C:\WINDOWS\SYSTEM32\NETAPI32.dll
00007FFE47FA0000 - C:\WINDOWS\SYSTEM32\DWrite.dll
00007FFE4C490000 - C:\WINDOWS\SYSTEM32\HID.DLL
00007FFE4B4F0000 - C:\WINDOWS\SYSTEM32\dwmapi.dll
00007FFDFD470000 - E:\Program Files\Guild Wars 2\bin64\cef\chrome_elf.dll
00007FFE46140000 - C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
00007FFE22EE0000 - C:\WINDOWS\SYSTEM32\d3d9.dll
00007FFE4D530000 - C:\WINDOWS\SYSTEM32\ncrypt.dll
00007FFE2D670000 - C:\WINDOWS\SYSTEM32\CRYPTUI.dll
00007FFE34550000 - C:\WINDOWS\SYSTEM32\urlmon.dll
00007FFE474C0000 - C:\WINDOWS\SYSTEM32\WINHTTP.dll
00007FFE35DA0000 - C:\WINDOWS\SYSTEM32\dxva2.dll
00007FFDF2D70000 - C:\WINDOWS\SYSTEM32\credui.dll
00007FFE47410000 - C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
00007FFE46EA0000 - C:\WINDOWS\SYSTEM32\wevtapi.dll
00007FFE45B80000 - C:\WINDOWS\SYSTEM32\WININET.dll
00007FFE26EB0000 - C:\WINDOWS\SYSTEM32\ESENT.dll
00007FFE34390000 - C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
00007FFE30F50000 - C:\WINDOWS\SYSTEM32\iertutil.dll
00007FFE34290000 - C:\WINDOWS\SYSTEM32\srvcli.dll
00007FFE4C6E0000 - C:\WINDOWS\SYSTEM32\netutils.dll
00007FFE4C8B0000 - C:\WINDOWS\SYSTEM32\DSROLE.DLL
00007FFE466E0000 - C:\WINDOWS\SYSTEM32\WKSCLI.DLL
00007FFE41CC0000 - C:\WINDOWS\SYSTEM32\SAMCLI.DLL
00007FFE4D4F0000 - C:\WINDOWS\SYSTEM32\NTASN1.dll
00007FFE4D960000 - C:\WINDOWS\SYSTEM32\DPAPI.dll
00007FFE479E0000 - C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
00007FFE4D830000 - C:\WINDOWS\SYSTEM32\WINSTA.dll
00007FFE432B0000 - C:\WINDOWS\System32\MMDevApi.dll
00007FFE42DC0000 - C:\WINDOWS\SYSTEM32\mscms.dll
00007FFE44A60000 - C:\WINDOWS\SYSTEM32\icm32.dll
00007FFE47600000 - C:\WINDOWS\SYSTEM32\DSREG.DLL
00007FFE4D9A0000 - C:\WINDOWS\SYSTEM32\POWRPROF.dll
00007FFE4D980000 - C:\WINDOWS\SYSTEM32\UMPDC.dll
00007FFE49850000 - C:\WINDOWS\System32\CoreMessaging.dll
00007FFE50010000 - C:\WINDOWS\System32\SETUPAPI.dll
00007FFE35D80000 - E:\Program Files\Guild Wars 2\addonLoader.dll
00007FFE34200000 - C:\WINDOWS\SYSTEM32\MSVCP140.dll
00007FFE33FE0000 - C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
00007FFE17760000 - E:\Program Files\Guild Wars 2\addons\d3d9_wrapper\gw2addon_d3d9_wrapper.dll
00007FFD98C20000 - E:\Program Files\Guild Wars 2\addons\gw2radial\gw2addon_gw2radial.dll
00007FFE47AA0000 - C:\WINDOWS\SYSTEM32\D3DCOMPILER_47.dll
00007FFE4B2E0000 - C:\WINDOWS\system32\dxgi.dll
00007FFE454D0000 - C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
00007FFE43860000 - C:\WINDOWS\System32\DriverStore\FileRepository\nvddsi.inf_amd64_bab961ac9981a58c\nvldumdx.dll
00007FFE37AB0000 - C:\WINDOWS\System32\DriverStore\FileRepository\nvddsi.inf_amd64_bab961ac9981a58c\nvgpucomp64.dll
00007FFE41960000 - C:\WINDOWS\System32\DriverStore\FileRepository\nvddsi.inf_amd64_bab961ac9981a58c\Display.NvContainer\NvMessageBus.dll
00007FFE02430000 - C:\WINDOWS\System32\DriverStore\FileRepository\nvddsi.inf_amd64_bab961ac9981a58c\nvwgf2umx.dll
00007FFE49010000 - C:\WINDOWS\SYSTEM32\dcomp.dll
00007FFE274D0000 - C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll
00007FFE4AF90000 - C:\WINDOWS\SYSTEM32\WINNSI.DLL
00007FFE4CAE0000 - C:\WINDOWS\system32\schannel.DLL
00007FFE33FB0000 - C:\WINDOWS\system32\ncryptsslp.dll
00007FFDED3B0000 - C:\Users\Steve\AppData\Local\Discord\app-1.0.9158\modules\discord_hook-1\discord_hook\3c707a899ed380\DiscordHook64.dll
00007FFE081B0000 - C:\WINDOWS\SYSTEM32\winmmbase.dll
00007FFE14F00000 - C:\WINDOWS\SYSTEM32\wdmaud.drv
00007FFE47A00000 - C:\WINDOWS\SYSTEM32\AVRT.dll
00007FFE34740000 - C:\WINDOWS\SYSTEM32\ksuser.dll
00007FFE3C350000 - C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
00007FFE48E20000 - C:\WINDOWS\SYSTEM32\msacm32.drv
00007FFE47010000 - C:\WINDOWS\SYSTEM32\midimap.dll
00007FFE4B740000 - C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
00007FFE3DC30000 - C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
00007FFE32020000 - C:\WINDOWS\SYSTEM32\dbgcore.DLL

[DbgHelp.dll is C:\WINDOWS\SYSTEM32\dbghelp.dll]
[DbgHelp.dll version 6.2.22621.3593 (64/32-bit compatible)]

*--> ClientContextThreadProc Thread 0x26df4 <--*

*--> Trace <--*
Pc                Rt                : Args
00007ffd`98c4423c 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffd`98c40760 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffd`98c24fbb 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffd`98c6b540 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffd`98c6b7b7 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffe`3badd7bc 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffe`3badd65c 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffe`4f9e82e1 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffe`4f9e7f9c 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffe`4f9f6bb2 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffe`50a13fe4 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffe`4e002754 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`cbcd8bc3 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`cbc9f6c9 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`cbc454d2 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`cbc45754 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`ccb25e1c 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`cbeb3b38 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`cbc0304a 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`cbeb3f85 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`cbeb5207 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`cbeb52d6 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`cbeb3795 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`cbc387cd 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff6`cbe73c52 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffe`4fcd257d 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffe`509caf28 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 

*--> Thread registers <--*
rax=00007ffe48ae0dd8 rbx=000001bcaaf530f0 rcx=000001bcaaf47498
rdx=0000000b9e3ff400 rsi=00000000ffffffff rdi=000001bca9eb1880
rip=00007ffd98c4423c rsp=0000000b9e3ff470 rbp=0000000000000000
 r8=000001bc98227c80  r9=0000000000000001 r10=0000000000000003
r11=0000000b9e3ff380 r12=0000000000000082 r13=0000000000bc0ca6
r14=0000000b9e3ff708 r15=0000000000000000
cs=0033 ss=002b ds=002b es=002b fs=0053 gs=002b efl=00010202

rbx-32 000001BCAAF530D0  c1000000`41e00000 00000001`000284d5 00000000`00000000 90000b8d`bcc87fb0 
rbx +0 000001BCAAF530F0  00007ffd`98d93e48 00000002`00000003 000001bc`ab35e7f0 3f03416d`3ecced9a 
rbx+32 000001BCAAF53110  3f800000`3f9b76e9 3e4ccccd`465f45c0 3f800000`00000007 00000000`00000000 
rcx-32 000001BCAAF47478  00000000`00000000 00000000`00000000 00000000`00000000 00007ffe`48ada3e0 
rcx +0 000001BCAAF47498  00007ffe`48ae0dd8 00000000`00000000 00000000`00000000 00000000`00000000 
rcx+32 000001BCAAF474B8  00007ffe`48ad9ff8 00000000`00000000 00000000`00000000 00000000`00000000 
rdx-32 0000000B9E3FF3E0  000001bc`a9eb1880 00007ffd`98d34cc0 00000000`00000000 000001bc`ab2d7180 
rdx +0 0000000B9E3FF400  00000000`00000000 00007ffd`98c4add6 00000000`00000000 00007ffd`98c41906 
rdx+32 0000000B9E3FF420  000001bc`a9c5271f 00000000`00000000 000001bc`a9eab7c0 00007ffd`98c4480e 
 r8-32 000001BC98227C60  00000011`00005e0d 000f0001`0000032e 00000000`0000001b 00000000`00000000 
 r8 +0 000001BC98227C80  000001bc`98220de0 000001bd`807d8c90 000001bd`8833b7a0 000001bd`36d09320 
 r8+32 000001BC98227CA0  000001bc`fb425120 000001bc`ab923ae0 000001bd`2052c4c0 000001bd`10373d70 

*--> Code <--*
00007ffd`98c4421c  488b0348 8bcbff50 0890488b 8f480e00 H..H...P..H..H..
00007ffd`98c4422c  004885c9 740e4889 af480e00 00488b01 .H..t.H..H...H..
00007ffd`98c4423c  ff501090 488b8f40 0e000048 85c9740e .P..H..@...H..t.
00007ffd`98c4424c  4889af40 0e000048 8b01ff50 1090488b H..@...H...P..H.
00007ffd`98c4425c  8f380e00 004885c9 740e4889 af380e00 .8...H..t.H..8..
00007ffd`98c4426c  00488b01 ff501090 488b9f18 0e000048 .H...P..H......H

*--> Stack <--*
0000000b`9e3ff470  0000000b`9e3ff708 000001bc`aa3ce950 000001bc`a9eb1880 00000000`00000000 ..?.....P.<.....................
0000000b`9e3ff490  00007ffd`98d93d08 000001bc`a9eb1880 000001bc`a9c52720 00007ffd`98c3bb22 .=.............. '......".......
0000000b`9e3ff4b0  000001bc`a9c52710 000001bc`983d0000 00000000`00000000 00000000`00000000 .'........=.....................
0000000b`9e3ff4d0  00007ffd`98d93d78 000001bc`a9eb1880 000001bc`aa3d5c28 00007ffd`98d34cc0 x=..............(\=......L......
0000000b`9e3ff4f0  000001bc`aa3ce950 00000000`00bc0ca6 0000000b`9e3ff708 0000000b`9e3ff4d0 P.<...............?.......?.....
0000000b`9e3ff510  00000000`00000001 00007ffd`98c40760 00000000`ffffffff 000001bc`aa3ce950 ........`...............P.<.....
0000000b`9e3ff530  00000000`00000000 000001bc`a9eb1880 000001bc`aaf35730 00007ffd`98c24fbb ................0W.......O......
0000000b`9e3ff550  000001bc`aa3ce950 000001bc`aa3ce970 00000000`ffffffff 00000000`00000000 P.<.....p.<.....................
0000000b`9e3ff570  00000000`00000082 00007ffd`98c6b540 00000000`00000082 000001bc`aaf35730 ........@...............0W......
0000000b`9e3ff590  00000000`00000000 00000000`00bc0ca6 00000000`00000082 00007ffd`98c6b7b7 ................................
0000000b`9e3ff5b0  0000000b`9e3ff700 00000000`00bc0ca6 0000000b`9e3ff700 00007ffe`4ec88349 ..?...............?.....I..N....
0000000b`9e3ff5d0  ffffffff`fffffffe 00007ffe`4f9eaba9 000001bc`9a475160 000001bc`00000082 ...........O....`QG.............
0000000b`9e3ff5f0  00000000`00000000 00000000`00000000 0000a746`858d7b49 00000000`00000000 ................I{..F...........
0000000b`9e3ff610  00000000`00000001 0000000b`9e3ff704 0000000b`9e3ff700 00007ffe`3badd7bc ..........?.......?........;....
0000000b`9e3ff630  00000000`00000000 00000000`00bc0ca6 0000000b`9e3ff6e9 00000000`fffffffe ..................?.............
0000000b`9e3ff650  00000000`00000000 00000000`00000000 00000000`00000000 00007ffe`4b1b6079 ........................y`.K....
0000000b`9e3ff670  00000000`00000000 0000000b`9e3ff700 0000000b`9e3ff704 0000000b`9e3ff708 ..........?.......?.......?.....
0000000b`9e3ff690  00000000`00000000 00000000`00000082 00000000`00000000 00000000`00000001 ................................
0000000b`9e3ff6b0  00000000`00000000 00007ffe`3badd65c 00000000`00000001 00000000`00000000 ........\..;....................
0000000b`9e3ff6d0  00000000`00bc0ca6 00000000`00000000 00000000`00000000 00000000`00000000 ................................
0000000b`9e3ff6f0  000001bc`aa0d3200 00000000`00000000 00000002`00000002 00000000`00000000 .2..............................
0000000b`9e3ff710  000001bc`aa0d3200 00000000`00000001 00000000`00000000 00000000`00000082 .2..............................
0000000b`9e3ff730  00000000`00000001 00007ffe`4f9e82e1 00000000`00bc0ca6 00000000`00000082 ...........O....................
0000000b`9e3ff750  00000000`00000000 00000000`80000012 0000000b`9e3ff788 0000000b`9e3ff7a8 ..................?.......?.....
0000000b`9e3ff770  00002fc4`ecb4936c 000001bc`80000012 00000000`00000000 00000000`00000000 l..../..........................
0000000b`9e3ff790  00000001`00000000 00000000`80000012 00000000`00000004 00000000`00000000 ................................
0000000b`9e3ff7b0  00000000`00000000 00007ffe`4ec76e17 000001bc`99cb8c1f 00000000`00000018 .........n.N....................
0000000b`9e3ff7d0  00000000`00000001 000001bc`9ecf3a30 000001bc`00000001 00000000`0000f718 ........0:......................
0000000b`9e3ff7f0  00000001`00002a31 000001bc`98220000 00000000`00000048 00007ffe`00000001 1*........".....H...............
0000000b`9e3ff810  00000000`00000000 00000000`00000000 00000000`00000048 ffffffff`00000001 ................H...............
0000000b`9e3ff830  00000000`00000000 00000000`00000000 00000000`00000030 ffffffff`ffffffff ................0...............
0000000b`9e3ff850  ffffffff`ffffffff 00007ffe`4f9e8137 00000000`00000000 00000000`00000000 ........7..O....................

*--> Error Logs <--*
12:41:34Z The user closed the browser.
12:41:34Z The browser is being closed.
12:41:34Z We are requesting CEF close the browser when the user closed the browser.
12:41:34Z The user closed the browser.
12:41:34Z CEF is closing the browser.
12:41:39Z The user closed the browser.
12:41:39Z The browser is being closed.
12:41:39Z We are requesting CEF close the browser when the user closed the browser.
12:41:39Z CEF is closing the browser.
12:41:40Z NULL REWARD TRACK: 0176140D-4175-E211-8756-78E7D1936222
12:41:40Z NULL REWARD TRACK: 0176140D-4175-E211-8756-78E7D1936222
12:41:59Z The user closed the browser.
12:41:59Z The browser is being closed.
12:41:59Z We are requesting CEF close the browser when the user closed the browser.
12:41:59Z CEF is closing the browser.
Crashed at 12:42:24Z

*--> Graphics Device Info <--*
VendorId    = 0x10de
DeviceId    = 0x1c03
Version     = 56081
Description = NVIDIA GeForce GTX 1060 6GB
Compat      = 0x000000003f77fc3f
VidMem      = 6144 MB

*--> NVidia Info <--*
DriverVersion = 560.81

**Comment by emmetotter** [comment]
The issue does not occur with GW2 Radial Version 2.2.1

**Comment by Friendly0Fire** [comment]
Does it occur with the pre-release?

**Comment by emmetotter** [comment]
I just installed v2.4.0-pre1 today, configured mounts, markers and object markers and tried all of them in various combinations and experienced no issues and certainly no crashes.
Thanks!
