### ISSUE TITLE
Custom Wheel not showing tabs

### ISSUE THREAD

**Issue by s0soking** [Friendly0Fire/GW2Radial#361]
So I've created the new custom folder and added the config.ini file with everything it needs, but when I click on “Reload custom wheels” I don't get any new tabs.

I'm using the latest pre-release version of gw2 radial → Version 2.3.0 Pre-release 8

Any work around to this ?

**Comment by DarthMaul22** [comment]
What does your folder structure look like? Each custom wheel needs to be in its own folder _within_ the "custom" folder, e.g. `custom/My_Wheel/config.ini`
