### ISSUE TITLE
Using Warclaw/Skyscale in combat

### ISSUE THREAD

**Issue by hokm** [Friendly0Fire/GW2Radial#363]
**Is your feature request related to a problem? Please describe.**
With SoTO and Janthir Wilds expansions, we can use Warclaw and Skyscale mounts in combat, however with GW2 radial no mount can be used in combat.

**Describe the solution you'd like**
Selecting mount in GW2 Radial should attempt to mount-up and not blocking it when player is in combat.
Queuing mount when player can't use it should periodically try to mount-up desired mount even if player is still in combat.

**Describe alternatives you've considered**
Combat check could be used to show only combat mounts in radial while player is in combat. (even better if it could determine if combat mount-up is on cooldown or not, but I am not sure if that's even possible)

**Additional context**
Mounting up in combat has some cooldown. For Skyscale it is 180s, for Warclaw cooldown depending on how often it is used within some time period.
Mounting up in combat is possible only if player is not attacking.

**Comment by Friendly0Fire** [comment]
See the current pre-release.

**Comment by hokm** [comment]
Oh sorry, I didn't notice there are closed issues same like this (i checked only open issues) and that new pre-release version has this already implemented. I just tried it and it works very well.
