### ISSUE TITLE
Game freezes temporarily on losing focus with v2.4

### ISSUE THREAD

**Issue by Draconicrose** [Friendly0Fire/GW2Radial#367]
**Describe the bug**
Playing GW2 on a multimonitor system as windowed fullscreen and mouse focus, when I move the mouse out of the GW2 window and back again, GW2 freezes for a few seconds before resuming.

**To Reproduce**
1. Have GW2 on windowed fullscreen and window focus set to follow mouse
2. Move mouse out of the GW2 screen into another one and back to GW2
3. Game freezes for a few seconds

**Expected behavior**
The game continues as normal.

**System configuration (please fill in):**
 - OS: Linux Mint 22 (Proton 8.0-5)
 - GPU: GTX 1660

**Additional context**
Steam launch options: LD_PRELOAD="" __GL_SHADER_DISK_CACHE=1 gamemoderun %command% -provider Portal -autologin

**Comment by Friendly0Fire** [comment]
Sorry, I do not directly support Linux, especially when it comes to window manager issues. There's a ­[discussion](https://github.com/Friendly0Fire/GW2Radial/discussions/281) for Linux users which has been helpful in the past.

**Comment by Draconicrose** [comment]
I'll keep using version 2.2 then. Too bad, the changes to combat mounting were good.
