### ISSUE TITLE
Chainloading Broken

### ISSUE THREAD

**Issue by MuttMeat** [Friendly0Fire/GW2Radial#68]
Since the last update, `d3d9_mchain.dll` is no longer registered in the chainloading process. The chainload sequence offered in the README file, while technically operational, gives me the following error message upon exiting, while the chainload sequence in the previous version with ArcDPS as `d3d9_mchain.dll` does not.

> 
> Jan 10 14:26:34 arcdps 20190109.150520-283-x64
> Jan 10 14:26:35 client: gw2 0x13FE10000-0x142306000 (0x9B0A0603)
> Jan 10 14:26:35 client: arcdps 0x7FEF0890000-0x7FEF0938000 (0x6E8A4300)
> Jan 10 14:26:35 client: d3d9 0x7FEF9FE0000-0x7FEF9FEA000 (0x5D3EEBD7)
> Jan 10 14:26:36 extensions: buildtemplates 0x7FEF9A60000-0x7FEF9A73000 (20190108.132025-282-x64, 0x794F7BD5)
> Jan 10 14:26:36 extensions: extras 0x7FEF9B80000-0x7FEF9BA6000 (20190108.132025-282-x64, 0x0714A933)
> Jan 10 14:26:36 extensions: Boon Table 0x7FEDEAE0000-0x7FEDEB14000 (0.1, 0xE259A1DE)
> Jan 10 14:26:36 config: loading from "C:\Games\Guild Wars 2\addons\arcdps\arcdps.ini"

**Comment by Friendly0Fire** [comment]
Check if the new version fixes it.
