### ISSUE TITLE
Problem with Arcdps, D912pxy and Radial mount

### ISSUE THREAD

**Issue by loqi93** [Friendly0Fire/GW2Radial#79]
Hi! im trying run arcdps, d912pxy and radial mount but i dont get it. 
D912pxy and arcdps work now (arcdps is d3d9.dll and d912pxy is d3d9_chainload.dll) 
but when i try to put radial mount the game no run.
i tried this form:
arcdps: d3d9_chain.dll
radial mount: d3d9.dll
d912pxy: d3d9_chainload.dll
How can i rename the files? 
Thanks!!!

**Comment by majorglory07** [comment]
I've gotten close using this:
ArcDPS: d3d9.dll
Radial Mount Menu: d3d9_chainload.dll
d912pxy: d3d9_mchain.dll

This seems to load both ArcDPS and d912pxy fine, but only loads some of Radial Mount Menu. The mount settings menu wont open with Shift+Alt+M. My mouse snaps to the middle when I press my mount hotkey, but no menu appears and char does not mount.

**Comment by Friendly0Fire** [comment]
Sorry, I will not be supporting the D3D12 proxy.
