### ISSUE TITLE
Stuck on Welcome Message. 

### ISSUE THREAD

**Issue by Flavourized** [Friendly0Fire/GW2Radial#82]
**Describe the bug**
Welcome msg is stuck on screen. I installed gw2radial (coming from gw2mounts). The welcome msg is currently stuck on my screen. I cannot click it to make it go away, the Shift + alt + m key bind does not work.. 

**To Reproduce**
1. Welcome msg..

**Expected behavior**
Expect to be able to click the welcome msg.. I have tried going in imgui config and setting collapsed to1, and it didnt work. 

**Screenshots**
http://prntscr.com/mjw8pl  - No matter where on the screen window i click, it doesnt go away. Tried keybind, tried enter, tried escape, cant figure it out.

**System configuration (please fill in):**
 - OS: win10
 - GPU: gtx 1080 
 - Chainloading: gw2Radial (d3d9) -> Arcdps (d3d9_mchain + d3d9_chainload) -> reshade (ReShade64)

**Additional context**
None

**Comment by Flavourized** [comment]
Just going to go back to gw2mounts for now, let me know if there is something i can do to fix this.

**Comment by Flavourized** [comment]
oh gw2mounts doesnt work on the current build..

**Comment by Friendly0Fire** [comment]
Looks like your resolution is low enough that the OK button overlaps the URL button which I guess confuses imgui. I'll have a look at that, thanks for the report.

In the meantime, you can edit the config manually. Go into `Guild Wars 2/addons/gw2radial` and open `config.ini`. You'll want to add the following:
```ini
[Core]
first_message_shown_v1 = true
```
or, if the `[Core]` block already exists, add the line to that existing block.

**Comment by Flavourized** [comment]
Okay, that worked, however now i am encountering another issue.. The other issue is that the in-game keybind does not work. 

```
[Core]
first_message_shown_v1 = true
```

When i remove this from `config.ini`, I see the welcome message. But if i add it, the keybind does not work for me. Any idea, kinda stumped. 

Here is a screenshot of my settings; https://prnt.sc/mksbrp

I play 1080p

**Comment by Friendly0Fire** [comment]
I can't really see what'd cause this. Could you have some kind of software running in the background which'd intercept/modify key inputs or rendering?

**Comment by Flavourized** [comment]
Sorry for the late reply! Using the chain method in your readme did the trick, thanks!

I initially installed it using one of the youtube videos, sorry about that.

**Comment by Friendly0Fire** [comment]
No worries, glad it's fixed!
