### ISSUE TITLE
It won't work...

### ISSUE THREAD

**Issue by EnkiduNaho** [Friendly0Fire/GW2Radial#86]
So, as many others, the Hotkeys won't work. The only difference is, that i have a Mac.
I also managed to put the dll in the bin64 (won't work) and one above (won't work too).
hotkey are bound elsewhere, as said and i don't know what i am doing wrong... please help i am struggling with the normal options and would love to try the Radial out!

**Comment by Friendly0Fire** [comment]
I'm afraid I can't debug anything with a Mac, since this is all Windows-specific hooking.
