### ISSUE TITLE
How to enable the WvW location

### ISSUE THREAD

**Issue by ArdiVeftvohl** [Friendly0Fire/GW2Radial#87]
I have the new version of the addon installed however I have no idea how to make addon hide all the other mounts while being in WvW.

If it's supposed to happen automaticly then it's currently not working for me. I'm standing with my character in WvW but it is still showing me all the mounts.

**Comment by Friendly0Fire** [comment]
I just went to various locations in WvW and it's working fine here. Are you sure you updated correctly? Which map did you go to?

**Comment by ArdiVeftvohl** [comment]
odd, I was on the deso border, alpine borderlands. I'll have another go tomorrow

**Comment by dameischta** [comment]
the same for me: [https://ibb.co/DQsjBT9](https://ibb.co/DQsjBT9)

**Comment by Friendly0Fire** [comment]
Out of curiosity, are you both using non-English versions of the game?

**Comment by dameischta** [comment]
switched to english (and restarted the client, just to be safe): all mounts are still displayed

**Comment by AlberGonAcosta** [comment]
I'm experiencing the same problem. I have the game on spanish and all mounts are showing up on alpine borderlands

**Comment by ArdiVeftvohl** [comment]
I am on the english version

**Comment by ThermoMan** [comment]
I'm on English version and I see all mounts in WvW.  My home is blue and I'm on green.  I have not looked on others.  Warclaw works though

**Comment by Friendly0Fire** [comment]
Hotfix released, should all be good now!
