### ISSUE TITLE
How to install new version

### ISSUE THREAD

**Issue by ImKitta** [Friendly0Fire/GW2Radial#88]
I cannot find the d3d9.dll file in this new version (update for warclaw) and there doesn't seem to be instructions on what to do with the new files. I'm really sorry with the waste of time this might be but I've looked through all of the folders and there are no dll file. Thank you a lot for your hard work and time!

**Comment by ThermoMan** [comment]
The file is not where you were looking.  On the main page under "Installatin" there is a link to the latest COMPILED version.  That link points at https://github.com/Friendly0Fire/GW2Radial/releases/latest
There you will find a ZIP file and it has only two things.  A readme with instructions and the d3d9.dll

**Comment by ImKitta** [comment]
Ah, now I feel a bit stupid but I appreciate the help. Thank you!

**Comment by Friendly0Fire** [comment]
Glad to hear everything's good!
