### ISSUE TITLE
After WarClaw Installation Only WarClaw shows In Menu

### ISSUE THREAD

**Issue by Stanty86** [Friendly0Fire/GW2Radial#89]
After installing the newest update for the warclaw I have a problem with the radial menu. The warclaw will show there but no other mounts will.

the settings menu system works and I tried changing the keybinds to something else (num pad) and every mount is checked as on in the visibility menu. One strange thing is all the mounts except the war claw are in italics. 

I've double checked all the hotkey match up in both the GW2 settings and Radial Mount Settings.

Something else I noticed, but this may be of no consequence, when I set the hotkeys in previous versions of radial mount my character would mount in game as I did it. So for example num 1 would be springer, when I assigned that in the radial settings menu he'd mount the springer. This no longer happens.

To install the new version, I overwrite the old one, which due to other mods was named d3d9_chainload.dll

**System configuration (please fill in):**
 - OS:  Windows 10
 - GPU: GTX1070
 - Chainloading: 
I have ArcDPS as d3d9.dll
then radial mount as d3d9_chainload.dll
and also GW2Hook as d3d9_mchain.dll

All the mods work correctly as far as I can tell, except for the radial menu.
![Capture](https://user-images.githubusercontent.com/48498810/54244190-627c5c80-4523-11e9-93e7-61ed55552550.PNG)
![Capture2](https://user-images.githubusercontent.com/48498810/54244191-627c5c80-4523-11e9-855d-f9c71b1a3a3b.PNG)

**Comment by Friendly0Fire** [comment]
Hotfix released, should all be good now!
