### ISSUE TITLE
Game forgets previous radial menu selection when losing focus

### ISSUE THREAD

**Issue by Adulka** [Friendly0Fire/GW2Radial#90]
**To Reproduce**
1. Go in-game and press Alt+Shift+M
2. Select Mounts tab
3. Set show in center hotkey
4. Set center behavior: previous
5. Close menu
6. Hold down center hotkey and select a mount
7. Check whether the game remembers your choice
8. Alt-tab out
9. Alt-tab back to GW2
10. Check whether the game remembers your choice

**Observed behavior**
Choice is not remembered after after alt-tab.

**Expected behavior**
The game should remember mount choice after alt-tab.

**System configuration**
 - OS: Windows 7
 - GPU: GTX970

**Comment by Friendly0Fire** [comment]
If you alt-tab while playing in full screen, the addon has to fully unload itself because of how DirectX 9 works. I'm afraid you'd have to play in (borderless) windowed mode to circumvent that issue.

**Comment by Adulka** [comment]
Thanks for the response! For me, the issue persists after I switch to windowed fullscreen, even if I switch to (fully) windowed mode. As soon as the game loses focus the last mount choice is gone is gone from the wheel.

**Comment by Friendly0Fire** [comment]
Hmm, in that case, let me investigate.
