### ISSUE TITLE
Stand Alone .dll file for Auto Updating?

### ISSUE THREAD

**Issue by Mythykle-Mythryndyr-Fs** [Friendly0Fire/GW2Radial#91]
Hello, 
I was wondering if you would be able to make the .dll file downloadable as a standalone file (NOT Zipped etc ). To allow auto updating of this addon via Guild Lounge addon, and such. :)
Link to Guild Lounge if you have not heard of it yet ---- >   https://guildlounge.com/

**Comment by Friendly0Fire** [comment]
I'm afraid I insist on the readme being included with the addon for various reasons. If you want to support this addon with auto-updates, you'll have to automate ZIP file extraction as well. Sorry.
