### ISSUE TITLE
Mount wheel not visible in Silverwastes map

### ISSUE THREAD

**Issue by Mac-Dino** [Friendly0Fire/GW2Radial#93]
After I installed the latest version (warclaw update), the wheel works normally on most maps.

Only on Silverwastes the whell does not show. It also always chooses the favorite mount, no matter in what direction I press.

Going back to the old Version (prior warclaw) brings back the wheel on all maps.

**Comment by Friendly0Fire** [comment]
You need to download the latest hotfix which already fixes this issue.

**Comment by Mac-Dino** [comment]
Sorry that I didn't see the hotfix was already available.
Thanks for the great work!
