### ISSUE TITLE
Setting up the Middle of the Wheel to dismount

### ISSUE THREAD

**Issue by VadoZhadar** [Friendly0Fire/GW2Radial#96]
Hey there!
Thanks so much for this awesome little gadget! :)
I've been wondering. I've been using the small mouse centered menu. Whenever I want to dismount, the way in doing it seems wonky, because you have to move your mouse again. But could you make the center of the wheel the dismounting section, so that you would only have to use the button to get the wheel and since the mouse is already centered on it, releasing the button would quickly dismount you just like that? I think in previous versions there was a mount area in the center, which should have the same effect. Is there any reason, why this has been changed?
Thanks for any insight you could give! :)
Cheers!
VadoZhadar

**Comment by Friendly0Fire** [comment]
There's unfortunately no "dismount" keybind in the game, so the best you can do is set the center of the wheel to trigger a favorite mount and pick any mount you wish. When you're mounted, rapidly hitting the keybind will then dismount you.

**Comment by VadoZhadar** [comment]
Ahhh, thank you :) That option wasnt clear to me. Of course, this solves my issue. Cheers
